#!/usr/bin/env bash
# Capture a canonical, live `claude --output-format stream-json` Mac golden for
# VAL-P0-STREAM-028 (Windows-port master plan §7.3 G0 criterion #5).
#
# This is the REPRODUCTION recipe for the committed golden pair:
#   AgentLensTests/Fixtures/StreamGolden/claude-stream-mac-golden.jsonl        (RAW)
#   AgentLensTests/Fixtures/StreamGolden/claude-stream-mac-golden-events.json  (parsed, via the test)
#
# It runs the GENUINE `claude` binary directly (not a PATH wrapper shim) in a
# stripped environment with --setting-sources "" so the system/init line is
# canonical (no personal skills / plugins / MCP servers / dev-wrapper hook lines),
# then applies one deterministic, event-neutral PII redaction to the sole
# machine-specific field (system/init.memory_paths, which the stream parser never
# reads). The parsed events golden is (re)generated by the parse-diff XCTest, not
# by this script — see docs/windows-port/STREAM_JSON_MAC_GOLDEN.md.
#
# Requires: an authenticated Claude Code install (OAuth via the default ~/.claude
# config dir) and Claude Code >= 2.1.x. NEVER hand-forge the stream — if `claude`
# cannot run authenticated in this environment, STOP and escalate a named blocker.
set -euo pipefail

MARKER="${OBB_STREAM_MARKER:-BURNBAR_STREAM_GOLDEN_MARKER_7F3A9C2E}"
MODEL="${OBB_STREAM_MODEL:-claude-haiku-4-5}"
PROMPT="There is a file named marker.txt in the current working directory. Use the Bash tool to run: cat marker.txt — to read its contents. Then reply with ONLY the exact one-line contents of that file and nothing else. Do not guess; you must actually run the command to learn the value."

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
dest="$repo_root/AgentLensTests/Fixtures/StreamGolden/claude-stream-mac-golden.jsonl"

# Resolve the REAL claude binary, skipping any PATH wrapper shim (e.g. a
# cmux/tmux dev shim) that would inject hook_started/session_state_changed lines.
real_claude=""
for cand in \
  "${OBB_REAL_CLAUDE:-}" \
  "${CMUX_AGENT_LAUNCH_EXECUTABLE:-}" \
  "$HOME/.nvm/versions/node/"*/bin/claude \
  "$HOME/.homebrew/bin/claude" \
  /opt/homebrew/bin/claude \
  /usr/local/bin/claude; do
  [ -n "$cand" ] || continue
  # A genuine binary is a Mach-O / node script, never a tiny shell shim in a temp shim dir.
  case "$cand" in *cmux-cli-shims*) continue;; esac
  if [ -x "$cand" ] && ! grep -qs "command claude" "$cand" 2>/dev/null; then
    real_claude="$cand"; break
  fi
done
if [ -z "$real_claude" ]; then
  echo "ERROR: could not resolve the genuine claude binary. Set OBB_REAL_CLAUDE." >&2
  exit 1
fi
echo "Using claude binary: $real_claude" >&2
"$real_claude" --version >&2 || true

workdir="$(mktemp -d "${TMPDIR:-/tmp}/obb-stream028.XXXXXX")"
trap 'rm -rf "$workdir"' EXIT
printf '%s' "$MARKER" > "$workdir/marker.txt"   # no trailing newline -> bare tool_result detail
raw="$workdir/stream.jsonl"

( cd "$workdir" && env -i \
    HOME="$HOME" USER="${USER:-$(id -un)}" LANG="en_US.UTF-8" LC_ALL="en_US.UTF-8" \
    PATH="$(dirname "$real_claude"):/usr/bin:/bin:/usr/sbin:/sbin" \
    "$real_claude" -p "$PROMPT" \
      --model "$MODEL" \
      --output-format stream-json --verbose \
      --strict-mcp-config \
      --setting-sources "" --disable-slash-commands \
      --allowedTools Bash --permission-mode acceptEdits \
      > "$raw" )

# Fail closed on an unauthenticated / empty capture — do NOT commit a dead stream.
if grep -q "Not logged in" "$raw" || ! grep -q '"subtype": *"init"\|"subtype":"init"' "$raw"; then
  echo "ERROR: capture is not a valid authenticated stream (no init line / not logged in)." >&2
  echo "----- captured stdout head -----" >&2; head -5 "$raw" >&2
  exit 1
fi

# One deterministic, event-neutral PII redaction: local home path in the inert
# system/init.memory_paths field -> canonical placeholder. Parser never reads it.
python3 - "$raw" "$dest" "$HOME" <<'PY'
import sys, json
raw_path, dest_path, home = sys.argv[1], sys.argv[2], sys.argv[3]
text = open(raw_path, encoding="utf-8").read().replace(home, "/Users/openburnbar")
lines = [ln for ln in text.split("\n") if ln.strip() != ""]
for ln in lines:
    json.loads(ln)  # every line must be valid JSON
open(dest_path, "w", encoding="utf-8").write("\n".join(lines) + "\n")
print(f"wrote {dest_path} ({len(lines)} lines, {text.count('/Users/openburnbar')} redaction(s))")
PY

echo "Done. Regenerate the parsed events golden via the XCTest:" >&2
echo "  TEST_RUNNER_OPENBURNBAR_STREAM_GOLDEN_OUT=/tmp/obb-stream-golden-out \\" >&2
echo "    scripts/test-openburnbar-app.sh -only-testing:OpenBurnBarTests/ClaudeStreamGoldenParseDiffTests" >&2
