// Generated by scripts/generate-pixel-clock-logos.py.
// Do not edit by hand; regenerate after bundled provider logo asset changes.

import Foundation

enum PixelClockProviderLogoAssets {
    static let claudeCode = PixelClockProviderLogo(
        sourceName: "OpenClawLogo",
        pixels: [
            [nil, nil, nil, nil, nil, nil, nil, nil],
            [nil, "#D97757", "#D97757", "#D97757", "#D97757", "#D97757", "#D97757", nil],
            [nil, "#D97757", "#1A1208", "#D97757", "#D97757", "#1A1208", "#D97757", nil],
            ["#D97757", "#D97757", "#D97757", "#D97757", "#D97757", "#D97757", "#D97757", "#D97757"],
            ["#D97757", "#D97757", "#D97757", "#D97757", "#D97757", "#D97757", "#D97757", "#D97757"],
            ["#D97757", nil, "#D97757", nil, nil, "#D97757", nil, "#D97757"],
            ["#D97757", nil, "#D97757", nil, nil, "#D97757", nil, "#D97757"],
            [nil, nil, nil, nil, nil, nil, nil, nil]
        ]
    )

    static let codex = PixelClockProviderLogo(
        sourceName: "CodexLogo",
        pixels: [
            [nil, nil, "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF", nil, nil],
            [nil, "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF", nil],
            ["#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF"],
            ["#8EA0FF", "#8EA0FF", "#FFFFFF", "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF"],
            ["#8EA0FF", "#8EA0FF", "#8EA0FF", "#FFFFFF", "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF"],
            ["#8EA0FF", "#8EA0FF", "#FFFFFF", "#8EA0FF", "#8EA0FF", "#FFFFFF", "#FFFFFF", "#FFFFFF"],
            [nil, "#4258FF", "#4258FF", "#4258FF", "#4258FF", "#4258FF", "#4258FF", nil],
            [nil, nil, "#4258FF", "#4258FF", "#4258FF", "#4258FF", nil, nil]
        ]
    )

    static let copilot = PixelClockProviderLogo(
        sourceName: "CopilotLogo",
        pixels: [
            [nil, "#0F4E70", "#1A80B6", "#187DB4", "#1050A2", "#091F60", nil, nil],
            ["#05293E", "#118BD1", "#1397E1", "#148FDD", "#1558D0", "#1652BA", "#031121", nil],
            ["#1B656E", "#2BA1AF", "#2EA3A9", "#257F90", "#172C62", "#675CBC", "#7350AF", "#572E73"],
            ["#529F62", "#60B46C", "#66B666", "#305A32", "#381429", "#C64FAF", "#BB51CC", "#B24FCB"],
            ["#A5BB36", "#AFC033", "#ABB92D", "#2A310B", "#762D45", "#E55898", "#D954A7", "#BC4A97"],
            ["#6C610A", "#AC8D13", "#D19422", "#75341D", "#CD5E5E", "#F46A80", "#F16187", "#963B57"],
            [nil, nil, "#D26238", "#F36544", "#F88D61", "#F9886D", "#E6756A", "#452121"],
            [nil, nil, "#67251B", "#B05634", "#BA7B40", "#BA7445", "#72442D", nil]
        ]
    )

    static let miniMax = PixelClockProviderLogo(
        sourceName: "MiniMaxLogo",
        pixels: [
            ["#EC1970", "#EC1970", nil, "#FF5B3F", "#FF5B3F", nil, "#EC1970", "#EC1970"],
            ["#EC1970", "#EC1970", nil, "#FF5B3F", "#FF5B3F", nil, "#EC1970", "#EC1970"],
            ["#EC1970", "#EC1970", "#FF5B3F", "#FF5B3F", "#FF5B3F", "#EC1970", "#EC1970", "#EC1970"],
            ["#EC1970", "#EC1970", nil, "#FF5B3F", "#FF5B3F", nil, "#EC1970", "#EC1970"],
            ["#EC1970", "#EC1970", nil, "#FF5B3F", "#FF5B3F", nil, "#EC1970", "#EC1970"],
            ["#EC1970", "#EC1970", "#FF5B3F", "#FF5B3F", "#FF5B3F", "#EC1970", "#EC1970", "#EC1970"],
            ["#EC1970", "#EC1970", nil, "#FF5B3F", "#FF5B3F", nil, "#EC1970", "#EC1970"],
            ["#EC1970", "#EC1970", nil, "#FF5B3F", "#FF5B3F", nil, "#EC1970", "#EC1970"]
        ]
    )

    static let zai = PixelClockProviderLogo(
        sourceName: "ZaiLogo",
        pixels: [
            ["#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", nil],
            ["#C9B6FF", "#C9B6FF", "#C9B6FF", "#C9B6FF", "#C9B6FF", "#C9B6FF", "#C9B6FF", nil],
            [nil, nil, nil, nil, "#FFFFFF", "#FFFFFF", "#FFFFFF", nil],
            [nil, nil, nil, "#FFFFFF", "#FFFFFF", "#FFFFFF", nil, nil],
            [nil, nil, "#FFFFFF", "#FFFFFF", "#FFFFFF", nil, nil, nil],
            [nil, "#FFFFFF", "#FFFFFF", "#FFFFFF", nil, nil, nil, nil],
            [nil, "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF"],
            [nil, "#C9B6FF", "#C9B6FF", "#C9B6FF", "#C9B6FF", "#C9B6FF", "#C9B6FF", "#C9B6FF"]
        ]
    )

    static let factory = PixelClockProviderLogo(
        sourceName: "FactoryLogo",
        pixels: [
            ["#FFFFFF", nil, nil, "#FFFFFF", "#FFFFFF", nil, nil, "#FFFFFF"],
            [nil, "#FFFFFF", nil, "#FFFFFF", "#FFFFFF", nil, "#FFFFFF", nil],
            [nil, nil, "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", nil, nil],
            ["#FFFFFF", "#FFFFFF", "#FFFFFF", "#B8B8B8", "#B8B8B8", "#FFFFFF", "#FFFFFF", "#FFFFFF"],
            ["#FFFFFF", "#FFFFFF", "#FFFFFF", "#B8B8B8", "#B8B8B8", "#FFFFFF", "#FFFFFF", "#FFFFFF"],
            [nil, nil, "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", nil, nil],
            [nil, "#FFFFFF", nil, "#FFFFFF", "#FFFFFF", nil, "#FFFFFF", nil],
            ["#FFFFFF", nil, nil, "#FFFFFF", "#FFFFFF", nil, nil, "#FFFFFF"]
        ]
    )

    static let cursor = PixelClockProviderLogo(
        sourceName: "CursorLogo",
        pixels: [
            ["#FFFFFF", "#F9F9F9", "#B3B3B3", "#333333", "#333333", "#B3B3B3", "#F9F9F9", "#FFFFFF"],
            ["#DDDDDD", "#7D7D7D", "#252525", "#0F0F0F", "#0F0F0F", "#232323", "#7C7C7C", "#DEDEDE"],
            ["#797979", "#565656", "#B9B9B9", "#D2D2D2", "#CFCFCF", "#D0D0D0", "#ABABAB", "#8D8D8D"],
            ["#6B6B6B", "#030303", "#3C3C3C", "#B0B0B0", "#FCFCFC", "#FFFFFF", "#787878", "#6B6B6B"],
            ["#6C6C6C", "#000000", "#000000", "#242424", "#E6E6E6", "#CBCBCB", "#171717", "#6A6A6A"],
            ["#727272", "#000000", "#000000", "#1F1F1F", "#D8D8D8", "#5B5B5B", "#000000", "#727272"],
            ["#DADADA", "#6C6C6C", "#101010", "#212121", "#8D8D8D", "#1E1E1E", "#6B6B6B", "#D9D9D9"],
            ["#FFFFFF", "#FAFAFA", "#B3B3B3", "#464646", "#5A5A5A", "#B2B2B2", "#FAFAFA", "#FFFFFF"]
        ]
    )

    static let warp = PixelClockProviderLogo(
        sourceName: "WarpLogo",
        pixels: [
            ["#FFFFFF", "#FBFBFB", "#F4F5F6", "#F4F5F6", "#F5F6F7", "#F5F6F7", "#FBFBFB", "#FFFFFF"],
            ["#FCFCFC", "#DCE0E3", "#D0D6DA", "#CFD5D9", "#D0D6DA", "#D0D6DA", "#DCE0E3", "#FBFCFC"],
            ["#F6F7F8", "#CCD2D6", "#ADB2B6", "#A1A6AA", "#6E7173", "#777A7C", "#C4C9CD", "#F6F7F8"],
            ["#F5F6F7", "#B3B8BC", "#3B3C3D", "#47494A", "#282828", "#373838", "#B2B7BB", "#F5F6F7"],
            ["#F4F5F6", "#ACB1B4", "#313233", "#4B4C4D", "#323333", "#494A4B", "#B4B9BD", "#F4F5F6"],
            ["#F4F5F6", "#C1C6CA", "#787B7D", "#8C8F92", "#ADB1B5", "#BBC0C4", "#CFD5D9", "#F3F5F5"],
            ["#FBFCFC", "#E3E8EB", "#D4DADE", "#D2D8DC", "#D8DEE2", "#D6DCE0", "#E1E6E9", "#FBFCFC"],
            ["#FFFFFF", "#FCFCFC", "#F5F7F7", "#F5F7F7", "#F6F7F8", "#F6F8F8", "#FCFCFD", "#FFFFFF"]
        ]
    )

    static let ollama = PixelClockProviderLogo(
        sourceName: "OllamaLogo",
        pixels: [
            [nil, "#F6F8FF", nil, nil, nil, nil, "#F6F8FF", nil],
            [nil, "#F6F8FF", "#F6F8FF", nil, nil, "#F6F8FF", "#F6F8FF", nil],
            ["#F6F8FF", "#F6F8FF", "#F6F8FF", "#F6F8FF", "#F6F8FF", "#F6F8FF", "#F6F8FF", "#F6F8FF"],
            ["#F6F8FF", "#F6F8FF", "#1EA7FF", nil, nil, "#1EA7FF", "#F6F8FF", "#F6F8FF"],
            ["#F6F8FF", "#F6F8FF", "#F6F8FF", "#F6F8FF", "#F6F8FF", "#F6F8FF", "#F6F8FF", "#F6F8FF"],
            ["#F6F8FF", "#AEB7C2", "#AEB7C2", "#F6F8FF", "#F6F8FF", "#AEB7C2", "#AEB7C2", "#F6F8FF"],
            [nil, "#F6F8FF", "#F6F8FF", "#F6F8FF", "#F6F8FF", "#F6F8FF", "#F6F8FF", nil],
            [nil, nil, "#F6F8FF", "#F6F8FF", "#F6F8FF", "#F6F8FF", nil, nil]
        ]
    )

    static let kimi = PixelClockProviderLogo(
        sourceName: "KimiLogo",
        pixels: [
            [nil, nil, nil, nil, nil, nil, "#0A2E57", "#136CD2"],
            [nil, "#919191", nil, nil, "#828282", "#858585", "#0F1C2B", "#052040"],
            ["#252525", "#C2C2C2", "#2F2F2F", "#8B8B8B", "#C2C2C2", "#2D2D2D", nil, nil],
            ["#242424", "#C9C9C9", "#B2B2B2", "#D7D7D7", "#303030", nil, nil, nil],
            ["#232323", "#DFDFDF", "#DDDDDD", "#D3D3D3", "#8D8D8D", nil, nil, nil],
            ["#242424", "#CDCDCD", "#404040", "#313131", "#B8B8B8", "#C3C3C3", "#2F2F2F", nil],
            [nil, "#7C7C7C", nil, nil, nil, "#6F6F6F", "#343434", nil],
            [nil, nil, nil, nil, nil, nil, nil, nil]
        ]
    )
}
