// Generated by scripts/generate-pixel-clock-logos.py.
// Do not edit by hand; regenerate after bundled provider logo asset changes.

import Foundation

enum PixelClockProviderLogoAssets {
    static let claudeCode = PixelClockProviderLogo(
        sourceName: "OpenClawLogo",
        pixels: [
            [nil, nil, nil, nil, nil, nil, nil, nil],
            [nil, "#D97757", "#D97757", "#D97757", "#D97757", "#D97757", "#D97757", nil],
            [nil, "#D97757", "#1A1208", "#D97757", "#D97757", "#1A1208", "#D97757", nil],
            ["#D97757", "#D97757", "#D97757", "#D97757", "#D97757", "#D97757", "#D97757", "#D97757"],
            ["#D97757", "#D97757", "#D97757", "#D97757", "#D97757", "#D97757", "#D97757", "#D97757"],
            ["#D97757", nil, "#D97757", nil, nil, "#D97757", nil, "#D97757"],
            ["#D97757", nil, "#D97757", nil, nil, "#D97757", nil, "#D97757"],
            [nil, nil, nil, nil, nil, nil, nil, nil]
        ]
    )

    static let codex = PixelClockProviderLogo(
        sourceName: "CodexLogo",
        pixels: [
            [nil, nil, "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF", nil, nil],
            [nil, "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF", nil],
            ["#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF"],
            ["#8EA0FF", "#8EA0FF", "#FFFFFF", "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF"],
            ["#8EA0FF", "#8EA0FF", "#8EA0FF", "#FFFFFF", "#8EA0FF", "#8EA0FF", "#8EA0FF", "#8EA0FF"],
            ["#8EA0FF", "#8EA0FF", "#FFFFFF", "#8EA0FF", "#8EA0FF", "#FFFFFF", "#FFFFFF", "#FFFFFF"],
            [nil, "#4258FF", "#4258FF", "#4258FF", "#4258FF", "#4258FF", "#4258FF", nil],
            [nil, nil, "#4258FF", "#4258FF", "#4258FF", "#4258FF", nil, nil]
        ]
    )

    static let copilot = PixelClockProviderLogo(
        sourceName: "CopilotLogo",
        pixels: [
            [nil, "#0F4E70", "#1A80B6", "#187DB4", "#1050A2", "#091F60", nil, nil],
            ["#05293E", "#118BD1", "#1397E1", "#148FDD", "#1558D0", "#1652BA", "#031121", nil],
            ["#1B656E", "#2BA1AF", "#2EA3A9", "#257F90", "#172C62", "#675CBC", "#7350AF", "#572E73"],
            ["#529F62", "#60B46C", "#66B666", "#305A32", "#381429", "#C64FAF", "#BB51CC", "#B24FCB"],
            ["#A5BB36", "#AFC033", "#ABB92D", "#2A310B", "#762D45", "#E55898", "#D954A7", "#BC4A97"],
            ["#6C610A", "#AC8D13", "#D19422", "#75341D", "#CD5E5E", "#F46A80", "#F16187", "#963B57"],
            [nil, nil, "#D26238", "#F36544", "#F88D61", "#F9886D", "#E6756A", "#452121"],
            [nil, nil, "#67251B", "#B05634", "#BA7B40", "#BA7445", "#72442D", nil]
        ]
    )

    static let miniMax = PixelClockProviderLogo(
        sourceName: "MiniMaxLogo",
        pixels: [
            ["#EC1970", nil, nil, "#EC1970", "#EC1970", nil, nil, "#EC1970"],
            ["#EC1970", "#EC1970", nil, "#EC1970", "#EC1970", nil, "#EC1970", "#EC1970"],
            ["#EC1970", "#EC1970", "#EC1970", "#EC1970", "#EC1970", "#EC1970", "#EC1970", "#EC1970"],
            ["#EC1970", nil, nil, "#EC1970", "#EC1970", nil, nil, "#EC1970"],
            ["#FF5B3F", nil, nil, "#FF5B3F", "#FF5B3F", nil, nil, "#FF5B3F"],
            ["#FF5B3F", "#FF5B3F", nil, "#FF5B3F", "#FF5B3F", nil, "#FF5B3F", "#FF5B3F"],
            ["#FF5B3F", "#FF5B3F", "#FF5B3F", "#FF5B3F", "#FF5B3F", "#FF5B3F", "#FF5B3F", "#FF5B3F"],
            ["#FF5B3F", nil, nil, "#FF5B3F", "#FF5B3F", nil, nil, "#FF5B3F"]
        ]
    )

    static let zai = PixelClockProviderLogo(
        sourceName: "ZaiLogo",
        pixels: [
            ["#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", nil],
            ["#C9B6FF", "#C9B6FF", "#C9B6FF", "#C9B6FF", "#C9B6FF", "#C9B6FF", "#C9B6FF", nil],
            [nil, nil, nil, nil, "#FFFFFF", "#FFFFFF", "#FFFFFF", nil],
            [nil, nil, nil, "#FFFFFF", "#FFFFFF", "#FFFFFF", nil, nil],
            [nil, nil, "#FFFFFF", "#FFFFFF", "#FFFFFF", nil, nil, nil],
            [nil, "#FFFFFF", "#FFFFFF", "#FFFFFF", nil, nil, nil, nil],
            [nil, "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF"],
            [nil, "#C9B6FF", "#C9B6FF", "#C9B6FF", "#C9B6FF", "#C9B6FF", "#C9B6FF", "#C9B6FF"]
        ]
    )

    static let factory = PixelClockProviderLogo(
        sourceName: "FactoryLogo",
        pixels: [
            [nil, nil, nil, "#FFFFFF", nil, nil, nil, nil],
            [nil, "#FFFFFF", nil, "#FFFFFF", nil, "#FFFFFF", nil, nil],
            ["#FFFFFF", nil, "#FFFFFF", nil, "#FFFFFF", nil, "#FFFFFF", nil],
            [nil, "#FFFFFF", "#FFFFFF", "#B8B8B8", "#FFFFFF", "#FFFFFF", nil, nil],
            ["#FFFFFF", nil, "#FFFFFF", nil, "#FFFFFF", nil, "#FFFFFF", nil],
            [nil, "#FFFFFF", nil, "#FFFFFF", nil, "#FFFFFF", nil, nil],
            [nil, nil, nil, "#FFFFFF", nil, nil, nil, nil],
            [nil, nil, nil, nil, nil, nil, nil, nil]
        ]
    )

    static let cursor = PixelClockProviderLogo(
        sourceName: "CursorLogo",
        pixels: [
            [nil, nil, nil, nil, nil, nil, nil, nil],
            [nil, nil, nil, "#FFFFFF", "#FFFFFF", nil, nil, nil],
            [nil, nil, "#FFFFFF", "#AEB7C2", "#AEB7C2", "#FFFFFF", nil, nil],
            [nil, "#FFFFFF", "#AEB7C2", "#30343A", "#7F8790", "#FFFFFF", nil, nil],
            [nil, nil, "#30343A", "#30343A", "#7F8790", nil, nil, nil],
            [nil, nil, nil, "#30343A", nil, nil, nil, nil],
            [nil, nil, nil, nil, nil, nil, nil, nil],
            [nil, nil, nil, nil, nil, nil, nil, nil]
        ]
    )

    static let warp = PixelClockProviderLogo(
        sourceName: "WarpLogo",
        pixels: [
            ["#DDE4EA", "#DDE4EA", "#DDE4EA", "#DDE4EA", nil, nil, nil, nil],
            ["#DDE4EA", "#A8B0B8", "#DDE4EA", "#DDE4EA", nil, nil, nil, nil],
            ["#DDE4EA", "#DDE4EA", "#A8B0B8", "#DDE4EA", nil, nil, nil, nil],
            [nil, "#6B7380", "#6B7380", "#DDE4EA", "#DDE4EA", nil, nil, nil],
            [nil, nil, nil, "#DDE4EA", "#DDE4EA", "#6B7380", "#6B7380", nil],
            [nil, nil, nil, nil, "#DDE4EA", "#A8B0B8", "#DDE4EA", "#DDE4EA"],
            [nil, nil, nil, nil, "#DDE4EA", "#DDE4EA", "#A8B0B8", "#DDE4EA"],
            [nil, nil, nil, nil, "#DDE4EA", "#DDE4EA", "#DDE4EA", "#DDE4EA"]
        ]
    )

    static let ollama = PixelClockProviderLogo(
        sourceName: "OllamaLogo",
        pixels: [
            [nil, nil, "#F6F8FF", nil, nil, nil, nil, nil],
            [nil, "#F6F8FF", "#F6F8FF", "#F6F8FF", nil, nil, nil, nil],
            [nil, nil, "#F6F8FF", "#F6F8FF", "#F6F8FF", "#F6F8FF", nil, nil],
            [nil, nil, "#F6F8FF", "#1EA7FF", "#F6F8FF", "#F6F8FF", nil, nil],
            [nil, nil, "#F6F8FF", "#F6F8FF", "#F6F8FF", "#0B0B0B", nil, nil],
            [nil, nil, nil, "#F6F8FF", "#F6F8FF", "#F6F8FF", nil, nil],
            [nil, nil, nil, "#F6F8FF", "#F6F8FF", nil, nil, nil],
            [nil, nil, nil, "#F6F8FF", "#F6F8FF", nil, nil, nil]
        ]
    )

    static let kimi = PixelClockProviderLogo(
        sourceName: "KimiLogo",
        pixels: [
            [nil, nil, nil, nil, nil, nil, "#0A2E57", "#136CD2"],
            [nil, "#919191", nil, nil, "#828282", "#858585", "#0F1C2B", "#052040"],
            ["#252525", "#C2C2C2", "#2F2F2F", "#8B8B8B", "#C2C2C2", "#2D2D2D", nil, nil],
            ["#242424", "#C9C9C9", "#B2B2B2", "#D7D7D7", "#303030", nil, nil, nil],
            ["#232323", "#DFDFDF", "#DDDDDD", "#D3D3D3", "#8D8D8D", nil, nil, nil],
            ["#242424", "#CDCDCD", "#404040", "#313131", "#B8B8B8", "#C3C3C3", "#2F2F2F", nil],
            [nil, "#7C7C7C", nil, nil, nil, "#6F6F6F", "#343434", nil],
            [nil, nil, nil, nil, nil, nil, nil, nil]
        ]
    )

    static let deepSeek = PixelClockProviderLogo(
        sourceName: "DeepSeekLogo",
        pixels: [
            [nil, nil, "#6366F1", "#6366F1", "#6366F1", "#6366F1", nil, nil],
            [nil, "#6366F1", "#6366F1", "#6366F1", "#6366F1", "#6366F1", "#6366F1", nil],
            ["#6366F1", "#FFFFFF", "#6366F1", "#6366F1", "#6366F1", "#6366F1", "#6366F1", "#6366F1"],
            ["#6366F1", "#6366F1", "#6366F1", "#6366F1", "#6366F1", "#6366F1", "#6366F1", "#6366F1"],
            [nil, "#6366F1", "#6366F1", "#6366F1", "#6366F1", "#6366F1", "#6366F1", "#6366F1"],
            [nil, nil, "#6366F1", "#6366F1", "#6366F1", "#6366F1", nil, "#6366F1"],
            [nil, nil, nil, "#6366F1", "#6366F1", nil, "#6366F1", "#6366F1"],
            [nil, nil, nil, nil, nil, nil, nil, nil]
        ]
    )

    static let openCode = PixelClockProviderLogo(
        sourceName: "OpenCodeLogo",
        pixels: [
            ["#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF"],
            ["#FFFFFF", nil, nil, nil, nil, nil, nil, "#FFFFFF"],
            ["#FFFFFF", nil, nil, nil, nil, nil, nil, "#FFFFFF"],
            ["#FFFFFF", nil, "#5A5858", "#5A5858", "#5A5858", "#5A5858", nil, "#FFFFFF"],
            ["#FFFFFF", nil, "#5A5858", "#5A5858", "#5A5858", "#5A5858", nil, "#FFFFFF"],
            ["#FFFFFF", nil, nil, nil, nil, nil, nil, "#FFFFFF"],
            ["#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF"],
            [nil, nil, nil, nil, nil, nil, nil, nil]
        ]
    )

    static let antigravity = PixelClockProviderLogo(
        sourceName: "GeminiCLILogo",
        pixels: [
            [nil, nil, nil, "#34A853", "#FFEB3B", nil, nil, nil],
            [nil, nil, "#00BCD4", "#34A853", "#FFEB3B", "#FF9800", nil, nil],
            [nil, "#00BCD4", "#00BCD4", nil, nil, "#FF9800", "#FF9800", nil],
            [nil, "#4285F4", "#00BCD4", nil, nil, "#FF9800", "#E91E63", nil],
            ["#4285F4", "#4285F4", nil, nil, nil, nil, "#E91E63", "#E91E63"],
            ["#4285F4", nil, nil, nil, nil, nil, nil, "#E91E63"],
            [nil, nil, nil, nil, nil, nil, nil, nil],
            [nil, nil, nil, nil, nil, nil, nil, nil]
        ]
    )
}
