// Generated by scripts/gen/mission-runtime-catalog.mjs from tools/schema-sync/fixtures/mission-runtime-catalog.json. Do not edit.
package com.openburnbar.data.catalog

data class MissionRuntimeCatalog(
    val rows: List<Row>,
) {
    enum class Surface { SWITCHER, ASSISTANT, FLEET, CHAT_BACKEND, CLI_RUNTIME, RESUME_TARGET, MISSION_CREATE, MISSION_EVENT, MISSION_MIRROR, MISSION_RECEIPT, GRANT_RUNTIME }
    enum class Launch { NONE, ARGV, ACP }
    enum class Platform { MACOS, IOS, ANDROID, WINDOWS, LINUX }

    data class Row(
        val id: String,
        val wireAliases: List<String>,
        val displayName: String,
        val surfaces: Set<Surface>,
        val launch: Launch,
        val platforms: Set<Platform>,
    )

    private val aliasToId: Map<String, String> =
        rows.flatMap { row -> row.wireAliases.map { it to row.id } }.toMap()

    fun canonicalId(token: String): String? = aliasToId[token]

    fun contains(token: String): Boolean = aliasToId.containsKey(token)

    fun covers(tokens: Collection<String>): Boolean = tokens.all { contains(it) }

    companion object {
        @JvmField
        val generated: MissionRuntimeCatalog = MissionRuntimeCatalog(
            rows = listOf(
        Row(
            id = "hermes",
            wireAliases = listOf("hermes"),
            displayName = "Hermes",
            surfaces = setOf(Surface.ASSISTANT, Surface.FLEET, Surface.CHAT_BACKEND, Surface.MISSION_CREATE, Surface.MISSION_EVENT, Surface.MISSION_MIRROR, Surface.MISSION_RECEIPT, Surface.GRANT_RUNTIME),
            launch = Launch.NONE,
            platforms = setOf(Platform.MACOS, Platform.IOS, Platform.ANDROID, Platform.WINDOWS, Platform.LINUX),
        ),
        Row(
            id = "pi",
            wireAliases = listOf("pi", "piagent", "pi_agent", "pi-agent", "piAgent"),
            displayName = "Pi",
            surfaces = setOf(Surface.SWITCHER, Surface.ASSISTANT, Surface.FLEET, Surface.CHAT_BACKEND, Surface.MISSION_CREATE, Surface.MISSION_EVENT, Surface.MISSION_MIRROR, Surface.MISSION_RECEIPT, Surface.GRANT_RUNTIME),
            launch = Launch.NONE,
            platforms = setOf(Platform.MACOS, Platform.IOS, Platform.ANDROID, Platform.WINDOWS, Platform.LINUX),
        ),
        Row(
            id = "codex",
            wireAliases = listOf("codex"),
            displayName = "Codex",
            surfaces = setOf(Surface.SWITCHER, Surface.ASSISTANT, Surface.FLEET, Surface.CHAT_BACKEND, Surface.CLI_RUNTIME, Surface.RESUME_TARGET, Surface.MISSION_CREATE, Surface.MISSION_EVENT, Surface.MISSION_MIRROR, Surface.MISSION_RECEIPT, Surface.GRANT_RUNTIME),
            launch = Launch.NONE,
            platforms = setOf(Platform.MACOS, Platform.IOS, Platform.ANDROID, Platform.WINDOWS, Platform.LINUX),
        ),
        Row(
            id = "claude",
            wireAliases = listOf("claude", "claude-code", "claudecode", "claude_code"),
            displayName = "Claude Code",
            surfaces = setOf(Surface.SWITCHER, Surface.ASSISTANT, Surface.FLEET, Surface.CHAT_BACKEND, Surface.CLI_RUNTIME, Surface.RESUME_TARGET, Surface.MISSION_CREATE, Surface.MISSION_EVENT, Surface.MISSION_MIRROR, Surface.MISSION_RECEIPT, Surface.GRANT_RUNTIME),
            launch = Launch.NONE,
            platforms = setOf(Platform.MACOS, Platform.IOS, Platform.ANDROID, Platform.WINDOWS, Platform.LINUX),
        ),
        Row(
            id = "openclaw",
            wireAliases = listOf("openclaw", "open-claw", "openClaw"),
            displayName = "OpenClaw",
            surfaces = setOf(Surface.ASSISTANT, Surface.CHAT_BACKEND, Surface.CLI_RUNTIME, Surface.MISSION_CREATE, Surface.MISSION_EVENT, Surface.MISSION_MIRROR, Surface.MISSION_RECEIPT, Surface.GRANT_RUNTIME),
            launch = Launch.NONE,
            platforms = setOf(Platform.MACOS, Platform.IOS, Platform.ANDROID, Platform.WINDOWS, Platform.LINUX),
        ),
        Row(
            id = "openclaude",
            wireAliases = listOf("openclaude", "open-claude", "openClaude"),
            displayName = "OpenClaude",
            surfaces = setOf(Surface.ASSISTANT, Surface.CHAT_BACKEND, Surface.CLI_RUNTIME, Surface.MISSION_CREATE, Surface.MISSION_EVENT, Surface.MISSION_MIRROR, Surface.MISSION_RECEIPT, Surface.GRANT_RUNTIME),
            launch = Launch.NONE,
            platforms = setOf(Platform.MACOS, Platform.IOS, Platform.ANDROID),
        ),
        Row(
            id = "omp",
            wireAliases = listOf("omp", "ohmypi", "oh-my-pi"),
            displayName = "OMP",
            surfaces = setOf(Surface.SWITCHER, Surface.ASSISTANT, Surface.CHAT_BACKEND, Surface.CLI_RUNTIME, Surface.MISSION_CREATE, Surface.MISSION_EVENT, Surface.MISSION_MIRROR, Surface.MISSION_RECEIPT, Surface.GRANT_RUNTIME),
            launch = Launch.NONE,
            platforms = setOf(Platform.MACOS, Platform.IOS, Platform.ANDROID, Platform.WINDOWS, Platform.LINUX),
        ),
        Row(
            id = "droid",
            wireAliases = listOf("droid", "factory", "factory-droid", "factorydroid"),
            displayName = "Droid",
            surfaces = setOf(Surface.SWITCHER, Surface.ASSISTANT, Surface.FLEET, Surface.CHAT_BACKEND, Surface.CLI_RUNTIME, Surface.RESUME_TARGET, Surface.MISSION_CREATE, Surface.MISSION_EVENT, Surface.MISSION_MIRROR, Surface.MISSION_RECEIPT, Surface.GRANT_RUNTIME),
            launch = Launch.NONE,
            platforms = setOf(Platform.MACOS, Platform.IOS, Platform.ANDROID, Platform.WINDOWS, Platform.LINUX),
        ),
        Row(
            id = "forge",
            wireAliases = listOf("forge", "forge-dev", "forgedev"),
            displayName = "Forge",
            surfaces = setOf(Surface.SWITCHER, Surface.ASSISTANT, Surface.CHAT_BACKEND, Surface.CLI_RUNTIME, Surface.RESUME_TARGET, Surface.MISSION_CREATE, Surface.MISSION_EVENT, Surface.MISSION_MIRROR, Surface.MISSION_RECEIPT, Surface.GRANT_RUNTIME),
            launch = Launch.NONE,
            platforms = setOf(Platform.MACOS, Platform.IOS, Platform.ANDROID, Platform.WINDOWS, Platform.LINUX),
        ),
        Row(
            id = "antigravity",
            wireAliases = listOf("antigravity", "agy", "google-antigravity", "googleantigravity"),
            displayName = "Antigravity",
            surfaces = setOf(Surface.SWITCHER, Surface.ASSISTANT, Surface.CHAT_BACKEND, Surface.CLI_RUNTIME, Surface.RESUME_TARGET, Surface.MISSION_CREATE, Surface.MISSION_EVENT, Surface.MISSION_MIRROR, Surface.MISSION_RECEIPT, Surface.GRANT_RUNTIME),
            launch = Launch.ARGV,
            platforms = setOf(Platform.MACOS, Platform.IOS, Platform.ANDROID, Platform.WINDOWS, Platform.LINUX),
        ),
        Row(
            id = "grok",
            wireAliases = listOf("grok", "grok-build", "xai", "grok-agent", "grok-cli"),
            displayName = "Grok Build",
            surfaces = setOf(Surface.SWITCHER, Surface.ASSISTANT, Surface.FLEET, Surface.CLI_RUNTIME, Surface.RESUME_TARGET, Surface.MISSION_CREATE, Surface.MISSION_EVENT, Surface.MISSION_MIRROR, Surface.MISSION_RECEIPT, Surface.GRANT_RUNTIME, Surface.CHAT_BACKEND),
            launch = Launch.ACP,
            platforms = setOf(Platform.MACOS, Platform.IOS, Platform.ANDROID, Platform.WINDOWS, Platform.LINUX),
        ),
        Row(
            id = "grok-bot",
            wireAliases = listOf("grok-bot"),
            displayName = "Grok Bot",
            surfaces = setOf(Surface.FLEET),
            launch = Launch.NONE,
            platforms = setOf(Platform.MACOS, Platform.LINUX),
        ),
        Row(
            id = "cursoragent",
            wireAliases = listOf("cursoragent", "cursorAgent", "cursor_agent", "cursor-agent", "cursor"),
            displayName = "Cursor Agent",
            surfaces = setOf(Surface.SWITCHER, Surface.ASSISTANT, Surface.FLEET, Surface.CHAT_BACKEND, Surface.CLI_RUNTIME, Surface.RESUME_TARGET, Surface.MISSION_CREATE, Surface.MISSION_EVENT, Surface.MISSION_MIRROR, Surface.MISSION_RECEIPT, Surface.GRANT_RUNTIME),
            launch = Launch.NONE,
            platforms = setOf(Platform.MACOS, Platform.IOS, Platform.ANDROID, Platform.WINDOWS, Platform.LINUX),
        ),
        Row(
            id = "junie",
            wireAliases = listOf("junie", "jetbrains-junie", "jetbrainsjunie"),
            displayName = "Junie",
            surfaces = setOf(Surface.SWITCHER, Surface.ASSISTANT, Surface.CHAT_BACKEND, Surface.CLI_RUNTIME, Surface.RESUME_TARGET, Surface.MISSION_CREATE, Surface.MISSION_EVENT, Surface.MISSION_MIRROR, Surface.MISSION_RECEIPT, Surface.GRANT_RUNTIME),
            launch = Launch.NONE,
            platforms = setOf(Platform.MACOS, Platform.IOS, Platform.ANDROID, Platform.WINDOWS, Platform.LINUX),
        ),
        Row(
            id = "gemini",
            wireAliases = listOf("gemini", "gemini-cli", "geminicli"),
            displayName = "Gemini CLI",
            surfaces = setOf(Surface.SWITCHER, Surface.RESUME_TARGET, Surface.FLEET, Surface.MISSION_CREATE, Surface.MISSION_EVENT, Surface.MISSION_MIRROR, Surface.MISSION_RECEIPT, Surface.GRANT_RUNTIME),
            launch = Launch.NONE,
            platforms = setOf(Platform.MACOS, Platform.IOS, Platform.ANDROID, Platform.WINDOWS, Platform.LINUX),
        ),
        Row(
            id = "kimi",
            wireAliases = listOf("kimi", "kimi-code", "kimi-cli"),
            displayName = "Kimi",
            surfaces = setOf(Surface.SWITCHER, Surface.FLEET, Surface.MISSION_CREATE, Surface.MISSION_EVENT, Surface.MISSION_MIRROR, Surface.MISSION_RECEIPT, Surface.GRANT_RUNTIME, Surface.CHAT_BACKEND, Surface.CLI_RUNTIME),
            launch = Launch.ACP,
            platforms = setOf(Platform.MACOS, Platform.IOS, Platform.ANDROID, Platform.WINDOWS, Platform.LINUX),
        ),
        Row(
            id = "prime-agent",
            wireAliases = listOf("prime-agent", "primeagent", "primeAgent"),
            displayName = "Prime Agent",
            surfaces = setOf(Surface.SWITCHER, Surface.MISSION_CREATE, Surface.MISSION_EVENT, Surface.MISSION_MIRROR, Surface.MISSION_RECEIPT, Surface.GRANT_RUNTIME),
            launch = Launch.NONE,
            platforms = setOf(Platform.MACOS, Platform.WINDOWS, Platform.LINUX),
        ),
        Row(
            id = "fx",
            wireAliases = listOf("fx", "vercel-fx", "vercelfx"),
            displayName = "Fx",
            surfaces = setOf(Surface.SWITCHER, Surface.MISSION_CREATE, Surface.MISSION_EVENT, Surface.MISSION_MIRROR, Surface.MISSION_RECEIPT, Surface.GRANT_RUNTIME),
            launch = Launch.NONE,
            platforms = setOf(Platform.MACOS, Platform.WINDOWS),
        ),
        Row(
            id = "opencode",
            wireAliases = listOf("opencode"),
            displayName = "OpenCode",
            surfaces = setOf(Surface.SWITCHER, Surface.RESUME_TARGET, Surface.MISSION_CREATE, Surface.MISSION_EVENT, Surface.MISSION_MIRROR, Surface.MISSION_RECEIPT, Surface.GRANT_RUNTIME),
            launch = Launch.NONE,
            platforms = setOf(Platform.MACOS, Platform.WINDOWS, Platform.LINUX),
        ),
        Row(
            id = "ollama",
            wireAliases = listOf("ollama"),
            displayName = "Ollama",
            surfaces = setOf(Surface.MISSION_CREATE, Surface.MISSION_EVENT, Surface.MISSION_MIRROR, Surface.MISSION_RECEIPT),
            launch = Launch.NONE,
            platforms = setOf(Platform.MACOS, Platform.LINUX),
        ),
        Row(
            id = "auto",
            wireAliases = listOf("auto"),
            displayName = "Auto",
            surfaces = setOf(Surface.MISSION_CREATE, Surface.MISSION_EVENT),
            launch = Launch.NONE,
            platforms = setOf(Platform.MACOS, Platform.IOS, Platform.ANDROID, Platform.WINDOWS, Platform.LINUX),
        )
            ),
        )

        @JvmStatic
        fun loadFixture(): MissionRuntimeCatalog = generated
    }
}
