"""Cross-platform interop tests for ``gateway.crypto.relay_e2ee``.

These mirror the Kotlin suite (``HermesRelayWireVectorTest.kt`` +
``HermesRelayCryptoTest.kt``): Python opens the *same* Swift-generated wire
vector (``tests/gateway/fixtures/HermesRelayWireVector.json``), proving the
Python port is byte-for-byte wire-compatible with the canonical Swift
``HermesRelayCrypto``. The vector itself is generated by
``swift test --package-path OpenBurnBarCore --filter HermesRelayCrossPlatformVectorTests``
and vendored verbatim; its ``revision`` is asserted as the contract key.

``cryptography`` is imported lazily inside the module under test; if it is
unavailable the whole module skips (matching the fork's lazy-import policy).
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

import pytest

pytest.importorskip("cryptography")

from gateway.crypto import relay_e2ee  # noqa: E402

_FIXTURE_PATH = Path(__file__).resolve().parent / "fixtures" / "HermesRelayWireVector.json"


@pytest.fixture(scope="module")
def vector() -> dict:
    with _FIXTURE_PATH.open("r", encoding="utf-8") as handle:
        return json.load(handle)


@pytest.fixture(scope="module")
def symmetric_key(vector) -> bytes:
    return base64.b64decode(vector["symmetricKey"])


@pytest.fixture(scope="module")
def recipient_private_key(vector) -> relay_e2ee.RelayPrivateKey:
    return relay_e2ee.RelayPrivateKey.from_base64(vector["recipientPrivateKey"])


def _request_aad(vector) -> bytes:
    return relay_e2ee.request_aad(
        vector["uid"], vector["connectionId"], vector["requestId"]
    )


def _key_aad(vector) -> bytes:
    return relay_e2ee.key_aad(
        vector["uid"], vector["connectionId"], vector["requestId"]
    )


def _chunk_aad(vector) -> bytes:
    return relay_e2ee.chunk_aad(
        vector["uid"],
        vector["connectionId"],
        vector["requestId"],
        vector["chunkSequence"],
        vector["chunkKind"],
    )


# ---------------------------------------------------------------------------
# Contract / fixture sanity
# ---------------------------------------------------------------------------


def test_fixture_revision_is_the_contract_key(vector):
    assert vector["revision"] == "v1"
    assert vector["algorithm"] == relay_e2ee.ALGORITHM


# ---------------------------------------------------------------------------
# A. AAD strings byte-match the fixture
# ---------------------------------------------------------------------------


def test_aad_strings_byte_match_fixture(vector):
    assert _request_aad(vector) == vector["requestAAD"].encode("utf-8")
    assert _key_aad(vector) == vector["keyAAD"].encode("utf-8")
    assert _chunk_aad(vector) == vector["chunkAAD"].encode("utf-8")


def test_aad_prefixes_are_namespaced():
    assert (
        relay_e2ee.request_aad("u", "c", "r")
        == b"OpenBurnBar-HermesRelay-v1|request|u|c|r"
    )
    assert relay_e2ee.key_aad("u", "c", "r") == b"OpenBurnBar-HermesRelay-v1|key|u|c|r"
    assert (
        relay_e2ee.chunk_aad("u", "c", "r", 0, "sse")
        == b"OpenBurnBar-HermesRelay-v1|chunk|u|c|r|0|sse"
    )


def test_piagent_namespace_swaps_prefix():
    assert (
        relay_e2ee.request_aad("u", "c", "r", namespace=relay_e2ee.PIAGENT_NAMESPACE)
        == b"OpenBurnBar-PiAgentRelay-v1|request|u|c|r"
    )
    assert (
        relay_e2ee.key_aad("u", "c", "r", namespace=relay_e2ee.PIAGENT_NAMESPACE)
        == b"OpenBurnBar-PiAgentRelay-v1|key|u|c|r"
    )


# ---------------------------------------------------------------------------
# B. Python opens Swift-sealed material (the core direction)
# ---------------------------------------------------------------------------


def test_python_unwraps_swift_wrapped_key(vector, recipient_private_key, symmetric_key):
    unwrapped = relay_e2ee.unwrap_symmetric_key(
        vector["wrappedKey"], recipient_private_key, _key_aad(vector)
    )
    assert unwrapped == symmetric_key


def test_python_unwraps_swift_wrapped_key_from_raw_bytes(
    vector, symmetric_key
):
    raw = base64.b64decode(vector["recipientPrivateKey"])
    unwrapped = relay_e2ee.unwrap_symmetric_key(
        vector["wrappedKey"], raw, _key_aad(vector)
    )
    assert unwrapped == symmetric_key


def test_python_opens_swift_payload_ciphertext(vector, symmetric_key):
    plaintext = relay_e2ee.open_base64(
        vector["payloadCiphertext"], symmetric_key, _request_aad(vector)
    )
    # Byte-for-byte equal to the Swift JSONEncoder output.
    assert plaintext == base64.b64decode(vector["encodedPlaintext"])
    decoded = json.loads(plaintext.decode("utf-8"))
    assert decoded["path"] == vector["plaintextPath"]
    assert decoded["sessionId"] == vector["plaintextSessionId"]
    assert decoded["body"] == vector["plaintextBody"]


def test_python_opens_swift_chunk_ciphertext(vector, symmetric_key):
    plaintext = relay_e2ee.open_base64(
        vector["chunkCiphertext"], symmetric_key, _chunk_aad(vector)
    )
    assert plaintext.decode("utf-8") == vector["chunkPlaintext"]


def test_recipient_public_key_matches_fixture(vector, recipient_private_key):
    assert recipient_private_key.public_key_base64() == vector["recipientPublicKey"]


# ---------------------------------------------------------------------------
# C. Python reseal / round-trip (proves Python emits valid wire format)
# ---------------------------------------------------------------------------


def test_python_reseal_round_trip_with_unwrapped_swift_key(
    vector, recipient_private_key
):
    symmetric_key = relay_e2ee.unwrap_symmetric_key(
        vector["wrappedKey"], recipient_private_key, _key_aad(vector)
    )
    aad = relay_e2ee.chunk_aad(
        vector["uid"], vector["connectionId"], vector["requestId"], 1, "sse"
    )
    plaintext = b"data: reply from python"
    sealed = relay_e2ee.seal_to_base64(plaintext, symmetric_key, aad)
    assert relay_e2ee.open_base64(sealed, symmetric_key, aad) == plaintext


def test_python_wrap_then_python_unwrap_round_trip():
    private_key = relay_e2ee.generate_private_key()
    symmetric_key = relay_e2ee.generate_symmetric_key()
    aad = relay_e2ee.key_aad("u", "c", "r")

    wrapped = relay_e2ee.wrap_symmetric_key(
        symmetric_key, private_key.public_key_base64(), aad
    )
    raw = base64.b64decode(wrapped)
    # Envelope shape: ephPub(65) ‖ nonce(12) ‖ ct(32) ‖ tag(16) == 125 bytes.
    assert len(raw) == 125
    assert raw[0] == 0x04

    unwrapped = relay_e2ee.unwrap_symmetric_key(wrapped, private_key, aad)
    assert unwrapped == symmetric_key


def test_combined_shape_for_sixteen_byte_plaintext():
    symmetric_key = relay_e2ee.generate_symmetric_key()
    aad = relay_e2ee.request_aad("u", "c", "r")
    sealed = relay_e2ee.seal_to_base64(b"0123456789abcdef", symmetric_key, aad)
    raw = base64.b64decode(sealed)
    # nonce(12) ‖ ct(16) ‖ tag(16) == 44 bytes.
    assert len(raw) == 44


# ---------------------------------------------------------------------------
# D. Adversarial / invariants
# ---------------------------------------------------------------------------


def test_open_with_wrong_aad_raises_invalid_tag(vector, symmetric_key):
    from cryptography.exceptions import InvalidTag

    wrong_aad = relay_e2ee.request_aad("u-other", vector["connectionId"], vector["requestId"])
    with pytest.raises(InvalidTag):
        relay_e2ee.open_base64(vector["payloadCiphertext"], symmetric_key, wrong_aad)


def test_unwrap_with_wrong_aad_raises_invalid_tag(vector, recipient_private_key):
    from cryptography.exceptions import InvalidTag

    wrong_aad = relay_e2ee.key_aad("u-other", vector["connectionId"], vector["requestId"])
    with pytest.raises(InvalidTag):
        relay_e2ee.unwrap_symmetric_key(vector["wrappedKey"], recipient_private_key, wrong_aad)


def test_unwrap_with_wrong_recipient_key_fails(vector):
    from cryptography.exceptions import InvalidTag

    other = relay_e2ee.generate_private_key()
    with pytest.raises(InvalidTag):
        relay_e2ee.unwrap_symmetric_key(vector["wrappedKey"], other, _key_aad(vector))


def test_two_wraps_of_same_key_are_distinct_but_both_unwrap():
    private_key = relay_e2ee.generate_private_key()
    symmetric_key = relay_e2ee.generate_symmetric_key()
    aad = relay_e2ee.key_aad("u", "c", "r")
    pub = private_key.public_key_base64()

    first = relay_e2ee.wrap_symmetric_key(symmetric_key, pub, aad)
    second = relay_e2ee.wrap_symmetric_key(symmetric_key, pub, aad)

    assert first != second  # ephemeral randomization
    assert relay_e2ee.unwrap_symmetric_key(first, private_key, aad) == symmetric_key
    assert relay_e2ee.unwrap_symmetric_key(second, private_key, aad) == symmetric_key


def test_seal_with_short_key_raises():
    with pytest.raises(relay_e2ee.InvalidSymmetricKeyError):
        relay_e2ee.seal_to_base64(b"hi", b"\x00" * 16, b"aad")


def test_open_with_short_key_raises():
    with pytest.raises(relay_e2ee.InvalidSymmetricKeyError):
        relay_e2ee.open_base64("AAAA", b"\x00" * 16, b"aad")


def test_unwrap_too_short_envelope_raises(vector, recipient_private_key):
    short = base64.b64encode(b"\x04" + b"\x00" * 10).decode("ascii")
    with pytest.raises(relay_e2ee.InvalidCiphertextError):
        relay_e2ee.unwrap_symmetric_key(short, recipient_private_key, _key_aad(vector))


def test_wrap_with_invalid_public_key_raises():
    symmetric_key = relay_e2ee.generate_symmetric_key()
    with pytest.raises(relay_e2ee.InvalidPublicKeyError):
        relay_e2ee.wrap_symmetric_key(symmetric_key, "not-a-key!!!", b"aad")


# ---------------------------------------------------------------------------
# E. AgentRelayIdentity persistence
# ---------------------------------------------------------------------------


def test_agent_relay_identity_loads_existing_key_from_env():
    private_key = relay_e2ee.generate_private_key()
    environ = {relay_e2ee.RELAY_PRIVATE_KEY_ENV: private_key.raw_base64()}
    identity = relay_e2ee.AgentRelayIdentity.load_or_create(environ=environ)
    assert identity.private_key == private_key
    assert identity.public_key_base64 == private_key.public_key_base64()
    assert identity.key_version == relay_e2ee.KEY_VERSION
    assert identity.algorithm == relay_e2ee.ALGORITHM


def test_agent_relay_identity_creates_and_persists_when_missing():
    persisted: dict[str, str] = {}

    def persist(env_var: str, value: str) -> None:
        persisted[env_var] = value

    identity = relay_e2ee.AgentRelayIdentity.load_or_create(environ={}, persist=persist)
    assert relay_e2ee.RELAY_PRIVATE_KEY_ENV in persisted
    # The persisted value round-trips back to the same identity.
    reloaded = relay_e2ee.AgentRelayIdentity.load_or_create(
        environ={relay_e2ee.RELAY_PRIVATE_KEY_ENV: persisted[relay_e2ee.RELAY_PRIVATE_KEY_ENV]}
    )
    assert reloaded.private_key == identity.private_key


def test_agent_relay_identity_mints_fresh_on_corrupt_env():
    identity = relay_e2ee.AgentRelayIdentity.load_or_create(
        environ={relay_e2ee.RELAY_PRIVATE_KEY_ENV: "not-base64-!!"}
    )
    assert isinstance(identity.private_key, relay_e2ee.RelayPrivateKey)


def test_minted_key_is_written_back_into_environ_for_stable_reload():
    """A minted key lands in the provided environ so an in-process reload is stable."""
    environ: dict[str, str] = {}
    first = relay_e2ee.AgentRelayIdentity.load_or_create(environ=environ)
    # The minted key was written back into the live environ map.
    assert environ.get(relay_e2ee.RELAY_PRIVATE_KEY_ENV) == first.private_key.raw_base64()
    # A second load from the SAME environ returns the SAME identity (no rotation).
    second = relay_e2ee.AgentRelayIdentity.load_or_create(environ=environ)
    assert second.private_key == first.private_key


def test_persist_failure_is_non_fatal_and_key_kept_in_process():
    """A throwing persist callback never loses the minted key (fail-stable)."""

    def boom(env_var: str, value: str) -> None:
        raise RuntimeError("disk is read-only")

    environ: dict[str, str] = {}
    identity = relay_e2ee.AgentRelayIdentity.load_or_create(environ=environ, persist=boom)
    assert isinstance(identity.private_key, relay_e2ee.RelayPrivateKey)
    # Despite the persist failure the key is still available for this run.
    assert environ.get(relay_e2ee.RELAY_PRIVATE_KEY_ENV) == identity.private_key.raw_base64()
