#!/usr/bin/env bash
# Regenerate the committed C# binding for the openburnbar-iroh cdylib.
#
# The binding is generated by uniffi-bindgen-cs from the *compiled* cdylib
# (library mode), exactly like the Swift/Kotlin lanes generate from the same
# crate, and exactly like crates/burnbar-remote/bindings/csharp/regenerate.sh.
# Re-run this after changing the `#[uniffi::export]` surface under
# crates/openburnbar-iroh/src/, then commit the diff under
# OpenBurnBarIroh.Ffi/generated/. See
# docs/windows-port/decisions/0001-csharp-binding-path.md.
#
# Toolchain pin: uniffi-bindgen-cs must match the crate's uniffi version (0.28.x).
#   cargo install uniffi-bindgen-cs \
#     --git https://github.com/NordSecurity/uniffi-bindgen-cs \
#     --tag v0.9.2+v0.28.3
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
crate_dir="$(cd "${here}/../.." && pwd)"          # crates/openburnbar-iroh
out_dir="${here}/OpenBurnBarIroh.Ffi/generated"

profile="${OPENBURNBAR_IROH_BUILD_PROFILE:-debug}"
build_flag=()
[[ "${profile}" == "release" ]] && build_flag=(--release)
# `${arr[@]+...}` keeps `set -u` happy on bash 3.2 (macOS) for empty arrays.

# Native library name per host OS.
case "$(uname -s)" in
  Darwin) libname="libopenburnbar_iroh.dylib" ;;
  Linux)  libname="libopenburnbar_iroh.so" ;;
  *)      libname="openburnbar_iroh.dll" ;;
esac

echo "==> Building the openburnbar-iroh cdylib (${profile})"
( cd "${crate_dir}" && cargo build ${build_flag[@]+"${build_flag[@]}"} )

lib_path="${crate_dir}/target/${profile}/${libname}"
[[ -f "${lib_path}" ]] || { echo "cdylib not found: ${lib_path}" >&2; exit 1; }

echo "==> Generating C# bindings from ${lib_path}"
mkdir -p "${out_dir}"
# Run from the crate dir: library mode shells out to `cargo metadata`, which
# needs a Cargo.toml at or above the CWD.
( cd "${crate_dir}" && uniffi-bindgen-cs \
    --library "${lib_path}" \
    --config "${crate_dir}/uniffi.toml" \
    --out-dir "${out_dir}" )

echo "==> Done. Review + commit ${out_dir}/openburnbar_iroh.cs"
