"""Adversarial secret-gate suite.

Every secret shape the shared corpus flags standalone is planted in eight
places a caller controls -- prose, a key/value line, a fenced code block, a
tag, an entity, a metadata value and a source ref -- and every policy is held
to its promise:

* ``redact``: the verbatim token survives in no surface the engine can return,
  and not in the raw bytes of the store either;
* ``reject``: the write is refused and no row lands;
* ``retain``: the vault decrypts to the verbatim token while the plaintext
  body and the file bytes still do not contain it.

Seeded, offline, and dependency-free: the tokens come from
``eval_memory.SECRET_SHAPES``, generated by ``random.Random(20260902)`` so
nothing of token shape is ever committed; the embedding provider is off, so no
network or Ollama call happens.

Auxiliary fields are gated on their raw, pre-normalization form, so a tag is
held to the same promise as the body even though the stored tag is lowercased.
``test_an_aws_key_in_an_aux_field_is_gated_before_normalization`` pins that
directly with the shape that exposed the bug.
"""

from __future__ import annotations

import base64
import json
import sys
from pathlib import Path
from typing import Any

import pytest

MCP_DIR = Path(__file__).resolve().parents[1]
if str(MCP_DIR) not in sys.path:
    sys.path.insert(0, str(MCP_DIR))

import eval_memory  # noqa: E402
import memory_engine as me  # noqa: E402

SHAPES: dict[str, str] = eval_memory.SECRET_SHAPES
FIXED_KEY = base64.b64encode(bytes(range(32))).decode("ascii")
RECALL_QUERY = "burnbar release runner credential rotated"

BODY_CONTEXTS = ("prose_middle", "prose_end", "key_line", "code_fence")
AUX_CONTEXTS = ("tag", "entity", "metadata", "source_ref")
CONTEXTS = BODY_CONTEXTS + AUX_CONTEXTS


def detected_shapes() -> dict[str, str]:
    """The shapes the corpus flags standalone -- the only ones this suite can hold
    the gate to. A shape the scanner cannot see is a corpus gap, not a gate bug;
    `eval_memory.run_gate_matrix` is where that coverage is reported."""
    return {name: token for name, token in SHAPES.items() if me.scan_text(token).secret_labels}


DETECTED = detected_shapes()

# Lowercased, an AWS access key id matches no corpus pattern and sits under the
# entropy floor, so it is the shape that catches a gate running after
# `normalize_tags` instead of before it.
CASE_SENSITIVE_SHAPE = "aws_access_key_id"


def _prose(label: str) -> str:
    return f"The {label} credential for the burnbar release runner is rotated every ninety days."


def _write_kwargs(context: str, label: str, token: str) -> dict[str, Any]:
    """The `remember` arguments that plant `token` in `context`."""
    prose = _prose(label)
    bodies = {
        "prose_middle": f"{prose} It is currently {token} and only the runner may read it.",
        "prose_end": f"{prose} The current value is {token}",
        "key_line": f"{prose}\ncredential: {token}",
        "code_fence": f"{prose}\n\n```sh\nexport RUNNER_CREDENTIAL={token}\n```",
    }
    if context in bodies:
        return {"text": bodies[context]}
    aux: dict[str, dict[str, Any]] = {
        "tag": {"tags": [token]},
        "entity": {"entities": [token]},
        "metadata": {"metadata": {"credential": token}},
        "source_ref": {"source_ref": token},
    }
    return {"text": prose, **aux[context]}


def _strings(value: Any, found: list[str] | None = None) -> list[str]:
    """Every string anywhere in a returned payload, dict keys included."""
    out = [] if found is None else found
    if isinstance(value, str):
        out.append(value)
    elif isinstance(value, dict):
        for key, item in value.items():
            _strings(key, out)
            _strings(item, out)
    elif isinstance(value, (list, tuple)):
        for item in value:
            _strings(item, out)
    return out


def _open(db_path: Path, *, secret_policy: str, retain_allowed: bool = False) -> me.MemoryEngine:
    return me.MemoryEngine.open(
        db_path,
        provider=me.NullEmbeddingProvider("adversarial gate suite"),
        config=me.EngineConfig(secret_policy=secret_policy, pii_policy="keep", retain_allowed=retain_allowed),
    )


def _store_bytes(db_path: Path) -> bytes:
    """The store as it sits on disk: the main file plus any un-checkpointed WAL."""
    raw = db_path.read_bytes()
    wal = db_path.with_name(db_path.name + "-wal")
    if wal.exists():
        raw += wal.read_bytes()
    return raw


def _tokens_on_disk(db_path: Path) -> list[str]:
    blob = _store_bytes(db_path)
    return [f"{label}: store bytes" for label, token in DETECTED.items() if token.encode("utf-8") in blob]


def _readable_surfaces(
    engine: me.MemoryEngine, project_path: str, memory_ids: list[str], results: list[dict[str, Any]]
) -> dict[str, list[str]]:
    """Every plaintext an agent can pull back out of the engine."""
    return {
        "write result": _strings(results),
        "get": _strings([engine.get(memory_id) for memory_id in memory_ids]),
        "history": _strings([engine.history(memory_id) for memory_id in memory_ids]),
        "list": _strings(engine.list(project_path=project_path, page_size=100)),
        "recall": _strings(
            engine.recall(
                RECALL_QUERY,
                project_path=project_path,
                limit=100,
                reinforce=False,
                include_quarantined=True,
                include_superseded=True,
                include_expired=True,
                include_secrets=True,
            )
        ),
        "pack": _strings(engine.recall_pack(RECALL_QUERY, project_path=project_path, token_budget=100_000, limit=100)),
        "export": _strings(engine.export(project_path=project_path, include_superseded=True)),
        "audit trail": _strings(engine.audit_trail(project_path=project_path, limit=500)),
    }


@pytest.fixture
def gate_store(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> tuple[Path, str]:
    """A throwaway store with a fixed key and no embedding provider."""
    monkeypatch.setenv(me.EMBEDDING_PROVIDER_ENV, "none")
    monkeypatch.setenv(me.MEMORY_KEY_ENV, FIXED_KEY)
    me.reset_provider_cache_for_tests()
    project = tmp_path / "repo"
    project.mkdir()
    return tmp_path / "gate.sqlite", str(project)


def test_the_corpus_detects_enough_shapes_for_this_suite_to_have_teeth():
    assert len(DETECTED) >= 12, {"detected": sorted(DETECTED), "missed": sorted(set(SHAPES) - set(DETECTED))}


@pytest.mark.parametrize("context", CONTEXTS)
def test_redact_policy_leaves_no_surface_with_the_raw_token(context: str, gate_store: tuple[Path, str]) -> None:
    db_path, project_path = gate_store
    engine = _open(db_path, secret_policy="redact")
    results: list[dict[str, Any]] = []
    memory_ids: list[str] = []
    try:
        for label, token in DETECTED.items():
            result = engine.remember(project_path=project_path, kind="fact", **_write_kwargs(context, label, token))
            results.append(result)
            if result.get("memoryID"):
                memory_ids.append(str(result["memoryID"]))
        surfaces = _readable_surfaces(engine, project_path, memory_ids, results)
    finally:
        engine.close()

    leaks = [
        f"{label}: {surface}"
        for label, token in DETECTED.items()
        for surface, values in surfaces.items()
        if any(token in value for value in values)
    ] + _tokens_on_disk(db_path)
    assert not leaks, leaks


@pytest.mark.parametrize("context", CONTEXTS)
def test_reject_policy_refuses_every_detected_shape(context: str, gate_store: tuple[Path, str]) -> None:
    db_path, project_path = gate_store
    engine = _open(db_path, secret_policy="reject")
    try:
        accepted = []
        for label, token in DETECTED.items():
            result = engine.remember(project_path=project_path, kind="fact", **_write_kwargs(context, label, token))
            if (result.get("status"), result.get("event"), result.get("code")) != (
                "rejected",
                "REJECT",
                "SECRET_DETECTED",
            ):
                accepted.append((label, result.get("status"), result.get("event"), result.get("code")))
        assert not accepted, accepted
        assert engine.list(project_path=project_path, page_size=100)["results"] == []
    finally:
        engine.close()

    assert not _tokens_on_disk(db_path)


def _found_case_insensitively(db_path: Path, token: str) -> bool:
    """Is `token` in the store bytes under any casing?

    Normalization lowercases a tag, so a case-sensitive search would miss exactly
    the leak this checks for.
    """
    return token.encode("utf-8").lower() in _store_bytes(db_path).lower()


@pytest.mark.parametrize("context", AUX_CONTEXTS)
def test_an_aws_key_in_an_aux_field_is_gated_before_normalization(context: str, gate_store: tuple[Path, str]) -> None:
    """The auxiliary gate must see the caller's raw string, not the normalized one."""
    db_path, project_path = gate_store
    token = SHAPES[CASE_SENSITIVE_SHAPE]
    planted = _write_kwargs(context, "aws", token)

    reject_db = db_path.with_name("reject.sqlite")
    engine = _open(reject_db, secret_policy="reject")
    try:
        refused = engine.remember(project_path=project_path, kind="fact", **planted)
        assert (refused.get("status"), refused.get("event"), refused.get("code")) == (
            "rejected",
            "REJECT",
            "SECRET_DETECTED",
        ), refused
        assert engine.list(project_path=project_path, page_size=100)["results"] == []
    finally:
        engine.close()
    assert not _found_case_insensitively(reject_db, token)

    engine = _open(db_path, secret_policy="redact")
    try:
        written = engine.remember(project_path=project_path, kind="fact", **planted)
        assert written["status"] == "ok", written
        surfaces = _readable_surfaces(engine, project_path, [str(written["memoryID"])], [written])
    finally:
        engine.close()

    leaks = [
        f"{surface}: {value}"
        for surface, values in surfaces.items()
        for value in values
        if token.lower() in value.lower()
    ]
    assert not leaks, leaks
    assert not _found_case_insensitively(db_path, token)


def test_a_secret_in_source_kind_is_gated_like_any_other_aux_field(gate_store: tuple[Path, str]) -> None:
    """`source_kind` is caller-supplied plaintext persisted beside the body."""
    db_path, project_path = gate_store
    token = SHAPES[CASE_SENSITIVE_SHAPE]

    reject_db = db_path.with_name("reject.sqlite")
    engine = _open(reject_db, secret_policy="reject")
    try:
        refused = engine.remember(_prose("aws"), project_path=project_path, kind="fact", source_kind=token)
        assert (refused.get("status"), refused.get("event"), refused.get("code")) == (
            "rejected",
            "REJECT",
            "SECRET_DETECTED",
        ), refused
        assert engine.list(project_path=project_path, page_size=100)["results"] == []
    finally:
        engine.close()
    assert not _found_case_insensitively(reject_db, token)

    engine = _open(db_path, secret_policy="redact")
    try:
        written = engine.remember(_prose("aws"), project_path=project_path, kind="fact", source_kind=token)
        assert written["status"] == "ok", written
        stored = engine.get(str(written["memoryID"]))["memory"]
        assert token.lower() not in str(stored["sourceKind"]).lower(), stored["sourceKind"]
    finally:
        engine.close()
    assert not _found_case_insensitively(db_path, token)


def test_oversized_auxiliary_input_is_refused_rather_than_clipped(gate_store: tuple[Path, str]) -> None:
    """A cap applied before the gate would drop a credential-bearing tag unscreened,
    so the bound refuses the write instead of quietly keeping a prefix."""
    db_path, project_path = gate_store
    engine = _open(db_path, secret_policy="redact")
    try:
        for field, payload in (
            ("tags", {"tags": [f"tag-{index}" for index in range(65)]}),
            ("entities", {"entities": [f"Entity{index}" for index in range(65)]}),
            ("metadata", {"metadata": {f"key-{index}": "value" for index in range(65)}}),
        ):
            refused = engine.remember(_prose(field), project_path=project_path, kind="fact", **payload)
            assert (refused.get("status"), refused.get("code")) == ("rejected", "AUX_TOO_LARGE"), (field, refused)
            assert "64" in str(refused.get("reason")), (field, refused)

        # The limit itself is accepted, and `update` is bounded the same way.
        ok = engine.remember(
            _prose("bounded"), project_path=project_path, kind="fact", tags=[f"tag-{index}" for index in range(64)]
        )
        assert ok["status"] == "ok", ok
        patched = engine.update(str(ok["memoryID"]), entities=[f"Entity{index}" for index in range(65)])
        assert (patched.get("status"), patched.get("code")) == ("rejected", "AUX_TOO_LARGE"), patched
        assert engine.get(str(ok["memoryID"]))["memory"]["entities"] == []
    finally:
        engine.close()


def test_memorize_refuses_oversized_batch_wide_auxiliary_input(gate_store: tuple[Path, str]) -> None:
    """`memorize` carries its own batch-wide aux (`default_tags`, `metadata`) that
    never reaches a `Fact`, so it needs the bound at its own entry point."""
    db_path, project_path = gate_store
    messages = [{"role": "user", "content": "We decided to keep the memory store local-only."}]
    engine = _open(db_path, secret_policy="redact")
    try:
        for field, payload in (
            ("default_tags", {"default_tags": [f"tag-{index}" for index in range(65)]}),
            ("metadata", {"metadata": {f"key-{index}": index for index in range(65)}}),
        ):
            refused = engine.memorize(project_path=project_path, messages=messages, **payload)
            assert (refused.get("status"), refused.get("code")) == ("rejected", "AUX_TOO_LARGE"), (field, refused)
            assert "64" in str(refused.get("reason")), (field, refused)
            assert refused["summary"] == {event: 0 for event in ("ADD", "UPDATE", "NONE", "DELETE", "REJECT")}, (
                field,
                refused,
            )
            assert refused["decisions"] == [], (field, refused)
            assert engine.list(project_path=project_path, page_size=100)["results"] == [], field
    finally:
        engine.close()


def test_the_update_bound_counts_the_caller_delta_not_the_stored_row(
    gate_store: tuple[Path, str], monkeypatch: pytest.MonkeyPatch
) -> None:
    """Stored auxiliary fields were gated when they were written.

    Counting them again on every patch would strand a row that predates the bound
    (or arrived through a historical import): it could never be edited again, not
    even to fix its text.
    """
    db_path, project_path = gate_store
    wide_metadata = {f"key-{index}": index for index in range(70)}

    engine = _open(db_path, secret_policy="redact")
    try:
        monkeypatch.setattr(me.gate, "MAX_AUX_METADATA_ENTRIES", 256)
        written = engine.remember(_prose("wide"), project_path=project_path, kind="fact", metadata=wide_metadata)
        assert written["status"] == "ok", written
        memory_id = str(written["memoryID"])
        monkeypatch.setattr(me.gate, "MAX_AUX_METADATA_ENTRIES", 64)
        assert len(engine.get(memory_id)["memory"]["metadata"]) == 70

        text_only = engine.update(memory_id, text=_prose("wide") + " Rotation is quarterly.")
        assert text_only.get("status") == "ok", text_only

        refused = engine.update(memory_id, metadata={f"extra-{index}": index for index in range(65)})
        assert (refused.get("status"), refused.get("code")) == ("rejected", "AUX_TOO_LARGE"), refused
        assert len(engine.get(memory_id)["memory"]["metadata"]) == 70
    finally:
        engine.close()


def test_one_auxiliary_value_may_not_outweigh_the_body_it_annotates(gate_store: tuple[Path, str]) -> None:
    """The count bound alone let a single two-megabyte tag into a plaintext column
    sitting beside a body truncated at `MAX_BODY_CHARS`."""
    db_path, project_path = gate_store
    over = "a" * (me.MAX_BODY_CHARS + 1)
    at_limit = "b" * me.MAX_BODY_CHARS
    engine = _open(db_path, secret_policy="redact")
    try:
        refused = engine.remember(_prose("long"), project_path=project_path, kind="fact", tags=[over])
        assert (refused.get("status"), refused.get("code")) == ("rejected", "AUX_TOO_LARGE"), refused
        assert str(me.MAX_BODY_CHARS) in str(refused.get("reason")), refused

        batch = engine.memorize(
            project_path=project_path,
            messages=[{"role": "user", "content": "We decided to keep the store local-only."}],
            default_tags=[over],
        )
        assert (batch.get("status"), batch.get("code")) == ("rejected", "AUX_TOO_LARGE"), batch

        # A per-fact tag reaches the bound through `_commit_fact`, not the
        # batch-wide check, so it needs its own case.
        per_fact = engine.memorize(
            project_path=project_path,
            facts=[{"text": "The runner reads its token from the keychain.", "tags": [over]}],
        )
        assert [item.get("code") for item in per_fact["decisions"]] == ["AUX_TOO_LARGE"], per_fact

        # A number is stored as JSON like everything else, so it is bounded by
        # what actually lands in `metadata_json`, not by `isinstance(value, str)`.
        huge_number = engine.remember(
            _prose("numeric"),
            project_path=project_path,
            kind="fact",
            metadata={"ticket": int("9" * (me.MAX_BODY_CHARS + 1))},
        )
        assert (huge_number.get("status"), huge_number.get("code")) == ("rejected", "AUX_TOO_LARGE"), huge_number

        kept = engine.remember(_prose("bounded-length"), project_path=project_path, kind="fact", tags=[at_limit])
        assert kept["status"] == "ok", kept
        assert engine.get(str(kept["memoryID"]))["memory"]["tags"] == [at_limit]

        patched = engine.update(str(kept["memoryID"]), tags=[over])
        assert (patched.get("status"), patched.get("code")) == ("rejected", "AUX_TOO_LARGE"), patched
        assert engine.get(str(kept["memoryID"]))["memory"]["tags"] == [at_limit]
    finally:
        engine.close()


def test_two_redacted_metadata_keys_do_not_collapse_into_one(gate_store: tuple[Path, str]) -> None:
    """Redaction is many-to-one: two different GitHub tokens both become
    `[REDACTED:GitHub token detected]`. Without a suffix the second key would
    overwrite the first and one of the caller's values would vanish."""
    db_path, project_path = gate_store
    first = SHAPES["github_pat"]
    # A second, distinct token of the same shape, so both keys redact to the
    # same placeholder. Derived rather than written out: no literal token.
    second = "ghp_" + first[4:][::-1]
    engine = _open(db_path, secret_policy="redact")
    try:
        written = engine.remember(
            _prose("keys"),
            project_path=project_path,
            kind="fact",
            metadata={first: "alpha", second: "beta"},
        )
        assert written["status"] == "ok", written
        metadata = engine.get(str(written["memoryID"]))["memory"]["metadata"]
    finally:
        engine.close()

    # The engine adds its own metadata (gate labels, mirror ids); only the two
    # keys the caller sent redact, and both must survive as distinct entries.
    placeholders = {key: value for key, value in metadata.items() if str(key).startswith("[REDACTED")}
    assert sorted(placeholders) == [
        "[REDACTED:GitHub token detected]",
        "[REDACTED:GitHub token detected]#2",
    ], metadata
    assert sorted(placeholders.values()) == ["alpha", "beta"], metadata
    assert first not in str(metadata) and second not in str(metadata), metadata


def _passthrough_aux(**kwargs: Any) -> Any:
    """`gate_aux_fields` with the gate removed: what the write path did before
    auxiliary fields were screened on their raw form."""
    return me.AuxGate(
        list(kwargs["tags"]),
        list(kwargs["entities"]),
        dict(kwargs["metadata"] or {}),
        kwargs.get("source_ref"),
        [],
        None,
        None,
        kwargs.get("source_kind"),
    )


def test_doctor_reports_auxiliary_secrets_left_in_plaintext_by_an_older_write(
    gate_store: tuple[Path, str],
) -> None:
    """Nothing re-examines a row once written, so rows that leaked before the fix
    would sit there unnoticed. `doctor` is where an operator finds them."""
    db_path, project_path = gate_store
    token = SHAPES[CASE_SENSITIVE_SHAPE]

    engine = _open(db_path, secret_policy="reject")
    try:
        clean = engine.remember(_prose("clean"), project_path=project_path, kind="fact", tags=["release"])
        assert clean["status"] == "ok", clean
        assert engine.doctor(project_path=project_path)["auxSecretExposure"] == []

        # Write one row the way the engine used to: gate bypassed, tag lowercased
        # on the way into the plaintext column.
        original = me._write.gate_aux_fields
        me._write.gate_aux_fields = _passthrough_aux
        try:
            leaked = engine.remember(_prose("leaked"), project_path=project_path, kind="fact", tags=[token])
        finally:
            me._write.gate_aux_fields = original
        assert leaked["status"] == "ok", leaked
        leaked_id = str(leaked["memoryID"])
        assert engine.get(leaked_id)["memory"]["tags"] == [token.lower()]

        report = engine.doctor(project_path=project_path)
    finally:
        engine.close()

    assert report["auxSecretExposure"] == [
        {"id": leaked_id, "surface": "tags", "revision": "active", "labels": ["AWS access key detected"]}
    ], report["auxSecretExposure"]
    assert report["policy"]["auxSecretExposures"] == 1, report["policy"]
    codes = [item["code"] for item in report["findings"]]
    assert "AUX_SECRET_EXPOSURE" in codes, report["findings"]
    assert report["status"] == "degraded", report["status"]
    # A complete sweep says so, and raises no incompleteness warning.
    assert report["auxScan"] == {
        "rowsScanned": 2,
        "rowsTotal": 2,
        "truncated": False,
        "skipped": None,
        "nextCursor": None,
    }, report["auxScan"]
    assert "AUX_SCAN_INCOMPLETE" not in codes, report["findings"]


def test_doctor_still_reports_a_leak_on_a_superseded_revision(gate_store: tuple[Path, str]) -> None:
    """Retiring a row does not remove its plaintext from the file, so a sweep that
    only looked at active rows would call a still-exposed store clean."""
    db_path, project_path = gate_store
    token = SHAPES[CASE_SENSITIVE_SHAPE]

    engine = _open(db_path, secret_policy="reject")
    try:
        original = me._write.gate_aux_fields
        me._write.gate_aux_fields = _passthrough_aux
        try:
            leaked = engine.remember(_prose("leaked"), project_path=project_path, kind="fact", tags=[token])
        finally:
            me._write.gate_aux_fields = original
        leaked_id = str(leaked["memoryID"])

        replacement = engine.remember(
            _prose("replacement"), project_path=project_path, kind="fact", supersedes=[leaked_id]
        )
        assert replacement["status"] == "ok", replacement
        assert engine.get(leaked_id)["memory"]["validTo"] is not None, "the leaked row should be retired"

        report = engine.doctor(project_path=project_path)
    finally:
        engine.close()

    assert report["auxSecretExposure"] == [
        {"id": leaked_id, "surface": "tags", "revision": "superseded", "labels": ["AWS access key detected"]}
    ], report["auxSecretExposure"]
    detail = next(item["detail"] for item in report["findings"] if item["code"] == "AUX_SECRET_EXPOSURE")
    assert "1 on superseded revisions" in detail, detail


def test_doctor_reports_when_the_auxiliary_scan_could_not_cover_the_store(
    gate_store: tuple[Path, str], monkeypatch: pytest.MonkeyPatch
) -> None:
    """An empty exposure list from a capped or skipped sweep looks exactly like one
    from a clean store, so the coverage is reported and the gap is a finding."""
    db_path, project_path = gate_store
    engine = _open(db_path, secret_policy="redact")
    try:
        # Four genuinely distinct bodies: near-duplicate detection would fold
        # four variations on one sentence into a single row.
        bodies = (
            "The release runner rotates its credential every ninety days.",
            "Recall packs are budgeted in tokens, not in rows.",
            "Gotcha: the WAL file must be checkpointed before a backup.",
            "We decided to keep the memory store local-only.",
        )
        for body in bodies:
            written = engine.remember(body, project_path=project_path, kind="fact")
            assert written.get("event") == "ADD", written

        monkeypatch.setattr(me._admin, "AUX_SCAN_ROW_LIMIT", 3)
        capped = engine.doctor(project_path=project_path)
        assert capped["auxScan"] == {
            "rowsScanned": 3,
            "rowsTotal": 4,
            "truncated": True,
            "skipped": None,
            "nextCursor": 3,
        }, capped["auxScan"]
        incomplete = next(item for item in capped["findings"] if item["code"] == "AUX_SCAN_INCOMPLETE")
        assert incomplete["severity"] == "warn", incomplete
        assert "3 of 4 rows scanned" in incomplete["detail"], incomplete
        # The unreachable rows are reachable: the finding names the resume point.
        assert "aux_scan_cursor=3" in incomplete["fix"], incomplete
        monkeypatch.undo()

        monkeypatch.setattr(me.gate, "GATE_CORPUS_AVAILABLE", False)
        blind = engine.doctor(project_path=project_path)
        assert blind["auxScan"] == {
            "rowsScanned": 0,
            "rowsTotal": 4,
            "truncated": False,
            "skipped": "corpus_unavailable",
            "nextCursor": None,
        }, blind["auxScan"]
        assert blind["auxSecretExposure"] == []
        blind_finding = next(item for item in blind["findings"] if item["code"] == "AUX_SCAN_INCOMPLETE")
        assert "0 of 4 rows scanned" in blind_finding["detail"], blind_finding
        assert "corpus is unavailable" in blind_finding["detail"], blind_finding
        monkeypatch.undo()

        monkeypatch.delenv("OPENBURNBAR_ACTIVE_PROJECT_PATH", raising=False)
        unscoped = engine.doctor()
        assert unscoped["auxScan"]["skipped"] == "no_project", unscoped["auxScan"]
        assert any(item["code"] == "AUX_SCAN_INCOMPLETE" for item in unscoped["findings"]), unscoped["findings"]
    finally:
        engine.close()


def test_update_refuses_an_aws_key_tag_on_its_raw_form(gate_store: tuple[Path, str]) -> None:
    """`update` patches tags through the same gate, on the same raw form."""
    db_path, project_path = gate_store
    token = SHAPES[CASE_SENSITIVE_SHAPE]
    engine = _open(db_path, secret_policy="reject")
    try:
        written = engine.remember(_prose("aws"), project_path=project_path, kind="fact")
        assert written["status"] == "ok", written
        memory_id = str(written["memoryID"])
        for patch in ({"tags": [token]}, {"add_tags": [token]}):
            refused = engine.update(memory_id, **patch)
            assert (refused.get("status"), refused.get("code")) == ("rejected", "SECRET_DETECTED"), (patch, refused)
        assert engine.get(memory_id)["memory"]["tags"] == []
    finally:
        engine.close()

    assert not _found_case_insensitively(db_path, token)


@pytest.mark.parametrize("context", CONTEXTS)
def test_retain_policy_keeps_the_verbatim_token_only_in_the_vault(context: str, gate_store: tuple[Path, str]) -> None:
    """`retain` vaults a body secret verbatim; an auxiliary field has no vault, so
    the token is redacted out of it instead of being kept anywhere."""
    db_path, project_path = gate_store
    vaulted = context in BODY_CONTEXTS
    engine = _open(db_path, secret_policy="retain", retain_allowed=True)
    bodies: dict[str, str] = {}
    results: list[dict[str, Any]] = []
    memory_ids: list[str] = []
    try:
        for label, token in DETECTED.items():
            result = engine.remember(project_path=project_path, kind="fact", **_write_kwargs(context, label, token))
            assert result["status"] == "ok", (label, result)
            results.append(result)
            memory_id = str(result["memoryID"])
            memory_ids.append(memory_id)
            opened = engine.get(memory_id, include_secrets=True)["memory"]
            if vaulted:
                assert opened["sensitivity"] == "secret", (label, opened["sensitivity"])
                assert token in opened["secretText"], label
                sealed = engine.get(memory_id, include_secrets=False)["memory"]
                assert sealed["secretAvailable"] is True, label
                assert sealed["secretText"] is None, label
            else:
                assert not opened.get("secretAvailable"), label
                assert opened.get("secretText") is None, (label, opened.get("secretText"))
            bodies[label] = opened["body"]
        surfaces = _readable_surfaces(engine, project_path, memory_ids, results)
    finally:
        engine.close()

    assert sorted(bodies) == sorted(DETECTED)
    leaks = [
        f"{label}: indexable body" for label, token in DETECTED.items() if token in bodies[label]
    ] + _tokens_on_disk(db_path)
    if not vaulted:
        # Nothing vaults an auxiliary field, so no readable surface may carry it.
        leaks += [
            f"{label}: {surface}"
            for label, token in DETECTED.items()
            for surface, values in surfaces.items()
            if any(token in value for value in values)
        ]
    assert not leaks, leaks


def test_non_string_metadata_scalars_count_toward_the_entry_bound(gate_store: tuple[Path, str]) -> None:
    """`{"samples": [0, 0, ...]}` used to count zero: only strings were counted, so a
    list of a million numbers slipped past a bound meant to cap plaintext metadata."""
    db_path, project_path = gate_store
    engine = _open(db_path, secret_policy="redact")
    try:
        for label, metadata in (
            ("numbers", {"samples": [0] * 200}),
            ("bools", {"flags": [True] * 200}),
            ("nulls", {"holes": [None] * 200}),
            ("nested", {"outer": {"inner": [1.5] * 200}}),
        ):
            refused = engine.remember(_prose(label), project_path=project_path, kind="fact", metadata=metadata)
            assert (refused.get("status"), refused.get("code")) == ("rejected", "AUX_TOO_LARGE"), (label, refused)
            assert "64" in str(refused.get("reason")), (label, refused)

        # An empty list still costs only its key, so ordinary metadata is unaffected.
        ok = engine.remember(
            _prose("small-metadata"),
            project_path=project_path,
            kind="fact",
            metadata={"hook": "SessionEnd", "attempt": 2, "samples": [1, 2, 3]},
        )
        assert ok["status"] == "ok", ok
    finally:
        engine.close()


def test_metadata_is_bounded_by_its_serialized_size(gate_store: tuple[Path, str]) -> None:
    """Few entries, each within the per-value bound, can still serialize to megabytes
    of plaintext `metadata_json`. The serialized size is bounded on its own."""
    db_path, project_path = gate_store
    assert me.gate.MAX_AUX_METADATA_JSON_CHARS == 16_384
    # Sixteen values, each comfortably under MAX_AUX_VALUE_CHARS, together over the bound.
    metadata = {f"k{index}": "v" * (me.MAX_BODY_CHARS - 1) for index in range(16)}
    assert len(json.dumps(metadata, ensure_ascii=False)) > me.gate.MAX_AUX_METADATA_JSON_CHARS
    assert me.gate._metadata_entry_count(metadata) <= me.gate.MAX_AUX_METADATA_ENTRIES

    engine = _open(db_path, secret_policy="redact")
    try:
        refused = engine.remember(_prose("bulky"), project_path=project_path, kind="fact", metadata=metadata)
        assert (refused.get("status"), refused.get("code")) == ("rejected", "AUX_TOO_LARGE"), refused
        assert str(me.gate.MAX_AUX_METADATA_JSON_CHARS) in str(refused.get("reason")), refused

        ok = engine.remember(
            _prose("compact"),
            project_path=project_path,
            kind="fact",
            metadata={"note": "x" * 1_000},
        )
        assert ok["status"] == "ok", ok
    finally:
        engine.close()


def test_the_auxiliary_scan_pages_through_a_store_larger_than_its_cap(gate_store: tuple[Path, str]) -> None:
    """A fixed LIMIT with no cursor makes the rows past the cap unreachable forever.

    The sweep hands back the last rowid it looked at, so an operator can resume
    and the union of the pages covers the whole store.
    """
    db_path, project_path = gate_store
    token = SHAPES[CASE_SENSITIVE_SHAPE]
    bodies = (
        "The release runner rotates its credential every ninety days.",
        "Recall packs are budgeted in tokens, not in rows.",
        "Gotcha: the WAL file must be checkpointed before a backup.",
        "We decided to keep the memory store local-only.",
        "The daemon mirror is off by default in this deployment.",
    )
    engine = _open(db_path, secret_policy="reject")
    try:
        original = me._write.gate_aux_fields
        me._write.gate_aux_fields = _passthrough_aux
        try:
            leaked = [
                str(engine.remember(body, project_path=project_path, kind="fact", tags=[token])["memoryID"])
                for body in bodies
            ]
        finally:
            me._write.gate_aux_fields = original
        assert len(leaked) == len(bodies)

        project_id = engine.doctor(project_path=project_path)["projectID"]

        seen: list[str] = []
        cursor: int | None = 0
        pages = 0
        while cursor is not None:
            page = engine.aux_secret_exposure(project_id, limit=2, after_rowid=cursor)
            pages += 1
            seen.extend(str(item["id"]) for item in page["exposures"])
            cursor = page["scan"]["nextCursor"]
            assert pages < 10, "the cursor must make progress"
        assert pages >= 3, pages
        assert sorted(set(seen)) == sorted(leaked), (seen, leaked)

        # A completed sweep says so: no cursor, nothing truncated.
        whole = engine.aux_secret_exposure(project_id, limit=50)
        assert whole["scan"]["nextCursor"] is None
        assert whole["scan"]["truncated"] is False
        assert whole["scan"]["rowsScanned"] == len(bodies)
    finally:
        engine.close()


def test_doctor_threads_the_auxiliary_scan_cursor_through(gate_store: tuple[Path, str]) -> None:
    """`doctor` is the only caller most operators have, so the cursor has to reach it."""
    db_path, project_path = gate_store
    engine = _open(db_path, secret_policy="redact")
    try:
        for body in (
            "The release runner rotates its credential every ninety days.",
            "Recall packs are budgeted in tokens, not in rows.",
            "Gotcha: the WAL file must be checkpointed before a backup.",
        ):
            assert engine.remember(body, project_path=project_path, kind="fact").get("event") == "ADD"

        first = engine.doctor(project_path=project_path, aux_scan_cursor=None)
        assert first["auxScan"]["rowsScanned"] == 3
        assert first["auxScan"]["nextCursor"] is None

        resumed = engine.doctor(project_path=project_path, aux_scan_cursor=1)
        assert resumed["auxScan"]["rowsScanned"] == 2, resumed["auxScan"]
    finally:
        engine.close()


def test_pro_extraction_never_sends_a_raw_secret(tmp_path, monkeypatch):
    """Every detected shape, memorized through the frontier extractor, reaches the gateway only redacted."""
    import json as _json

    from fakes.fake_gateway import FakeGateway, chat_reply
    from test_memory_providers import POLICY

    with FakeGateway(lambda p, b: chat_reply({"facts": []})) as gw:
        monkeypatch.setenv(me.MODEL_POLICY_JSON_ENV, _json.dumps(dict(POLICY, gatewayURL=gw.url)))
        router = me.ModelRouter(me.load_policy(courier=lambda: None, ttl_seconds=0))
        engine = me.MemoryEngine.open(db_path=tmp_path / "pro.sqlite", models=router)
        try:
            project = tmp_path / "project"
            project.mkdir(exist_ok=True)
            for shape, token in DETECTED.items():
                result = engine.memorize(
                    project_path=str(project),
                    messages=[{"role": "user", "content": f"The {shape} we use is {token}; keep it in 1Password."}],
                    extractor="pro",
                    force=True,
                )
                assert result["status"] == "ok", shape
            bodies = gw.bodies().lower()
            for shape, token in DETECTED.items():
                assert token.lower() not in bodies, f"{shape} reached the gateway"
        finally:
            engine.close()
