use base64::{engine::general_purpose::STANDARD as BASE64_STANDARD, Engine as _};
use futures_util::StreamExt;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, HashMap};
use std::fs::{self, OpenOptions};
use std::io::{BufRead, BufReader, Read, Write};
use std::os::unix::fs::{MetadataExt, OpenOptionsExt, PermissionsExt};
use std::os::unix::net::UnixStream;
use std::os::unix::process::CommandExt;
use std::path::{Component, Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::mpsc::Receiver;
use std::sync::{Arc, Mutex, OnceLock};
use std::thread;
use std::time::{Duration, Instant};
use tauri::ipc::Channel;
use tauri::menu::{MenuBuilder, MenuItem, MenuItemBuilder};
use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};
use tauri::{AppHandle, Emitter, Manager, RunEvent, WindowEvent, Wry};
use tauri_plugin_dialog::DialogExt;
use tauri_plugin_global_shortcut::{Code, Modifiers, ShortcutState};
use tauri_plugin_global_shortcut::{GlobalShortcut, Shortcut, ShortcutEvent};
use tauri_plugin_shell::ShellExt;

use super::{media, single_instance, update_feed};

include!("desktop/foundation.rs");
include!("desktop/shell_routing.rs");
include!("desktop/gateway.rs");
include!("desktop/daemon_runtime.rs");
include!("desktop/native_shell.rs");
include!("desktop/daemon_data_commands.rs");
include!("desktop/export_destination_commands.rs");
include!("desktop/recovery_destination_commands.rs");
include!("desktop/database_snapshot_picker_commands.rs");
include!("desktop/account_media_commands.rs");
include!("desktop/computer_use.rs");
include!("desktop/tray_runtime.rs");
include!("desktop/wallpaper_runtime.rs");
include!("desktop/tests.rs");
