/**
 * Style Dictionary v5 build for "The Pensieve" design tokens.
 *
 * DTCG sources (tokens/*.tokens.json) → platform outputs so the web
 * console, Apple apps, Android, AND the Windows/WinUI app render one product:
 *   dist/css/pensieve.css          — CSS custom properties (:root)
 *   dist/swift/PensieveTokens.swift — Swift constants (consumed by AuroraDesign)
 *   dist/compose/PensieveTokens.kt  — Kotlin constants (consumed by AuroraTheme)
 *   dist/winui/PensieveTokens.xaml  — WinUI ResourceDictionary (Color/Brush/…)
 *   dist/winui/PensieveTokens.cs    — C# constants (static PensieveTokens class)
 *
 * Native colors are emitted as their canonical string values; the CSS/Swift/
 * Kotlin/C# theme layers parse hex/rgba into Color. The WinUI XAML emitter is the
 * exception: XAML cannot parse `rgba()`, so it converts every color to the
 * `#AARRGGBB` form WinUI's XAML color parser requires. Run: node config.mjs
 */

import StyleDictionary from "style-dictionary";

/** color.mercury.bright -> colorMercuryBright ; space.4 -> space4 */
function camelName(path) {
  return path
    .map((seg, i) => (i === 0 ? seg : seg.charAt(0).toUpperCase() + seg.slice(1)))
    .join("")
    .replace(/[^A-Za-z0-9]/g, "");
}

/** color.mercury.bright -> ColorMercuryBright (C#/XAML PascalCase). */
function pascalName(path) {
  const c = camelName(path);
  return c.charAt(0).toUpperCase() + c.slice(1);
}

/** DTCG type of a token, tolerant of missing $type (falls back by root path). */
function tokenType(t) {
  const declared = String(t.$type ?? t.type ?? "").toLowerCase();
  if (declared) return declared;
  const root = t.path[0];
  if (root === "color") return "color";
  if (root === "font") return "fontfamily";
  if (root === "space" || root === "radius") return "dimension";
  return "number";
}

/** 0–255 int -> two-digit uppercase hex. */
function hex2(n) {
  return Math.max(0, Math.min(255, Math.round(n))).toString(16).padStart(2, "0").toUpperCase();
}

/**
 * Convert a CSS color (#rgb, #rrggbb, rgb()/rgba()) to the WinUI `#AARRGGBB`
 * form. WinUI's XAML parser does NOT accept `rgba(…)`, so alpha must be folded
 * into the leading byte. Fully opaque `#rrggbb` becomes `#FFrrggbb`.
 */
function toXamlColor(value) {
  const v = String(value).trim();
  const m = v.match(
    /^rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*([\d.]+)\s*)?\)$/i
  );
  if (m) {
    const a = m[4] === undefined ? 255 : parseFloat(m[4]) * 255;
    return `#${hex2(a)}${hex2(parseFloat(m[1]))}${hex2(parseFloat(m[2]))}${hex2(parseFloat(m[3]))}`;
  }
  let hex = v.replace(/^#/, "");
  if (hex.length === 3) hex = hex.split("").map((c) => c + c).join("");
  if (hex.length === 6) return `#FF${hex.toUpperCase()}`;
  if (hex.length === 8) return `#${hex.toUpperCase()}`;
  return v; // named color / unrecognized — pass through
}

/** Minimal XML text escaping for string tokens (font stacks, easing curves). */
function escapeXml(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

const GEN_HEADER = "// GENERATED by packages/design-tokens (Style Dictionary v5) — DO NOT EDIT. Sources: tokens/*.tokens.json";

StyleDictionary.registerFormat({
  name: "pensieve/swift",
  format: ({ dictionary }) => {
    const lines = [GEN_HEADER, "", "import Foundation", "", "public enum PensieveTokens {"];
    for (const t of dictionary.allTokens) {
      lines.push(`    public static let ${camelName(t.path)}: String = ${JSON.stringify(String(t.$value ?? t.value))}`);
    }
    lines.push("}", "");
    return lines.join("\n");
  },
});

StyleDictionary.registerFormat({
  name: "pensieve/compose",
  format: ({ dictionary }) => {
    const lines = [GEN_HEADER, "", "package com.openburnbar.ui.tokens", "", "object PensieveTokens {"];
    for (const t of dictionary.allTokens) {
      lines.push(`    const val ${camelName(t.path)}: String = ${JSON.stringify(String(t.$value ?? t.value))}`);
    }
    lines.push("}", "");
    return lines.join("\n");
  },
});

// C# constants (consumed by the WinUI app + the Swift↔C# provider-brand parity
// test). Mirrors pensieve/swift + pensieve/compose exactly: one string constant
// per token, canonical value verbatim — just PascalCased for C# convention.
StyleDictionary.registerFormat({
  name: "pensieve/csharp",
  format: ({ dictionary }) => {
    const lines = [
      GEN_HEADER,
      "",
      "namespace OpenBurnBar.App.Theme;",
      "",
      "/// <summary>Generated design tokens. See packages/design-tokens.</summary>",
      "public static class PensieveTokens",
      "{",
    ];
    for (const t of dictionary.allTokens) {
      lines.push(`    public const string ${pascalName(t.path)} = ${JSON.stringify(String(t.$value ?? t.value))};`);
    }
    lines.push("}", "");
    return lines.join("\n");
  },
});

// WinUI ResourceDictionary. Every color becomes a <Color> + matching
// <SolidColorBrush>; dimensions become <x:Double> (+ <CornerRadius>/<Thickness>
// convenience shapes for radius/space); numbers become <x:Double>; font stacks
// and easing curves become <x:String>. A trailing "shell semantic" block keeps
// the exact OBB* keys the WinUI shell already references (App.xaml merges this
// dictionary), resolving accent/surface/stroke to Pensieve primitives so the
// shell's brand now flows from the token pipeline.
StyleDictionary.registerFormat({
  name: "pensieve/winui-xaml",
  format: ({ dictionary }) => {
    const resolved = new Map();
    for (const t of dictionary.allTokens) resolved.set(camelName(t.path), String(t.$value ?? t.value));

    const colors = [];
    const brushes = [];
    const doubles = [];
    const corners = [];
    const thicknesses = [];
    const strings = [];

    for (const t of dictionary.allTokens) {
      const key = `Pensieve${pascalName(t.path)}`;
      const raw = String(t.$value ?? t.value);
      const type = tokenType(t);
      if (type === "color") {
        colors.push(`    <Color x:Key="${key}">${toXamlColor(raw)}</Color>`);
        brushes.push(`    <SolidColorBrush x:Key="${key}Brush" Color="{StaticResource ${key}}" />`);
      } else if (type === "dimension") {
        const n = parseFloat(raw);
        doubles.push(`    <x:Double x:Key="${key}">${n}</x:Double>`);
        if (t.path[0] === "radius") corners.push(`    <CornerRadius x:Key="${key}Corner">${n}</CornerRadius>`);
        if (t.path[0] === "space") thicknesses.push(`    <Thickness x:Key="${key}Thickness">${n}</Thickness>`);
      } else if (type === "number") {
        doubles.push(`    <x:Double x:Key="${key}">${parseFloat(raw)}</x:Double>`);
      } else {
        strings.push(`    <x:String x:Key="${key}">${escapeXml(raw)}</x:String>`);
      }
    }

    // Shell semantic aliases — the OBB* keys the WinUI shell binds to. Accent
    // resolves to the macOS Aurora ember (the shell's design oracle — see
    // tokens/aurora.tokens.json); surface / stroke resolve to Pensieve
    // primitives; the CLI-stream / mono / card values are Windows-shell
    // semantics not yet promoted to the shared token source (documented drift).
    const accent = toXamlColor(resolved.get("colorMacosEmber")); // macOS Aurora ember/CTA
    const semantic = [
      `    <Color x:Key="OBBAccentColor">${accent}</Color>`,
      `    <SolidColorBrush x:Key="OBBAccentBrush" Color="{StaticResource OBBAccentColor}" />`,
      `    <SolidColorBrush x:Key="OBBSurfaceBrush" Color="{StaticResource PensieveColorGlassLine}" />`,
      `    <SolidColorBrush x:Key="OBBStrokeBrush" Color="{StaticResource PensieveColorGlassLineBright}" />`,
      `    <SolidColorBrush x:Key="OBBStdoutBrush" Color="#FFE8E8EA" />`,
      `    <SolidColorBrush x:Key="OBBStderrBrush" Color="#FFFF8A7A" />`,
      `    <SolidColorBrush x:Key="OBBToolBrush" Color="#FF6AB0FF" />`,
      `    <SolidColorBrush x:Key="OBBSystemBrush" Color="#FF9AA0AA" />`,
      `    <x:String x:Key="OBBMonoFontFamily">ms-appx:///Assets/Fonts/jetbrains-mono.ttf#JetBrains Mono, Cascadia Mono, Consolas, Courier New</x:String>`,
      `    <CornerRadius x:Key="OBBCardCornerRadius">10</CornerRadius>`,
      `    <Thickness x:Key="OBBCardPadding">14</Thickness>`,
    ];

    return [
      '<?xml version="1.0" encoding="utf-8"?>',
      "<!--",
      "  GENERATED by packages/design-tokens (Style Dictionary v5) — DO NOT EDIT.",
      "  Sources: tokens/*.tokens.json. Regenerate + sync the in-tree shell copy with:",
      "    (cd packages/design-tokens && node config.mjs) && \\",
      "    cp packages/design-tokens/dist/winui/PensieveTokens.xaml \\",
      "       windows/app/OpenBurnBar.App/Theme/Tokens.xaml",
      "-->",
      "<ResourceDictionary",
      '    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"',
      '    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">',
      "",
      "    <!-- ── Pensieve primitives — colors (Color + SolidColorBrush) ── -->",
      ...colors,
      "",
      ...brushes,
      "",
      "    <!-- ── Pensieve primitives — dimensions + numbers (x:Double) ── -->",
      ...doubles,
      "",
      "    <!-- Convenience CornerRadius shapes (radius.*) -->",
      ...corners,
      "",
      "    <!-- Convenience Thickness shapes (space.*) -->",
      ...thicknesses,
      "",
      "    <!-- ── Pensieve primitives — font stacks + easing curves (x:String) ── -->",
      ...strings,
      "",
      "    <!-- ── Shell semantic aliases (OBB*) — keys the WinUI shell binds to. ── -->",
      ...semantic,
      "",
      "</ResourceDictionary>",
      "",
    ].join("\n");
  },
});

const sd = new StyleDictionary({
  source: ["tokens/**/*.json"],
  platforms: {
    css: {
      transformGroup: "css",
      buildPath: "dist/css/",
      files: [{ destination: "pensieve.css", format: "css/variables", options: { selector: ":root" } }],
    },
    swift: {
      transformGroup: "css",
      buildPath: "dist/swift/",
      files: [{ destination: "PensieveTokens.swift", format: "pensieve/swift" }],
    },
    compose: {
      transformGroup: "css",
      buildPath: "dist/compose/",
      files: [{ destination: "PensieveTokens.kt", format: "pensieve/compose" }],
    },
    winui: {
      transformGroup: "css",
      buildPath: "dist/winui/",
      files: [
        { destination: "PensieveTokens.xaml", format: "pensieve/winui-xaml" },
        { destination: "PensieveTokens.cs", format: "pensieve/csharp" },
      ],
    },
  },
});

await sd.cleanAllPlatforms();
await sd.buildAllPlatforms();
console.log("[design-tokens] built css + swift + compose + winui (xaml + cs) from tokens/*.tokens.json");
