/**
 * Style Dictionary v5 build for "The Pensieve" design tokens.
 *
 * One DTCG source (tokens/pensieve.tokens.json) → three platform outputs so the
 * web console, Apple apps, and Android render one product:
 *   dist/css/pensieve.css        — CSS custom properties (:root)
 *   dist/swift/PensieveTokens.swift — Swift constants (consumed by AuroraDesign)
 *   dist/compose/PensieveTokens.kt  — Kotlin constants (consumed by AuroraTheme)
 *
 * Native colors are emitted as their canonical string values; the existing
 * platform theme layers already parse hex/rgba into Color. Run: node config.mjs
 */

import StyleDictionary from "style-dictionary";

/** color.mercury.bright -> colorMercuryBright ; space.4 -> space4 */
function camelName(path) {
  return path
    .map((seg, i) => (i === 0 ? seg : seg.charAt(0).toUpperCase() + seg.slice(1)))
    .join("")
    .replace(/[^A-Za-z0-9]/g, "");
}

const GEN_HEADER = "// GENERATED by packages/design-tokens (Style Dictionary v5) — DO NOT EDIT. Source: tokens/pensieve.tokens.json";

StyleDictionary.registerFormat({
  name: "pensieve/swift",
  format: ({ dictionary }) => {
    const lines = [GEN_HEADER, "", "import Foundation", "", "public enum PensieveTokens {"];
    for (const t of dictionary.allTokens) {
      lines.push(`    public static let ${camelName(t.path)}: String = ${JSON.stringify(String(t.$value ?? t.value))}`);
    }
    lines.push("}", "");
    return lines.join("\n");
  },
});

StyleDictionary.registerFormat({
  name: "pensieve/compose",
  format: ({ dictionary }) => {
    const lines = [GEN_HEADER, "", "package com.openburnbar.ui.tokens", "", "object PensieveTokens {"];
    for (const t of dictionary.allTokens) {
      lines.push(`    const val ${camelName(t.path)}: String = ${JSON.stringify(String(t.$value ?? t.value))}`);
    }
    lines.push("}", "");
    return lines.join("\n");
  },
});

const sd = new StyleDictionary({
  source: ["tokens/**/*.json"],
  platforms: {
    css: {
      transformGroup: "css",
      buildPath: "dist/css/",
      files: [{ destination: "pensieve.css", format: "css/variables", options: { selector: ":root" } }],
    },
    swift: {
      transformGroup: "css",
      buildPath: "dist/swift/",
      files: [{ destination: "PensieveTokens.swift", format: "pensieve/swift" }],
    },
    compose: {
      transformGroup: "css",
      buildPath: "dist/compose/",
      files: [{ destination: "PensieveTokens.kt", format: "pensieve/compose" }],
    },
  },
});

await sd.cleanAllPlatforms();
await sd.buildAllPlatforms();
console.log("[design-tokens] built css + swift + compose from pensieve.tokens.json");
