import Foundation

// MARK: - Release metadata

/// One release entry from `latest-macos.json`, the direct-download update feed
/// published by `release.yml` and generated by `scripts/generate-macos-appcast.mjs`.
///
/// Trust model: the feed JSON is fetched over HTTPS from the GitHub releases
/// CDN but is **not** independently authenticated — anyone who can tamper with
/// the transport or the release assets can rewrite it. The authenticated
/// object is the DMG itself: the release pipeline runs Sparkle's
/// `sign_update`, which produces an Ed25519 signature over the **DMG file
/// bytes**, and embeds it in the feed as `sparkleEdSignature`.
/// `DirectDownloadArtifactVerifier` re-verifies that signature against the
/// `SUPublicEDKey` pinned in Info.plist after downloading and before the file
/// is ever opened.
struct DirectDownloadRelease: Equatable, Sendable {
    let version: String
    let build: String
    let downloadUrl: URL
    let appcastUrl: URL?
    let length: Int
    let sha256: String
    let sparkleEdSignature: String?
    /// Security-critical release flag (emitted by `generate-macos-appcast.mjs
    /// --critical 1`). Critical releases re-prompt even after "Later".
    let critical: Bool
}

extension DirectDownloadRelease: Decodable {
    private enum CodingKeys: String, CodingKey {
        case version
        case build
        case downloadUrl
        case appcastUrl
        case length
        case sha256
        case sparkleEdSignature
        case critical
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        version = try container.decode(String.self, forKey: .version)
        build = try container.decode(String.self, forKey: .build)
        downloadUrl = try container.decode(URL.self, forKey: .downloadUrl)
        appcastUrl = try container.decodeIfPresent(URL.self, forKey: .appcastUrl)
        length = try container.decode(Int.self, forKey: .length)
        sha256 = try container.decode(String.self, forKey: .sha256)
        sparkleEdSignature = try container.decodeIfPresent(String.self, forKey: .sparkleEdSignature)
        critical = try container.decodeIfPresent(Bool.self, forKey: .critical) ?? false
    }
}

extension DirectDownloadRelease {
    /// Numeric `CFBundleVersion` comparison first; falls back to a numeric
    /// `CFBundleShortVersionString` comparison when builds are equal or
    /// non-numeric (so `1.10.0` > `1.9.0`).
    func isNewer(thanBuild currentBuild: String, currentVersion: String) -> Bool {
        if let remote = Int(build), let local = Int(currentBuild), remote != local {
            return remote > local
        }
        return version.compare(currentVersion, options: .numeric) == .orderedDescending
    }

    var isNewerThanCurrentBundle: Bool {
        let info = Bundle.main.infoDictionary ?? [:]
        return isNewer(
            thanBuild: info["CFBundleVersion"] as? String ?? "0",
            currentVersion: info["CFBundleShortVersionString"] as? String ?? "0"
        )
    }

    /// Shape-only sanity filter for feed metadata: HTTPS scheme, download host
    /// pinned to the feed host, 64-hex digest shape, plausible length, and
    /// signature presence.
    ///
    /// This is **not** a trust decision — it cannot detect a forged feed or a
    /// swapped artifact. Trust is established exclusively by
    /// `DirectDownloadArtifactVerifier`, which checks the SHA-256 digest and
    /// verifies the Ed25519 signature over the downloaded DMG bytes against
    /// the pinned `SUPublicEDKey` before the file is opened. (Renamed from
    /// `isTrustedDirectDownloadMetadata`, which implied cryptographic trust it
    /// never provided.)
    func hasWellFormedDownloadMetadata(from feedURL: URL) -> Bool {
        guard downloadUrl.scheme == "https" else { return false }
        guard appcastUrl?.scheme != "http" else { return false }
        guard length > 0 else { return false }
        guard sha256.range(of: "^[A-Fa-f0-9]{64}$", options: .regularExpression) != nil else {
            return false
        }
        guard let sparkleEdSignature,
              !sparkleEdSignature.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return false
        }

        guard let feedHost = feedURL.host?.lowercased(),
              let downloadHost = downloadUrl.host?.lowercased() else {
            return false
        }
        return feedHost == downloadHost
    }
}
