// OpenBurnBar iroh transport binding.
//
// This is the Rust core that the OpenBurnBarIroh Swift package wraps via
// UniFFI. The surface area is intentionally tiny — eight functions that move
// us from "no transport" to "open a bidirectional stream of bytes." Anything
// richer (frame parsing, quota, runtime discriminators) lives in Swift in
// `OpenBurnBarCore/IrohRelay/` where it can reuse `HermesRelayCrypto` and
// the existing `HermesRealtimeRelayFrame` Codable model.
//
// Why so small: n0 paused official iroh-ffi releases in Feb 2025
// (https://www.iroh.computer/blog/ffi-updates). Owning the surface in-tree
// lets us pin iroh, drift on our schedule, and keep the binding green for
// macOS arm64 + iOS arm64 + iOS Simulator arm64/x86_64.

use std::net::SocketAddr;
use std::sync::Arc;
use std::time::Duration;

use iroh::{Endpoint, NodeAddr, NodeId, RelayMap, RelayMode, RelayUrl, SecretKey, Watcher};
use tokio::io::AsyncWriteExt;
use tokio::runtime::Runtime;
use tokio::sync::Mutex;

mod blobs;
mod datagrams;

#[allow(unused_imports)]
pub use blobs::{
    iroh_blobs_alpn, iroh_blobs_crate_version, parse_blob_ticket, BlobTicketBytes,
    BlobTransferStats, IrohBlobNode,
};

#[allow(unused_imports)]
pub use datagrams::{mercury_audio_alpn, IrohDatagramChannel, MERCURY_AUDIO_ALPN};

uniffi::setup_scaffolding!();

/// ALPN we negotiate over QUIC. Bumping this string forces a clean upgrade
/// boundary across iOS + Mac, mirroring `IrohRelayProtocol.alpn` in Swift.
pub const OPENBURNBAR_ALPN: &[u8] = b"openburnbar/1";

#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum IrohFfiError {
    #[error("invalid iroh secret key")]
    InvalidSecretKey,
    #[error("invalid iroh node id")]
    InvalidNodeId,
    #[error("endpoint not initialized")]
    EndpointNotInitialized,
    #[error("connect failed: {message}")]
    ConnectFailed { message: String },
    #[error("stream failed: {message}")]
    StreamFailed { message: String },
    #[error("accept failed: {message}")]
    AcceptFailed { message: String },
    #[error("shutdown failed: {message}")]
    ShutdownFailed { message: String },
    #[error("runtime failed: {message}")]
    RuntimeFailed { message: String },
}

impl IrohFfiError {
    fn connect<E: std::fmt::Display>(error: E) -> Self {
        Self::ConnectFailed {
            message: error.to_string(),
        }
    }
    fn stream<E: std::fmt::Display>(error: E) -> Self {
        Self::StreamFailed {
            message: error.to_string(),
        }
    }
    fn accept<E: std::fmt::Display>(error: E) -> Self {
        Self::AcceptFailed {
            message: error.to_string(),
        }
    }
    fn runtime<E: std::fmt::Display>(error: E) -> Self {
        Self::RuntimeFailed {
            message: error.to_string(),
        }
    }
}

/// 32 raw secret-key bytes generated by `IrohSecretKeyMaterial.generate()` on
/// the Swift side (or by `generate_secret_key_material()` for cold-start).
#[derive(uniffi::Record, Clone)]
pub struct IrohSecretKeyMaterial {
    pub raw: Vec<u8>,
}

/// 32 raw public-key bytes plus the base32 NodeId surface form (52 chars).
#[derive(uniffi::Record, Clone)]
pub struct IrohNodeIdentity {
    pub raw_public_key: Vec<u8>,
    pub node_id: String,
    pub relay_url: String,
    pub direct_addresses: Vec<String>,
}

/// Per-call options for inbound connection acceptance. Today only the
/// ALPN is configurable; we hard-pin `OPENBURNBAR_ALPN` from Swift.
#[derive(uniffi::Record, Clone)]
pub struct IrohAcceptOptions {
    pub alpn: Vec<u8>,
}

/// A single bidirectional stream, surfaced as an opaque handle to Swift so we
/// can keep the send/recv halves alive across UniFFI boundaries.
#[derive(uniffi::Object)]
pub struct IrohStream {
    inner: Mutex<Option<IrohStreamInner>>,
    runtime_handle: tokio::runtime::Handle,
}

struct IrohStreamInner {
    _conn: iroh::endpoint::Connection,
    send: iroh::endpoint::SendStream,
    recv: iroh::endpoint::RecvStream,
}

#[uniffi::export]
impl IrohStream {
    /// Write a length-prefixed JSON frame onto the stream. Length prefix is
    /// a big-endian u32 — matches `IrohRelayWireFormat.lengthPrefix` in Swift.
    pub fn send_frame(self: Arc<Self>, frame: Vec<u8>) -> Result<(), IrohFfiError> {
        let runtime_handle = self.runtime_handle.clone();
        runtime_handle.block_on(async move {
            let mut guard = self.inner.lock().await;
            let inner = guard.as_mut().ok_or(IrohFfiError::EndpointNotInitialized)?;
            let length = frame.len() as u32;
            inner
                .send
                .write_all(&length.to_be_bytes())
                .await
                .map_err(IrohFfiError::stream)?;
            inner
                .send
                .write_all(&frame)
                .await
                .map_err(IrohFfiError::stream)?;
            inner.send.flush().await.map_err(IrohFfiError::stream)?;
            Ok(())
        })
    }

    /// Read one length-prefixed JSON frame off the stream. Returns `None` on
    /// clean stream close.
    pub fn recv_frame(self: Arc<Self>) -> Result<Option<Vec<u8>>, IrohFfiError> {
        let runtime_handle = self.runtime_handle.clone();
        runtime_handle.block_on(async move {
            let mut guard = self.inner.lock().await;
            let inner = guard.as_mut().ok_or(IrohFfiError::EndpointNotInitialized)?;
            let mut len_buf = [0u8; 4];
            match inner.recv.read_exact(&mut len_buf).await {
                Ok(_) => {}
                Err(iroh::endpoint::ReadExactError::FinishedEarly(0)) => return Ok(None),
                Err(err) => return Err(IrohFfiError::stream(err)),
            }
            let length = u32::from_be_bytes(len_buf) as usize;
            let mut payload = vec![0u8; length];
            inner
                .recv
                .read_exact(&mut payload)
                .await
                .map_err(IrohFfiError::stream)?;
            Ok(Some(payload))
        })
    }

    /// Close the stream cleanly. Idempotent.
    pub fn close(self: Arc<Self>) -> Result<(), IrohFfiError> {
        let runtime_handle = self.runtime_handle.clone();
        runtime_handle.block_on(async move {
            let mut guard = self.inner.lock().await;
            if let Some(inner) = guard.take() {
                let mut send = inner.send;
                let _ = send.finish();
                let _ = send.stopped().await;
            }
            Ok(())
        })
    }
}

/// Wraps an `iroh::Endpoint` and exposes the eight-function surface the Swift
/// `OpenBurnBarIrohEndpoint` actor calls into.
#[derive(uniffi::Object)]
pub struct IrohEndpointHandle {
    endpoint: Mutex<Option<Endpoint>>,
    runtime: Mutex<Option<Runtime>>,
    runtime_handle: Mutex<Option<tokio::runtime::Handle>>,
    identity: Mutex<Option<IrohNodeIdentity>>,
}

#[uniffi::export]
impl IrohEndpointHandle {
    #[uniffi::constructor]
    pub fn new() -> Arc<Self> {
        Arc::new(Self {
            endpoint: Mutex::new(None),
            runtime: Mutex::new(None),
            runtime_handle: Mutex::new(None),
            identity: Mutex::new(None),
        })
    }

    /// Spawn the iroh endpoint with the supplied 32-byte secret key. Idempotent
    /// per handle; calling twice replaces the inner endpoint. Returns the
    /// node identity (public key + base32 NodeId).
    ///
    /// Phase 6+: callers can pass a non-empty `relay_url` to pin a specific
    /// hosted relay (e.g., the $200/mo n0 hosted tier provisioned via the
    /// services API and surfaced by `scripts/cutover-n0-hosted-relay.sh`).
    /// Empty string means "use n0's public relay set" (the default in
    /// phases 1-5).
    pub fn bootstrap(
        self: Arc<Self>,
        secret: IrohSecretKeyMaterial,
        relay_url: String,
    ) -> Result<IrohNodeIdentity, IrohFfiError> {
        if secret.raw.len() != 32 {
            return Err(IrohFfiError::InvalidSecretKey);
        }
        let mut key_bytes = [0u8; 32];
        key_bytes.copy_from_slice(&secret.raw);
        let secret_key = SecretKey::from_bytes(&key_bytes);

        let runtime = tokio::runtime::Builder::new_multi_thread()
            .enable_all()
            .worker_threads(2)
            .thread_name("openburnbar-iroh")
            .build()
            .map_err(IrohFfiError::runtime)?;

        let configured_relay_url = relay_url.trim().to_string();
        let relay_mode = if configured_relay_url.is_empty() {
            RelayMode::Default
        } else {
            let url: RelayUrl =
                configured_relay_url
                    .parse()
                    .map_err(
                        |err: iroh::RelayUrlParseError| IrohFfiError::RuntimeFailed {
                            message: format!("invalid relay url: {err}"),
                        },
                    )?;
            RelayMode::Custom(RelayMap::from(url))
        };

        let endpoint = runtime
            .block_on(async {
                Endpoint::builder()
                    .secret_key(secret_key.clone())
                    .alpns(vec![OPENBURNBAR_ALPN.to_vec()])
                    .relay_mode(relay_mode)
                    .discovery_n0()
                    .bind()
                    .await
            })
            .map_err(IrohFfiError::runtime)?;

        let identity = runtime.block_on(async {
            let selected_relay_url =
                tokio::time::timeout(Duration::from_secs(10), endpoint.home_relay().initialized())
                    .await
                    .map_err(|_| IrohFfiError::RuntimeFailed {
                        message: "iroh endpoint did not select a home relay within 10s".into(),
                    })?;
            let published_relay_url = if configured_relay_url.is_empty() {
                selected_relay_url.to_string()
            } else {
                configured_relay_url.clone()
            };

            let direct_addresses = tokio::time::timeout(
                Duration::from_secs(10),
                endpoint.direct_addresses().initialized(),
            )
            .await
            .map_err(|_| IrohFfiError::RuntimeFailed {
                message: "iroh endpoint did not publish direct addresses within 10s".into(),
            })?
            .into_iter()
            .map(|addr| addr.addr.to_string())
            .collect();

            let node_id = endpoint.node_id();
            Ok::<_, IrohFfiError>(IrohNodeIdentity {
                raw_public_key: node_id.as_bytes().to_vec(),
                node_id: node_id.to_string(),
                relay_url: published_relay_url,
                direct_addresses,
            })
        })?;

        let runtime_handle = runtime.handle().clone();
        block_on(async {
            *self.endpoint.lock().await = Some(endpoint);
            *self.runtime_handle.lock().await = Some(runtime_handle);
            *self.runtime.lock().await = Some(runtime);
            *self.identity.lock().await = Some(identity.clone());
            Ok::<_, IrohFfiError>(())
        })?;

        Ok(identity)
    }

    /// Returns the cached identity if `bootstrap` has been called.
    pub fn identity(self: Arc<Self>) -> Result<IrohNodeIdentity, IrohFfiError> {
        block_on(async move {
            self.identity
                .lock()
                .await
                .clone()
                .ok_or(IrohFfiError::EndpointNotInitialized)
        })
    }

    /// Dial a remote node by NodeId (base32 surface form) and open one
    /// bidirectional stream. The caller is responsible for stream lifetime.
    pub fn connect(
        self: Arc<Self>,
        node_id: String,
        relay_url: String,
        direct_addresses: Vec<String>,
        timeout_seconds: u32,
    ) -> Result<Arc<IrohStream>, IrohFfiError> {
        let (endpoint, runtime_handle) = block_on(async {
            let endpoint = self
                .endpoint
                .lock()
                .await
                .clone()
                .ok_or(IrohFfiError::EndpointNotInitialized)?;
            let runtime_handle = self
                .runtime_handle
                .lock()
                .await
                .clone()
                .ok_or(IrohFfiError::EndpointNotInitialized)?;
            Ok::<_, IrohFfiError>((endpoint, runtime_handle))
        })?;

        let target: NodeId = node_id.parse().map_err(|_| IrohFfiError::InvalidNodeId)?;
        let relay_url = relay_url.trim();
        let relay_url = if relay_url.is_empty() {
            None
        } else {
            Some(relay_url.parse().map_err(|err: iroh::RelayUrlParseError| {
                IrohFfiError::ConnectFailed {
                    message: format!("invalid relay url: {err}"),
                }
            })?)
        };
        let direct_addresses = direct_addresses
            .into_iter()
            .filter(|addr| !addr.trim().is_empty())
            .map(|addr| {
                addr.parse::<SocketAddr>()
                    .map_err(|err| IrohFfiError::ConnectFailed {
                        message: format!("invalid direct address {addr}: {err}"),
                    })
            })
            .collect::<Result<Vec<_>, _>>()?;
        let mut node_addr = NodeAddr::new(target);
        if let Some(relay_url) = relay_url {
            node_addr = node_addr.with_relay_url(relay_url);
        }
        if !direct_addresses.is_empty() {
            node_addr = node_addr.with_direct_addresses(direct_addresses);
        }
        let timeout = Duration::from_secs(timeout_seconds.max(1) as u64);

        let stream_runtime_handle = runtime_handle.clone();
        runtime_handle.block_on(async move {
            let (conn, send, recv) = tokio::time::timeout(timeout, async move {
                let conn = endpoint
                    .connect(node_addr, OPENBURNBAR_ALPN)
                    .await
                    .map_err(IrohFfiError::connect)?;
                let (send, recv) = conn.open_bi().await.map_err(IrohFfiError::stream)?;
                Ok::<_, IrohFfiError>((conn, send, recv))
            })
            .await
            .map_err(|_| IrohFfiError::ConnectFailed {
                message: "iroh connect timed out".into(),
            })??;
            Ok(Arc::new(IrohStream {
                inner: Mutex::new(Some(IrohStreamInner {
                    _conn: conn,
                    send,
                    recv,
                })),
                runtime_handle: stream_runtime_handle,
            }))
        })
    }

    /// Block waiting for one inbound bidirectional stream. Returns once the
    /// remote opens its first bi-stream after a successful ALPN handshake.
    pub fn accept_one(
        self: Arc<Self>,
        timeout_seconds: u32,
    ) -> Result<Arc<IrohStream>, IrohFfiError> {
        let (endpoint, runtime_handle) = block_on(async {
            let endpoint = self
                .endpoint
                .lock()
                .await
                .clone()
                .ok_or(IrohFfiError::EndpointNotInitialized)?;
            let runtime_handle = self
                .runtime_handle
                .lock()
                .await
                .clone()
                .ok_or(IrohFfiError::EndpointNotInitialized)?;
            Ok::<_, IrohFfiError>((endpoint, runtime_handle))
        })?;
        let timeout = Duration::from_secs(timeout_seconds.max(1) as u64);
        let stream_runtime_handle = runtime_handle.clone();
        runtime_handle.block_on(async move {
            let (conn, send, recv) = tokio::time::timeout(timeout, async move {
                let incoming =
                    endpoint
                        .accept()
                        .await
                        .ok_or_else(|| IrohFfiError::AcceptFailed {
                            message: "iroh endpoint closed before accepting".into(),
                        })?;
                let conn = incoming.await.map_err(IrohFfiError::accept)?;
                let (send, recv) = conn.accept_bi().await.map_err(IrohFfiError::stream)?;
                Ok::<_, IrohFfiError>((conn, send, recv))
            })
            .await
            .map_err(|_| IrohFfiError::AcceptFailed {
                message: "iroh accept timed out".into(),
            })??;
            Ok(Arc::new(IrohStream {
                inner: Mutex::new(Some(IrohStreamInner {
                    _conn: conn,
                    send,
                    recv,
                })),
                runtime_handle: stream_runtime_handle,
            }))
        })
    }

    /// Cleanly close the endpoint. After shutdown the handle is unusable.
    pub fn shutdown(self: Arc<Self>) -> Result<(), IrohFfiError> {
        let endpoint_opt = block_on(async {
            let endpoint = self.endpoint.lock().await.take();
            let runtime = self.runtime.lock().await.take();
            let _ = self.runtime_handle.lock().await.take();
            *self.identity.lock().await = None;
            Ok::<_, IrohFfiError>((endpoint, runtime))
        })?;

        if let (Some(endpoint), Some(runtime)) = endpoint_opt {
            runtime.block_on(async move {
                endpoint.close().await;
            });
            // Drop the runtime explicitly so any spawned tasks are shut down
            // before this function returns. Swift never reuses the handle
            // after shutdown.
            drop(runtime);
        }
        Ok(())
    }
}

#[uniffi::export]
pub fn generate_secret_key_material() -> IrohSecretKeyMaterial {
    let secret = SecretKey::generate(&mut rand::thread_rng());
    IrohSecretKeyMaterial {
        raw: secret.to_bytes().to_vec(),
    }
}

#[uniffi::export]
pub fn openburnbar_alpn() -> Vec<u8> {
    OPENBURNBAR_ALPN.to_vec()
}

#[uniffi::export]
pub fn openburnbar_iroh_protocol_version() -> u32 {
    1
}

pub(crate) fn block_on<F, T>(future: F) -> T
where
    F: std::future::Future<Output = T>,
{
    // Caller-side block_on runs on the iroh-owned multi-thread runtime when
    // available; otherwise we use a transient single-thread runtime for
    // construction-time work (which never holds the endpoint mutex).
    let handle = tokio::runtime::Handle::try_current();
    match handle {
        Ok(handle) => handle.block_on(future),
        Err(_) => tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .expect("tokio runtime build failed")
            .block_on(future),
    }
}
