// AUTO-GENERATED by tools/schema-sync/emit/generate.mjs — do not edit.
// Domain: community

import Foundation

public enum FirestoreConsentTriState: String, Codable, Sendable, CaseIterable {
    case unset
    case granted
    case declined
}

public enum FirestoreGeographyTier: String, Codable, Sendable, CaseIterable {
    case world
    case country
    case region
    case city
}

public struct FirestoreCommunityTierConsent: Codable, Sendable, Equatable {
    public var world: String
    public var country: String
    public var region: String
    public var city: String
}

/// Firestore: users/{uid}/community/consent
public struct FirestoreCommunityConsentDoc: Codable, Sendable, Equatable {
    public var l1Analytics: String
    public var l2Rankings: String
    public var l2Tiers: FirestoreCommunityTierConsent
    public var l3LookingGlass: String
    public var locationConsent: String
    public var schemaVersion: Int
    public var updatedAt: String
    public var optedInAt: String?
}

/// Firestore: users/{uid}/community/profile
public struct FirestoreCommunityProfileDoc: Codable, Sendable, Equatable {
    public var handle: String?
    public var anonId: String
    public var countryCode: String?
    public var regionKey: String?
    public var cityKey: String?
    public var schemaVersion: Int
    public var updatedAt: String
}

public struct FirestoreCommunityUsageTotal: Codable, Sendable, Equatable {
    public var totalTokens: Int64
    public var costUSD: Double

    public init(totalTokens: Int64 = 0, costUSD: Double = 0) {
        self.totalTokens = totalTokens
        self.costUSD = costUSD
    }
}

/// Uses CodingKeys to map the non-identifier Firestore keys (7d, 30d, 90d, all_time).
public struct FirestoreCommunityWindowTotals: Codable, Sendable, Equatable {
    public var today: FirestoreCommunityUsageTotal
    public var sevenDay: FirestoreCommunityUsageTotal
    public var thirtyDay: FirestoreCommunityUsageTotal
    public var ninetyDay: FirestoreCommunityUsageTotal
    public var allTime: FirestoreCommunityUsageTotal

    enum CodingKeys: String, CodingKey {
        case today
        case sevenDay = "7d"
        case thirtyDay = "30d"
        case ninetyDay = "90d"
        case allTime = "all_time"
    }

    public init(
        today: FirestoreCommunityUsageTotal = .init(),
        sevenDay: FirestoreCommunityUsageTotal = .init(),
        thirtyDay: FirestoreCommunityUsageTotal = .init(),
        ninetyDay: FirestoreCommunityUsageTotal = .init(),
        allTime: FirestoreCommunityUsageTotal = .init()
    ) {
        self.today = today
        self.sevenDay = sevenDay
        self.thirtyDay = thirtyDay
        self.ninetyDay = ninetyDay
        self.allTime = allTime
    }
}

/// Firestore: users/{uid}/community/share_snapshot
public struct FirestoreCommunityShareSnapshotDoc: Codable, Sendable, Equatable {
    public var windows: FirestoreCommunityWindowTotals
    public var modelMix: [String: Double]
    public var purposeMix: [String: Double]
    public var sessionCount: Int?
    public var countryCode: String?
    public var regionKey: String?
    public var cityKey: String?
    public var revoked: Bool?
    public var schemaVersion: Int
    public var updatedAt: String

    public init(
        windows: FirestoreCommunityWindowTotals = .init(),
        modelMix: [String: Double] = [:],
        purposeMix: [String: Double] = [:],
        sessionCount: Int? = nil,
        countryCode: String? = nil,
        regionKey: String? = nil,
        cityKey: String? = nil,
        revoked: Bool? = nil,
        schemaVersion: Int = 1,
        updatedAt: String = ""
    ) {
        self.windows = windows
        self.modelMix = modelMix
        self.purposeMix = purposeMix
        self.sessionCount = sessionCount
        self.countryCode = countryCode
        self.regionKey = regionKey
        self.cityKey = cityKey
        self.revoked = revoked
        self.schemaVersion = schemaVersion
        self.updatedAt = updatedAt
    }
}

public enum FirestoreRankMovement: String, Codable, Sendable, CaseIterable {
    case up
    case down
    case same
    case new
}

public struct FirestoreLeaderboardEntry: Codable, Sendable, Equatable, Identifiable {
    public var rank: Int
    public var percentile: Double
    public var handle: String?
    public var anonId: String
    public var totalTokens: Int64
    public var costUSD: Double
    public var movement: String

    public var id: String { anonId }
}

public struct FirestorePercentileBands: Codable, Sendable, Equatable {
    public var p50: Double
    public var p75: Double
    public var p90: Double
    public var p99: Double
}

/// Firestore: community_leaderboards/{window}_{tier}_{geoKey}
public struct FirestoreCommunityLeaderboardDoc: Codable, Sendable, Equatable {
    public var window: String
    public var tier: String
    public var geoKey: String
    public var entries: [FirestoreLeaderboardEntry]
    public var percentiles: FirestorePercentileBands
    public var cohortSize: Int
    public var belowThreshold: Bool
    public var kThreshold: Int
    public var updatedAt: String
    public var schemaVersion: Int
}

public enum FirestoreModelPurposeCategory: String, Codable, Sendable, CaseIterable {
    case ui
    case backend
    case logic
    case writing
    case research
    case debugging
    case orchestration
    case other
}

/// Firestore: users/{uid}/looking_glass_traces/{id}
public struct FirestoreLookingGlassTraceDoc: Codable, Sendable, Equatable {
    public var sessionId: String
    public var model: String
    public var provider: String
    public var purpose: String
    public var corrected: Bool
    public var inferredPurpose: String?
    public var totalTokens: Int64
    public var costUSD: Double
    public var signals: [String]?
    public var recordedAt: String
    public var schemaVersion: Int
}

/// Firestore: users/{uid}/looking_glass_exports/{id}
public struct FirestoreLookingGlassExportDoc: Codable, Sendable, Equatable {
    public var storagePath: String
    public var format: String
    public var traceCount: Int
    public var sizeBytes: Int64
    public var createdAt: String
    public var schemaVersion: Int
}
