// AUTO-GENERATED by tools/schema-sync/emit/generate.mjs — do not edit.
// Domain: entitlements

import Foundation

public struct FirestoreEscrowDeviceDoc: Codable, Sendable, Equatable {
    public var deviceId: String
    public var trustState: String
    public var registeredAt: String
    public var approvedAt: String?
}