// AUTO-GENERATED by tools/schema-sync/emit/generate.mjs — do not edit.
// Domain: hermes-gateway

import Foundation

public struct FirestoreHermesGatewayModelOptionDoc: Codable, Sendable, Equatable {
    public var providerId: String
    public var providerName: String
    public var modelId: String
    public var displayName: String
}

public struct FirestoreGatewayRelayEnvelopeDoc: Codable, Sendable, Equatable {
    public var payloadCiphertext: String
    public var wrappedKey: String
    public var relayEncryption: String
    public var relayKeyVersion: Int
    public var enc: String?
    public var senderPublicKey: String?
}

public struct FirestoreGatewayRatchetHeaderDoc: Codable, Sendable, Equatable {
    public var version: Int
    public var algorithm: String
    public var sessionID: String
    public var senderDeviceID: String
    public var receiverDeviceID: String
    public var ratchetPublicKeyBase64: String
    public var previousChainLength: Int
    public var messageNumber: Int
    public var epoch: Int
}

public struct FirestoreGatewayRatchetEnvelopeDoc: Codable, Sendable, Equatable {
    public var header: FirestoreGatewayRatchetHeaderDoc
    public var ciphertextBase64: String
}

public struct FirestoreGatewaySignalCiphertextLayerDoc: Codable, Sendable, Equatable {
    public var payloadCiphertextB64: String
    public var payloadAADLabel: String
    public var schemaVersion: Int

    public init(payloadCiphertextB64: String, payloadAADLabel: String, schemaVersion: Int) {
        self.payloadCiphertextB64 = payloadCiphertextB64
        self.payloadAADLabel = payloadAADLabel
        self.schemaVersion = schemaVersion
    }
}

public struct FirestoreGatewaySignalBindingDoc: Codable, Sendable, Equatable {
    public var uid: String
    public var scope: String
    public var clientId: String?
    public var collection: String?
    public var docId: String?
    public var field: String?
    public var slotId: String?
    public var mode: String
    public var formatVersion: Int

    public init(uid: String, scope: String, clientId: String? = nil, collection: String? = nil, docId: String? = nil, field: String? = nil, slotId: String? = nil, mode: String, formatVersion: Int) {
        self.uid = uid
        self.scope = scope
        self.clientId = clientId
        self.collection = collection
        self.docId = docId
        self.field = field
        self.slotId = slotId
        self.mode = mode
        self.formatVersion = formatVersion
    }
}

public struct FirestoreGatewaySignalAtRestWrapDoc: Codable, Sendable, Equatable {
    public var recipientKind: String
    public var recipientIdentityKeyId: String
    public var recipientIdentityKeyB64: String
    public var sealedContentKeyB64: String

    public init(recipientKind: String, recipientIdentityKeyId: String, recipientIdentityKeyB64: String, sealedContentKeyB64: String) {
        self.recipientKind = recipientKind
        self.recipientIdentityKeyId = recipientIdentityKeyId
        self.recipientIdentityKeyB64 = recipientIdentityKeyB64
        self.sealedContentKeyB64 = sealedContentKeyB64
    }
}

public struct FirestoreGatewaySignalKeyDeliveryDoc: Codable, Sendable, Equatable {
    public var scheme: String
    public var signalMessageType: Int?
    public var signalMessageB64: String?
    public var senderIdentityKeyId: String?
    public var ratchetEpochHint: Int?
    public var wraps: [FirestoreGatewaySignalAtRestWrapDoc]?
    public var contentKeyLength: Int?

    public init(scheme: String, signalMessageType: Int? = nil, signalMessageB64: String? = nil, senderIdentityKeyId: String? = nil, ratchetEpochHint: Int? = nil, wraps: [FirestoreGatewaySignalAtRestWrapDoc]? = nil, contentKeyLength: Int? = nil) {
        self.scheme = scheme
        self.signalMessageType = signalMessageType
        self.signalMessageB64 = signalMessageB64
        self.senderIdentityKeyId = senderIdentityKeyId
        self.ratchetEpochHint = ratchetEpochHint
        self.wraps = wraps
        self.contentKeyLength = contentKeyLength
    }
}

public struct FirestoreGatewaySignalAtRestSenderAuthDoc: Codable, Sendable, Equatable {
    public var senderIdentityKeyId: String
    public var senderIdentityKeyB64: String
    public var signatureB64: String
    public var signatureVersion: Int

    public init(senderIdentityKeyId: String, senderIdentityKeyB64: String, signatureB64: String, signatureVersion: Int) {
        self.senderIdentityKeyId = senderIdentityKeyId
        self.senderIdentityKeyB64 = senderIdentityKeyB64
        self.signatureB64 = signatureB64
        self.signatureVersion = signatureVersion
    }
}

public struct FirestoreGatewaySignalEnvelopeDoc: Codable, Sendable, Equatable {
    public var signalEnvelopeFormatVersion: Int
    public var mode: String
    public var relayKeyVersion: Int?
    public var relayEncryption: String
    public var ciphertextLayer: FirestoreGatewaySignalCiphertextLayerDoc
    public var keyDelivery: FirestoreGatewaySignalKeyDeliveryDoc
    public var binding: FirestoreGatewaySignalBindingDoc
    public var senderAuth: FirestoreGatewaySignalAtRestSenderAuthDoc?

    public init(signalEnvelopeFormatVersion: Int, mode: String, relayKeyVersion: Int? = nil, relayEncryption: String, ciphertextLayer: FirestoreGatewaySignalCiphertextLayerDoc, keyDelivery: FirestoreGatewaySignalKeyDeliveryDoc, binding: FirestoreGatewaySignalBindingDoc, senderAuth: FirestoreGatewaySignalAtRestSenderAuthDoc? = nil) {
        self.signalEnvelopeFormatVersion = signalEnvelopeFormatVersion
        self.mode = mode
        self.relayKeyVersion = relayKeyVersion
        self.relayEncryption = relayEncryption
        self.ciphertextLayer = ciphertextLayer
        self.keyDelivery = keyDelivery
        self.binding = binding
        self.senderAuth = senderAuth
    }
}

public struct FirestoreHermesGatewaySignalPrekeyBundleDoc: Codable, Sendable, Equatable {
    public var version: Int
    public var bundleId: String
    public var identityKeyId: String
    public var identityKeyB64: String
    public var registrationId: Int
    public var deviceId: Int
    public var signedPreKeyId: Int
    public var signedPreKeyPublicB64: String
    public var signedPreKeySignatureB64: String
    public var oneTimePreKeyId: Int
    public var oneTimePreKeyPublicB64: String
    public var kyberPreKeyId: Int
    public var kyberPreKeyPublicB64: String
    public var kyberPreKeySignatureB64: String
    public var generatedAt: String

    public init(version: Int, bundleId: String, identityKeyId: String, identityKeyB64: String, registrationId: Int, deviceId: Int, signedPreKeyId: Int, signedPreKeyPublicB64: String, signedPreKeySignatureB64: String, oneTimePreKeyId: Int, oneTimePreKeyPublicB64: String, kyberPreKeyId: Int, kyberPreKeyPublicB64: String, kyberPreKeySignatureB64: String, generatedAt: String) {
        self.version = version
        self.bundleId = bundleId
        self.identityKeyId = identityKeyId
        self.identityKeyB64 = identityKeyB64
        self.registrationId = registrationId
        self.deviceId = deviceId
        self.signedPreKeyId = signedPreKeyId
        self.signedPreKeyPublicB64 = signedPreKeyPublicB64
        self.signedPreKeySignatureB64 = signedPreKeySignatureB64
        self.oneTimePreKeyId = oneTimePreKeyId
        self.oneTimePreKeyPublicB64 = oneTimePreKeyPublicB64
        self.kyberPreKeyId = kyberPreKeyId
        self.kyberPreKeyPublicB64 = kyberPreKeyPublicB64
        self.kyberPreKeySignatureB64 = kyberPreKeySignatureB64
        self.generatedAt = generatedAt
    }
}

public struct FirestoreHermesGatewayClientDoc: Codable, Sendable, Equatable {
    public var id: String
    public var uid: String
    public var displayName: String
    public var status: String
    public var tokenHash: String
    public var tokenPreview: String
    public var agentClientSigningPublicKeyBase64: String?
    public var agentClientSigningKeyId: String?
    public var popRequired: Bool?
    public var popVersion: Int?
    public var scopes: [String]
    public var homeDestinationId: String
    public var expiresAt: String?
    public var rotatedAt: String?
    public var lastSeenAt: String?
    public var agentRelayPublicKey: String?
    public var agentRelayKeyVersion: Int?
    public var agentRelayEncryption: String?
    public var agentSupportsRelayEnvelopeVersions: [Int]?
    public var agentPreferredRelayEnvelopeVersion: Int?
    public var agentSupportsHpkeV3: Bool?
    public var agentSupportsSignalEnvelope: Bool?
    public var agentSignalPrekeyBundle: FirestoreHermesGatewaySignalPrekeyBundleDoc?
    public var agentPlatform: String?
    public var agentAppBuild: String?
    public var phoneRelayPublicKey: String?
    public var phoneRelayKeyVersion: Int?
    public var phoneRelayEncryption: String?
    public var phoneSupportsRelayEnvelopeVersions: [Int]?
    public var phonePreferredRelayEnvelopeVersion: Int?
    public var phoneSupportsHpkeV3: Bool?
    public var phoneSupportsSignalEnvelope: Bool?
    public var phoneSignalPrekeyBundle: FirestoreHermesGatewaySignalPrekeyBundleDoc?
    public var phonePlatform: String?
    public var phoneAppBuild: String?
    public var agentRatchetIdentityPublicKey: String?
    public var agentRatchetSigningPublicKey: String?
    public var agentRatchetSignedPreKeyPublicKey: String?
    public var agentRatchetSignedPreKeyId: String?
    public var agentRatchetSignedPreKeySignature: String?
    public var agentSupportsRatchetV1: Bool?
    public var phoneRatchetIdentityPublicKey: String?
    public var phoneRatchetSigningPublicKey: String?
    public var phoneRatchetSignedPreKeyPublicKey: String?
    public var phoneRatchetSignedPreKeyId: String?
    public var phoneRatchetSignedPreKeySignature: String?
    public var phoneSupportsRatchetV1: Bool?
    public var supportsRatchetV1: Bool?
    public var supportsRelayEnvelopeVersions: [Int]?
    public var preferredRelayEnvelopeVersion: Int?
    public var supportsHpkeV3: Bool?
    public var supportsSignalEnvelope: Bool?
    public var relayCapable: Bool?
    public var runtimeModelId: String?
    public var runtimeProviderId: String?
    public var runtimeModelOptions: [FirestoreHermesGatewayModelOptionDoc]?
    public var runtimeUpdatedAt: String?
    public var agentVersion: String?
    public var pendingModelId: String?
    public var pendingModelRequestedAt: String?
    public var oversightMode: String?
    public var revokedAt: String?
    public var createdAt: String
    public var updatedAt: String
    public var schemaVersion: Int
}

public struct FirestoreHermesGatewayApprovalDoc: Codable, Sendable, Equatable {
    public var id: String
    public var clientId: String
    public var destinationId: String
    public var actionId: String
    public var toolName: String?
    public var summary: String
    public var status: String
    public var requestedAt: String
    public var expiresAt: String
    public var respondedAt: String?
    public var approvedByDeviceId: String?
    public var schemaVersion: Int
}

public struct FirestoreHermesGatewayDestinationDoc: Codable, Sendable, Equatable {
    public var id: String
    public var displayName: String
    public var kind: String
    public var status: String
    public var isDefault: Bool
    public var createdAt: String
    public var updatedAt: String
    public var schemaVersion: Int
}

public struct FirestoreHermesGatewayEventDoc: Codable, Sendable, Equatable {
    public var id: String
    public var sequence: Int
    public var kind: String
    public var destinationId: String
    public var targetClientId: String?
    public var threadId: String?
    public var senderId: String
    public var senderDisplayName: String?
    public var text: String?
    public var modelId: String?
    public var attachmentIds: [String]
    public var relayEnvelope: FirestoreGatewayRelayEnvelopeDoc?
    public var ratchetEnvelope: FirestoreGatewayRatchetEnvelopeDoc?
    public var signalEnvelope: FirestoreGatewaySignalEnvelopeDoc?
    public var createdAt: String
    public var schemaVersion: Int
}

public struct FirestoreHermesGatewayMessageDoc: Codable, Sendable, Equatable {
    public var id: String
    public var clientId: String
    public var kind: String
    public var destinationId: String
    public var threadId: String?
    public var replyToEventId: String?
    public var text: String?
    public var attachmentIds: [String]
    public var relayEnvelope: FirestoreGatewayRelayEnvelopeDoc?
    public var ratchetEnvelope: FirestoreGatewayRatchetEnvelopeDoc?
    public var signalEnvelope: FirestoreGatewaySignalEnvelopeDoc?
    public var createdAt: String
    public var schemaVersion: Int
}

public struct FirestoreHermesGatewayAttachmentManifestDoc: Codable, Sendable, Equatable {
    public var id: String
    public var clientId: String
    public var destinationId: String?
    public var fileName: String?
    public var contentType: String
    public var byteCount: Int
    public var storagePath: String
    public var status: String
    public var relayEnvelope: FirestoreGatewayRelayEnvelopeDoc?
    public var ratchetEnvelope: FirestoreGatewayRatchetEnvelopeDoc?
    public var signalEnvelope: FirestoreGatewaySignalEnvelopeDoc?
    public var createdAt: String
    public var updatedAt: String?
    public var expiresAt: String
    public var uploadedAt: String?
    public var finalizedAt: String?
    public var sha256: String?
    public var storageGeneration: String?
    public var schemaVersion: Int
}
