// AUTO-GENERATED by tools/schema-sync/emit/generate.mjs — do not edit.
// Domain: hermes-relay

import Foundation

public struct FirestoreHermesRelayRequestDoc: Codable, Sendable, Equatable {
    public var operation: String
    public var status: String
    public var sessionId: String?
    public var createdAt: String
    public var updatedAt: String?
}

public struct FirestoreHermesRelayChunkDoc: Codable, Sendable, Equatable {
    public var requestId: String
    public var chunkIndex: Int
    public var payloadBase64: String
    public var createdAt: String
}