// AUTO-GENERATED by tools/schema-sync/emit/generate.mjs — do not edit.
// Domain: hosted-quota

import Foundation

public struct FirestoreEntitlementBindingDoc: Codable, Sendable, Equatable {
    public var appAccountToken: String
    public var uid: String
    public var createdAt: String
}