// AUTO-GENERATED by tools/schema-sync/emit/generate.mjs — do not edit.
// Domain: insights

import Foundation

public struct FirestoreInsightCanvasDoc: Codable, Sendable, Equatable {
    public var id: String
    public var title: String
    public var theme: String
    public var origin: String
    public var updatedAt: String
}
