// AUTO-GENERATED by tools/schema-sync/emit/generate.mjs — do not edit.
// Domain: missions

import Foundation

public struct FirestoreMissionDispatchDoc: Codable, Sendable, Equatable {
    public var missionId: String
    public var status: String
    public var createdAt: String
    public var updatedAt: String?
    public var payloadSummary: String?
}
