// AUTO-GENERATED by tools/schema-sync/emit/generate.mjs — do not edit.
// Domain: war-room

import Foundation

/// Static hardware identity for a body. Unknown fields stay absent and render em-dash.
public struct FirestoreHermesBodyHardware: Codable, Sendable, Equatable {
    public var hardwareModel: String?
    public var chipBrand: String?
    public var coresPerformance: Int?
    public var coresEfficiency: Int?
    public var memBytes: Int64?
    public var gpu: String?
}

public struct FirestoreHermesBodyHermesState: Codable, Sendable, Equatable {
    public var installed: Bool
    public var gatewayReachable: Bool
    public var version: String?
    public var gatewayClientId: String?
    public var botCount: Int?
    public var botsUpdatedAt: String?
}

public struct FirestoreHermesBodyEndpoints: Codable, Sendable, Equatable {
    public var irohNodeId: String?
    public var pairingConnectionId: String
}

public struct FirestoreHermesBodyPresence: Codable, Sendable, Equatable {
    public var state: String
    public var lastHeartbeatAt: String
    public var wireReachable: Bool
}

/// Firestore: users/{uid}/hermes_bodies/{bodyId}
/// bodyId == relay-host-<installationUUID>; written only by the owning Mac.
public struct FirestoreHermesBodyDoc: Codable, Sendable, Equatable {
    public var id: String
    public var deviceID: String
    public var displayName: String
    public var machineName: String
    public var platform: String
    public var hardware: FirestoreHermesBodyHardware
    public var hermes: FirestoreHermesBodyHermesState
    public var endpoints: FirestoreHermesBodyEndpoints
    public var presence: FirestoreHermesBodyPresence
    public var capabilities: [String]
    public var schemaVersion: Int
    public var createdAt: String
    public var updatedAt: String
}

/// STARTED BY attribution stamped wherever work begins (Command Board column).
public struct FirestoreOriginatorRef: Codable, Sendable, Equatable {
    public var kind: String
    public var label: String
    public var bodyID: String?
    public var decisionID: String?
    public var missionID: String?
    public var missionGroupID: String?
    public var botName: String?
    public var confidence: String
}

/// Firestore: users/{uid}/war_wire_grants/{pairId}
/// pairId == the two bodyIds sorted lexicographically and joined with "__".
/// Revocable from either machine; unverifiable state reads as revoked.
public struct FirestoreWarWireGrantDoc: Codable, Sendable, Equatable {
    public var id: String
    public var bodyIdA: String
    public var bodyIdB: String
    public var state: String
    public var grantedByDeviceID: String
    public var grantedAt: String
    public var revokedByDeviceID: String?
    public var revokedAt: String?
    public var schemaVersion: Int
    public var createdAt: String
    public var updatedAt: String
}
