// AUTO-GENERATED by tools/schema-sync/emit/generate.mjs — do not edit.
// Domain: war-room

import Foundation

/// Hardware a body reports about itself. Absent means "not readable here", never zero.
public struct FirestoreHermesBodyHardwareDoc: Codable, Sendable, Equatable {
    public var hardwareModel: String?
    public var chip: String?
    public var memoryBytes: Int64?
    public var performanceCoreCount: Int?
    public var efficiencyCoreCount: Int?
    public var osVersion: String?
}

/// Liveness of a body, derived from its own heartbeat.
public struct FirestoreHermesBodyPresenceDoc: Codable, Sendable, Equatable {
    public var state: String
    public var lastHeartbeatAt: String
    public var heartbeatIntervalSeconds: Int
}

/// Firestore: users/{uid}/hermes_bodies/{bodyId}
/// `bodyId` is the existing Hermes relay connection id — joining mints no new identity.
public struct FirestoreHermesBodyDoc: Codable, Sendable, Equatable {
    public var bodyId: String
    public var installationId: String
    public var displayName: String
    public var platform: String
    public var hardware: FirestoreHermesBodyHardwareDoc
    public var capabilities: [String]
    public var presence: FirestoreHermesBodyPresenceDoc
    public var joinedAt: String
    public var updatedAt: String
    public var schemaVersion: Int
}

/// Who caused a write. Embedded in usage, mission, and run documents.
/// Only a write the daemon itself spawned may claim `exact` confidence.
public struct FirestoreOriginatorDoc: Codable, Sendable, Equatable {
    public var bodyId: String
    public var kind: String
    public var surface: String
    public var confidence: String
    public var provenanceDetail: String?
    public var label: String?
    public var missionId: String?
    public var runId: String?
    public var recordedAt: String
    public var schemaVersion: Int
}
