#!/usr/bin/env bash
# Regenerate the committed C# binding for the burnbar-remote-ffi cdylib.
#
# The binding is generated by uniffi-bindgen-cs from the *compiled* cdylib
# (library mode), exactly like the Swift/Kotlin lanes generate from the same
# crate. Re-run this after changing the `#[uniffi::export]` surface in
# crates/burnbar-remote/burnbar-remote-ffi/src/lib.rs, then commit the diff under
# BurnBarRemote.Ffi/generated/. See docs/windows-port/decisions/0001-csharp-binding-path.md.
#
# Toolchain pin: uniffi-bindgen-cs must match the crate's uniffi version (0.28.3).
#   cargo install uniffi-bindgen-cs \
#     --git https://github.com/NordSecurity/uniffi-bindgen-cs \
#     --tag v0.9.2+v0.28.3
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
crate_dir="$(cd "${here}/../.." && pwd)"          # crates/burnbar-remote
ffi_dir="${crate_dir}/burnbar-remote-ffi"
out_dir="${here}/BurnBarRemote.Ffi/generated"

profile="${BURNBAR_REMOTE_BUILD_PROFILE:-debug}"
build_flag=""
[[ "${profile}" == "release" ]] && build_flag="--release"

# Native library name per host OS.
case "$(uname -s)" in
  Darwin) libname="libburnbar_remote.dylib" ;;
  Linux)  libname="libburnbar_remote.so" ;;
  *)      libname="burnbar_remote.dll" ;;
esac

echo "==> Building the burnbar-remote-ffi cdylib (${profile})"
( cd "${crate_dir}" && cargo build -p burnbar-remote-ffi ${build_flag} )

target_dir="$(
  cd "${crate_dir}" && cargo metadata --no-deps --format-version 1 \
    | python3 -c 'import json, sys; print(json.load(sys.stdin)["target_directory"])'
)"
lib_path="${target_dir}/${profile}/${libname}"
[[ -f "${lib_path}" ]] || { echo "cdylib not found: ${lib_path}" >&2; exit 1; }

echo "==> Generating C# bindings from ${lib_path}"
mkdir -p "${out_dir}"
(
  cd "${crate_dir}"
  uniffi-bindgen-cs \
    --library "${lib_path}" \
    --config "${ffi_dir}/uniffi.toml" \
    --out-dir "${out_dir}"
)
perl -0pi -e 's/[ \t]+$//mg' "${out_dir}/burnbar_remote.cs"

echo "==> Done. Review + commit ${out_dir}/burnbar_remote.cs"
