import Foundation
import LibSignalClient
import OpenBurnBarSignalCore
import XCTest

/// Phase 2.5 G1 — reverse-direction cross-language interop KAT: decrypts PreKey messages produced
/// by the ANDROID `AndroidSignalProtocolStore` (Alice) using the Swift `OBBSignalProtocolStore`
/// (Bob), reconstructed from the same key material. The mirror of the existing
/// `AndroidSignalInteropKatTest.decryptsSwiftAliceMessage` (Swift-Alice -> Android-Bob), in the
/// OTHER direction, proving the Android and Swift session stores interoperate on the real
/// official-libsignal wire format both ways.
///
/// The committed fixture is generated by the Android `AndroidSignalInteropFixtureGen` (run on
/// demand) and lives in `Fixtures/android-alice-to-swift-bob.json` (byte-identical to the copies
/// under `tests/fixtures/signal-interop/` and `android/.../resources/signal-interop/`).
///
/// Two messages are carried: both are PreKey-type (libsignal keeps wrapping Alice's messages as
/// PreKeySignalMessage until she gets a reply), so the second exercises the symmetric message-key
/// chain ratchet across the wire. The bidirectional DH-ratchet whisper reply is proven in-process
/// by `OBBSignalSessionOverIrohTests` (a from-scratch peer cannot decrypt a DH-ratchet whisper).
final class OBBSignalInteropKatTests: XCTestCase {
    private struct InteropVector: Decodable {
        let schema: String
        let direction: String
        let aliceAddressName: String
        let bobAddressName: String
        let deviceId: Int
        let bobRegistrationId: Int
        let bobIdentityKeyPairB64: String
        let bobPreKeyId: Int
        let bobPreKeyRecordB64: String
        let bobSignedPreKeyId: Int
        let bobSignedPreKeyRecordB64: String
        let bobKyberPreKeyId: Int
        let bobKyberPreKeyRecordB64: String
        let ciphertextType: Int
        let ciphertextB64: String
        let expectedPlaintext: String
        let secondCiphertextType: Int
        let secondCiphertextB64: String
        let secondExpectedPlaintext: String
    }

    private func loadVector() throws -> InteropVector {
        let url = try XCTUnwrap(
            Bundle.module.url(forResource: "android-alice-to-swift-bob", withExtension: "json"),
            "reverse interop fixture missing — regenerate with the Android AndroidSignalInteropFixtureGen"
        )
        return try JSONDecoder().decode(InteropVector.self, from: Data(contentsOf: url))
    }

    private func bytes(_ b64: String) throws -> Data {
        try XCTUnwrap(Data(base64Encoded: b64), "invalid base64 in interop fixture")
    }

    func testDecryptsAndroidAlicePreKeyAndChainAdvancedMessage() throws {
        let vector = try loadVector()
        XCTAssertEqual(vector.schema, "obb-signal-interop-v1")
        XCTAssertEqual(vector.direction, "android-alice-to-swift-bob")
        XCTAssertEqual(vector.ciphertextType, Int(CiphertextMessage.MessageType.preKey.rawValue))

        let ctx = NullContext()

        // Reconstruct Bob's Swift store from the Android-produced key material.
        let bobIdentity = try IdentityKeyPair(bytes: bytes(vector.bobIdentityKeyPairB64))
        let bobDir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: bobDir) }
        let bob = try OBBSignalProtocolStore.testingTOFU(
            identityKeypair: bobIdentity,
            registrationId: UInt32(vector.bobRegistrationId),
            keychainService: "com.openburnbar.signal.interop.kat.bob.\(UUID().uuidString)",
            sessionDir: bobDir
        )
        try bob.storePreKey(try PreKeyRecord(bytes: bytes(vector.bobPreKeyRecordB64)), id: UInt32(vector.bobPreKeyId), context: ctx)
        try bob.storeSignedPreKey(try SignedPreKeyRecord(bytes: bytes(vector.bobSignedPreKeyRecordB64)), id: UInt32(vector.bobSignedPreKeyId), context: ctx)
        try bob.storeKyberPreKey(try KyberPreKeyRecord(bytes: bytes(vector.bobKyberPreKeyRecordB64)), id: UInt32(vector.bobKyberPreKeyId), context: ctx)

        let aliceAddress = try ProtocolAddress(name: vector.aliceAddressName, deviceId: UInt32(vector.deviceId))
        let bobAddress = try ProtocolAddress(name: vector.bobAddressName, deviceId: UInt32(vector.deviceId))

        // Leg 1 — Android-Alice's PreKey message establishes Bob's session and decrypts.
        let firstMessage = try PreKeySignalMessage(bytes: bytes(vector.ciphertextB64))
        let firstPlaintext = try signalDecryptPreKey(
            message: firstMessage, from: aliceAddress, localAddress: bobAddress,
            sessionStore: bob, identityStore: bob, preKeyStore: bob,
            signedPreKeyStore: bob, kyberPreKeyStore: bob, context: ctx
        )
        XCTAssertEqual(String(decoding: firstPlaintext, as: UTF8.self), vector.expectedPlaintext)

        // Leg 2 — the chain-advanced second message (also PreKey-type) decrypts on the established
        // session, proving the symmetric message-key chain ratchet survives cross-language.
        XCTAssertEqual(vector.secondCiphertextType, Int(CiphertextMessage.MessageType.preKey.rawValue))
        let secondMessage = try PreKeySignalMessage(bytes: bytes(vector.secondCiphertextB64))
        let secondPlaintext = try signalDecryptPreKey(
            message: secondMessage, from: aliceAddress, localAddress: bobAddress,
            sessionStore: bob, identityStore: bob, preKeyStore: bob,
            signedPreKeyStore: bob, kyberPreKeyStore: bob, context: ctx
        )
        XCTAssertEqual(String(decoding: secondPlaintext, as: UTF8.self), vector.secondExpectedPlaintext)
    }
}
