"""
OpenBurnBar local memory engine.

A self-contained, local-first memory layer for the local MCP: extraction,
secret/PII gating with a redact/reject/retain policy, ADD/UPDATE/NONE/DELETE
conflict resolution with per-memory history, hybrid BM25 + vector recall with
a deterministic salience rerank, entity/relation extraction, encrypted-at-rest
bodies, an encrypted vault for the experimental "retain secrets" mode, and a
label-only hash-chained audit log.

Design: docs/superpowers/2026-09-02-memory-mcp-v2-design.md

The engine owns its own SQLite file. It never touches the app's SQLCipher
database. Bodies (and history bodies) are AES-256-GCM encrypted with a key the
engine owns; vectors and metadata are plaintext. There is deliberately no FTS
table on disk: BM25 runs in-process over the decrypted active bodies of one
project, so the only plaintext derivative on disk is the vector.

This package is a facade over focused modules (`constants`, `_util`, `text`,
`crypto`, `embeddings`, `gate`, `extract`, `store`, `filters`, `engine`, and
the three `MemoryEngine` mixins `_write`, `_read`, `_admin`). `import
memory_engine as me` reaches every name the engine exports, exactly as it did
when this was one file.

Mutable module state is deliberately *not* re-exported here: a facade alias is
bound once at import and stops tracking its module, so patching the alias would
silently do nothing. Read and patch `memory_engine.gate.GATE_CORPUS_AVAILABLE`,
`memory_engine.embeddings.OllamaEmbeddingProvider`, and
`memory_engine.store.SCHEMA_MIGRATIONS` through their own modules;
`tests/test_memory_engine_layout.py` enforces the rule for the whole package,
this file included.
"""

from __future__ import annotations

from . import constants, crypto, embeddings, engine, extract, filters, gate, store, text
from ._util import (
    _json_dumps,
    normalize_kind,
    normalize_kind_strict,
    normalize_scope,
    normalize_tags,
    now_iso,
    raw_tags,
    sha256_hex,
)
from .constants import (
    ALWAYS_REDACT_PII_LABELS,
    CONFLICT_MIN_SIM,
    CONFLICT_OBJECT_MAX_SIM,
    CUE_PATTERNS,
    DEDUP_COSINE,
    DEDUP_JACCARD,
    DEFAULT_EMBEDDING_MODEL,
    DEFAULT_MAX_FACTS,
    DEFAULT_OLLAMA_BASE_URL,
    DISCOURSE_MARKER_RE,
    EMBEDDING_MODEL_ENV,
    EMBEDDING_PROVIDER_ENV,
    ENGINE_ACTOR,
    ENGINE_SCHEMA_VERSION,
    EXTRACT_PROMPT,
    EXTRACT_PROMPT_VERSION,
    EXTRACTOR_ENV,
    FILTER_OPERATORS,
    HALF_LIFE_DAYS_LONG,
    HALF_LIFE_DAYS_SHORT,
    HANDLE_RE,
    IDENTIFIER_RE,
    INGEST_DECISION_KEYS,
    INJECTION_PATTERNS,
    ISSUE_RE,
    KIND_ALIASES,
    KIND_WEIGHTS,
    KINDS,
    MAX_BODY_CHARS,
    MAX_MEMORIES_PER_PROJECT_SOFT,
    MEMORY_DB_PATH_ENV,
    MEMORY_KEY_ENV,
    MEMORY_SCOPES,
    NEGATION_RE,
    NOISE_PATTERNS,
    OLLAMA_BASE_URL_ENV,
    PATH_RE,
    PERSONAL_KINDS,
    PII_POLICIES,
    PII_POLICY_ENV,
    PROPER_NOUN_RE,
    RELATION_PREDICATES,
    REVIEW_STATUSES,
    RRF_K,
    RRF_LEXICAL_WEIGHT,
    RRF_SEMANTIC_WEIGHT,
    SAME_CLAIM_MIN_OVERLAP,
    SECRET_POLICIES,
    SECRET_POLICY_ENV,
    SENSITIVITIES,
    SENTENCE_SPLIT_RE,
    SHORT_HALF_LIFE_KINDS,
    STOPWORDS,
    SWITCH_RE,
    VERSION_RE,
)
from .crypto import KeyRing, secure_store_files, store_lock_path, store_sidecar_paths
from .embeddings import (
    EmbeddingProvider,
    FakeEmbeddingProvider,
    NullEmbeddingProvider,
    OllamaEmbeddingProvider,
    decode_vector,
    embedding_provider,
    encode_vector,
    reset_provider_cache_for_tests,
)
from .engine import ActiveMemory, EngineConfig, MemoryEngine
from .extract import (
    PACK_TOKEN_BUDGET_FLOOR,
    ExtractorFn,
    Fact,
    claude_cli_extract,
    extract_entities,
    extract_relations,
    gate_transcript,
    heuristic_extract,
    ollama_extract,
    parse_llm_facts,
    render_transcript,
    resolve_extractor,
)
from .filters import match_filters
from .gate import (
    AuxGate,
    GateDecision,
    GateFindings,
    GatePattern,
    apply_gate,
    auxiliary_injection_labels,
    gate_aux_fields,
    injection_labels,
    scan_text,
)
from .store import (
    STORE_OPEN_ATTEMPTS,
    SchemaTooNew,
    audit_event,
    default_db_path,
    ensure_schema,
    open_store,
    project_payload,
    resolve_project,
    verify_audit_chain,
)
from .text import BM25, _estimate_tokens, _stem, tokenize

__all__ = [
    "ALWAYS_REDACT_PII_LABELS",
    "BM25",
    "CONFLICT_MIN_SIM",
    "CONFLICT_OBJECT_MAX_SIM",
    "CUE_PATTERNS",
    "DEDUP_COSINE",
    "DEDUP_JACCARD",
    "DEFAULT_EMBEDDING_MODEL",
    "DEFAULT_MAX_FACTS",
    "DEFAULT_OLLAMA_BASE_URL",
    "DISCOURSE_MARKER_RE",
    "EMBEDDING_MODEL_ENV",
    "EMBEDDING_PROVIDER_ENV",
    "ENGINE_ACTOR",
    "ENGINE_SCHEMA_VERSION",
    "EXTRACTOR_ENV",
    "EXTRACT_PROMPT",
    "EXTRACT_PROMPT_VERSION",
    "FILTER_OPERATORS",
    "HALF_LIFE_DAYS_LONG",
    "HALF_LIFE_DAYS_SHORT",
    "HANDLE_RE",
    "IDENTIFIER_RE",
    "INGEST_DECISION_KEYS",
    "INJECTION_PATTERNS",
    "ISSUE_RE",
    "KINDS",
    "KIND_ALIASES",
    "KIND_WEIGHTS",
    "MAX_BODY_CHARS",
    "MAX_MEMORIES_PER_PROJECT_SOFT",
    "MEMORY_DB_PATH_ENV",
    "MEMORY_KEY_ENV",
    "MEMORY_SCOPES",
    "NEGATION_RE",
    "NOISE_PATTERNS",
    "OLLAMA_BASE_URL_ENV",
    "PACK_TOKEN_BUDGET_FLOOR",
    "PATH_RE",
    "PERSONAL_KINDS",
    "PII_POLICIES",
    "PII_POLICY_ENV",
    "PROPER_NOUN_RE",
    "RELATION_PREDICATES",
    "REVIEW_STATUSES",
    "RRF_K",
    "RRF_LEXICAL_WEIGHT",
    "RRF_SEMANTIC_WEIGHT",
    "SAME_CLAIM_MIN_OVERLAP",
    "SECRET_POLICIES",
    "SECRET_POLICY_ENV",
    "SENSITIVITIES",
    "SENTENCE_SPLIT_RE",
    "SHORT_HALF_LIFE_KINDS",
    "STOPWORDS",
    "STORE_OPEN_ATTEMPTS",
    "SWITCH_RE",
    "VERSION_RE",
    "ActiveMemory",
    "AuxGate",
    "EmbeddingProvider",
    "EngineConfig",
    "ExtractorFn",
    "Fact",
    "FakeEmbeddingProvider",
    "GateDecision",
    "GateFindings",
    "GatePattern",
    "KeyRing",
    "MemoryEngine",
    "NullEmbeddingProvider",
    "OllamaEmbeddingProvider",
    "SchemaTooNew",
    "_estimate_tokens",
    "_json_dumps",
    "_stem",
    "apply_gate",
    "audit_event",
    "auxiliary_injection_labels",
    "claude_cli_extract",
    "constants",
    "crypto",
    "decode_vector",
    "default_db_path",
    "embedding_provider",
    "embeddings",
    "encode_vector",
    "engine",
    "ensure_schema",
    "extract",
    "extract_entities",
    "extract_relations",
    "filters",
    "gate",
    "gate_aux_fields",
    "gate_transcript",
    "heuristic_extract",
    "injection_labels",
    "match_filters",
    "normalize_kind",
    "normalize_kind_strict",
    "normalize_scope",
    "normalize_tags",
    "now_iso",
    "ollama_extract",
    "open_store",
    "parse_llm_facts",
    "project_payload",
    "raw_tags",
    "render_transcript",
    "reset_provider_cache_for_tests",
    "resolve_extractor",
    "resolve_project",
    "scan_text",
    "secure_store_files",
    "sha256_hex",
    "store",
    "store_lock_path",
    "store_sidecar_paths",
    "text",
    "tokenize",
    "verify_audit_chain",
]
