#!/usr/bin/env bash
#
# Install the droid-wiki -> mem0 post-commit hook.
#
# This is a raw git hook (not a pre-commit-framework hook) on purpose: the sync
# writes droid-wiki/.mem0-manifest.json, and the pre-commit framework both flags
# file-modifying hooks as "Failed" and stashes/restores unstaged files around
# hook runs — which clobbers the manifest write. A plain post-commit hook has
# none of that, and git already serializes commits so no locking is needed.
#
# Run once per clone:  bash scripts/wiki/install-hooks.sh
#
set -euo pipefail

HOOK_DIR="$(git rev-parse --git-path hooks)"
HOOK="$HOOK_DIR/post-commit"

mkdir -p "$HOOK_DIR"

cat > "$HOOK" <<'HOOK_EOF'
#!/bin/sh
# OpenBurnBar post-commit hook: Git LFS bookkeeping + droid-wiki -> mem0 sync.
# Generated by scripts/wiki/install-hooks.sh.

# Preserve Git LFS behavior.
if command -v git-lfs >/dev/null 2>&1; then
  git lfs post-commit "$@"
fi

# Mirror any wiki pages this commit changed into mem0 (verbatim). The commit is
# already made, so this never blocks it; the sync skips fast when the commit
# touched no wiki markdown and exits 0 when MEM0_BURNBAR_API_KEY or node is absent.
REPO_ROOT="$(git rev-parse --show-toplevel)"
if command -v node >/dev/null 2>&1; then
  node "$REPO_ROOT/scripts/wiki/mem0-sync.mjs" --changed-from-commit HEAD || true
fi
HOOK_EOF

chmod +x "$HOOK"
echo "Installed post-commit hook -> $HOOK"
echo "Set MEM0_BURNBAR_API_KEY in your environment to enable the mem0 sync."
