#!/usr/bin/env bash
# publish-mirror.sh — mirror plugins/openburnbar into the thin public plugin repo.
#
# The plugin tree is mirrored to the ROOT of Imagine-That-Ai/openburnbar-cursor-plugin,
# so `.cursor-plugin/plugin.json` lands at the repo root. Only the plugin tree is
# copied (README.md, LICENSE, AUTH.md, CHANGELOG.md, mcp.json, .cursor-plugin/,
# assets/, skills/, commands/, rules/, agents/, scripts/, docs/) — Swift, Xcode,
# daemon, and BurnBar monorepo files never enter the copy set. The mirror commit is
# pushed to the thin repo's default branch.
#
# The plugin root is resolved from this script's own directory (same copy-aware idea
# as validate.mjs), so the script also works from a /tmp copy of the plugin tree.
#
# Env overrides: THIN_REPO (thin repo URL), SIBLING_DIR (sibling clone path).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

THIN_REPO="${THIN_REPO:-https://github.com/Imagine-That-Ai/openburnbar-cursor-plugin}"
SIBLING_DIR="${SIBLING_DIR:-/Users/dewclaw/openburnbar-cursor-plugin}"

if [ ! -f "${PLUGIN_ROOT}/.cursor-plugin/plugin.json" ]; then
  echo "publish-mirror: error: no .cursor-plugin/plugin.json under ${PLUGIN_ROOT}" >&2
  exit 1
fi

# Fail closed: the package must be valid (AGPL, no Swift/Xcode/daemon, no
# marketplace.json, no secrets) before we publish it.
node "${PLUGIN_ROOT}/scripts/validate.mjs" >/dev/null

# The manifest repository field must name the thin repo (never the monorepo).
REPOSITORY_FIELD="$(node -e "const m = require('${PLUGIN_ROOT}/.cursor-plugin/plugin.json'); console.log(typeof m.repository === 'string' ? m.repository : ((m.repository && m.repository.url) || ''))")"
if [ "${REPOSITORY_FIELD}" != "${THIN_REPO}" ]; then
  echo "publish-mirror: error: plugin.json.repository is '${REPOSITORY_FIELD}', expected '${THIN_REPO}'" >&2
  exit 1
fi

REMOTE_DEFAULT="$(git ls-remote --symref "${THIN_REPO}" HEAD 2>/dev/null | awk '/^ref:/{print $2}' | sed 's#^refs/heads/##')"
REMOTE_DEFAULT="${REMOTE_DEFAULT:-main}"

if [ ! -d "${SIBLING_DIR}/.git" ]; then
  echo "publish-mirror: cloning ${THIN_REPO} into ${SIBLING_DIR}"
  git clone --quiet "${THIN_REPO}" "${SIBLING_DIR}"
else
  echo "publish-mirror: reusing ${SIBLING_DIR}"
  git -C "${SIBLING_DIR}" fetch --quiet origin
fi

cd "${SIBLING_DIR}"
git checkout --quiet "${REMOTE_DEFAULT}" 2>/dev/null || git checkout --quiet -b "${REMOTE_DEFAULT}" 2>/dev/null || true
BRANCH="$(git symbolic-ref --short HEAD)"

echo "publish-mirror: mirroring ${PLUGIN_ROOT} -> ${SIBLING_DIR} (${BRANCH})"
# Clear the previous mirror so the clone root exactly equals the plugin tree.
git rm -r --quiet --ignore-unmatch . 2>/dev/null || true
# Copy the plugin-tree contents (including dot dirs such as .cursor-plugin/)
# to the clone root. Nothing outside the plugin tree is ever copied.
cp -R "${PLUGIN_ROOT}/." "${SIBLING_DIR}/"
git add -A

if git diff --cached --quiet; then
  echo "publish-mirror: no changes to mirror; skipping commit"
else
  git commit --quiet -m "$(cat <<'EOF'
Mirror OpenBurnBar Cursor plugin from BurnBar plugins/openburnbar

Generated by plugins/openburnbar/scripts/publish-mirror.sh. The plugin tree
lives at this repo root (.cursor-plugin/plugin.json at root), AGPL-3.0-only,
plugin-only. See docs/local-load.md for the local-load path and docs/probe/
for hosted-MCP probe transcripts.

Co-authored-by: factory-droid[bot] <138933559+factory-droid[bot]@users.noreply.github.com>
EOF
)"
fi

git push --quiet -u origin "${BRANCH}"
echo "publish-mirror: pushed ${BRANCH} to ${THIN_REPO}"
