#!/usr/bin/env node
/**
 * Self-test for scripts/ci/verify-factory-security-review-boundary.mjs.
 */

import { execFileSync } from "node:child_process";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const GATE = join(SCRIPT_DIR, "verify-factory-security-review-boundary.mjs");
const roots = [];
process.on("exit", () =>
  roots.forEach((dir) => rmSync(dir, { recursive: true, force: true })),
);

const fixture = (strings, ...values) =>
  String.raw({ raw: strings.raw }, ...values).replaceAll("\\${", "${");

const GOOD_WORKFLOW = fixture`
name: Factory Security Review
permissions:
  contents: read
  security-events: write
on:
  workflow_dispatch:
jobs:
  deep-security-review:
    steps:
      - name: Run mission-based deep security review
        env:
          FACTORY_API_KEY: \${{ secrets.FACTORY_API_KEY }}
        run: |
          set -euo pipefail
          review_output="\${RUNNER_TEMP}/factory-security-review-output.log"
          trusted_system_path="/usr/bin:/bin:/usr/sbin:/sbin"
          npm_global_bin="$(npm prefix --global)/bin"
          droid_bin="\${npm_global_bin}/droid"
          node_bin="$(command -v node || true)"
          if [[ -z "\${droid_bin}" || ! -x "\${droid_bin}" || -z "\${node_bin}" || ! -x "\${node_bin}" ]]; then
            echo "::error::Droid CLI or Node runtime was not found after the pinned npm install"
            exit 1
          fi
          droid_dir="$(dirname "\${droid_bin}")"
          node_dir="$(dirname "\${node_bin}")"
          mission_user="factory-mission"
          if ! id -u "\${mission_user}" >/dev/null 2>&1; then
            sudo useradd --create-home --shell /usr/sbin/nologin "\${mission_user}"
          fi
          mission_root="\${RUNNER_TEMP}/factory-security-review-mission"
          mission_home="\${mission_root}/home"
          mission_tmp="\${mission_root}/tmp"
          mkdir -p "\${mission_home}" "\${mission_tmp}"
          sudo chown -R "\${mission_user}:\${mission_user}" "\${mission_root}"
          if ! {
            sudo -H -u "\${mission_user}" env -i \
              HOME="\${mission_home}" \
              PATH="\${droid_dir}:\${node_dir}:\${trusted_system_path}" \
              LANG="\${LANG:-C.UTF-8}" \
              LC_ALL="\${LC_ALL:-C.UTF-8}" \
              CI="true" \
              GITHUB_ACTIONS="true" \
              RUNNER_TEMP="\${mission_tmp}" \
              TMPDIR="\${mission_tmp}" \
              FACTORY_API_KEY="\${FACTORY_API_KEY}" \
              FACTORY_SECURITY_MODEL="\${FACTORY_SECURITY_MODEL}" \
              FACTORY_REASONING_EFFORT="\${FACTORY_REASONING_EFFORT}" \
              "\${droid_bin}" exec --mission --auto high \
              --model "\${FACTORY_SECURITY_MODEL}" \
              "/security-review across the entire repository"
          } >"\${review_output}" 2>&1; then
            echo "::error::Droid security review failed. Raw mission output was kept on the runner and was not printed to CI logs."
            rm -f "\${review_output}"
            exit 1
          fi
          rm -f "\${review_output}"
          echo "Droid security review completed; raw mission output was not printed to CI logs."
      - name: Route critical findings to private security advisory
        run: |
          set -euo pipefail
          export PATH="/usr/bin:/bin:/usr/sbin:/sbin"
          unset BASH_ENV ENV CDPATH
          gh_bin="/usr/bin/gh"
          jq_bin="/usr/bin/jq"
          curl_bin="/usr/bin/curl"
          gpg_bin="/usr/bin/gpg"
          tar_bin="/usr/bin/tar"
          for tool in gh jq curl gpg tar; do
            bin_var="\${tool}_bin"
            if [[ ! -x "\${!bin_var}" ]]; then
              echo "::error::Required routing tool \${tool} was not found at the expected system path"
              exit 1
            fi
          done
          tmp_files=()
          cleanup() {
            for f in "\${tmp_files[@]}"; do
              rm -f "\${f}"
            done
          }
          trap cleanup EXIT
          report_tmp="$(mktemp)"
          evidence_archive="\${RUNNER_TEMP}/factory-security-review-encrypted-evidence.tgz.gpg"
          evidence_retained=false
          tmp_files+=("\${report_tmp}")
          description_tmp="$(mktemp)"
          payload_tmp="$(mktemp)"
          tmp_files+=("\${description_tmp}" "\${payload_tmp}")
          find "\${HOME}/security-audits" -type f -print0 | sort -z | while IFS= read -r -d '' f; do
            rel="\${f#"\${HOME}/security-audits"/}"
            {
              echo "===== \${rel} ====="
              cat "\${f}"
              echo ""
            } >> "\${report_tmp}"
          done
          max_chars=60000
          {
            printf 'Auto-generated by the Factory Security Review workflow.\\n\\n'
            head -c "\${max_chars}" "\${report_tmp}"
          } > "\${description_tmp}"
          if [[ -n "\${SECURITY_REVIEW_EVIDENCE_KEY:-}" ]]; then
            evidence_dir="$(mktemp -d)"
            tmp_files+=("\${evidence_dir}")
            chmod 700 "\${evidence_dir}"
            cp "\${report_tmp}" "\${evidence_dir}/report.txt"
            "\${jq_bin}" -n \
              --arg run_url "\${run_url}" \
              --arg repository "\${GITHUB_REPOSITORY}" \
              --arg run_id "\${GITHUB_RUN_ID}" \
              --arg created_at "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
              "{repository: \$repository, run_id: \$run_id, run_url: \$run_url, created_at: \$created_at}" > "\${evidence_dir}/metadata.json"
            (
              cd "\${evidence_dir}"
              "\${tar_bin}" -czf - report.txt metadata.json
            ) | "\${gpg_bin}" --batch --yes --pinentry-mode loopback \
              --symmetric --cipher-algo AES256 \
              --s2k-mode 3 --s2k-digest-algo SHA512 --s2k-count 65011712 \
              --passphrase-fd 3 \
              --output "\${evidence_archive}" \
              3<<<"\${SECURITY_REVIEW_EVIDENCE_KEY}"
            chmod 600 "\${evidence_archive}"
            evidence_retained=true
          fi
          "\${jq_bin}" -n \
            --arg summary "Weekly security review" \
            --rawfile description "\${description_tmp}" \
            "{summary: \$summary, description: \$description, severity: \"critical\", confidential: true, vulnerabilities: [{package: {ecosystem: \"other\", name: \"repository-codebase\"}, vulnerable_version_range: \">= 0.0.0\"}]}" > "\${payload_tmp}"
          advisory_created=false
          if [[ -z "\${GH_TOKEN:-}" ]]; then
            echo "::warning::SECURITY_ADVISORY_TOKEN is not configured; workflow will fail closed after alert routing."
          else
            if "\${gh_bin}" api --silent --method POST "/repos/\${GITHUB_REPOSITORY}/security-advisories" \
              --input "\${payload_tmp}" \
              2>/dev/null; then
              advisory_created=true
            fi
          fi
          if [[ "\${advisory_created}" == "true" ]]; then
            slack_text="Private advisory created."
          else
            slack_text="Advisory creation failed; workflow failed closed without printing the report."
          fi
          payload="$("\${jq_bin}" -nc --arg text "\${slack_text}" "{text: \$text}")"
          "\${curl_bin}" -fsS -X POST -H 'Content-Type: application/json' --data "\${payload}" "\${SLACK_SECURITY_WEBHOOK}" 2>/dev/null || true
          # Slack is only an alert, never a substitute for the confidential report body.
          if [[ "\${advisory_created}" == "false" ]]; then
            echo "::error::Critical findings detected but private advisory routing failed. Raw report intentionally not printed to CI logs."
            exit 1
          fi
        env:
          GH_TOKEN: \${{ secrets.SECURITY_ADVISORY_TOKEN }}
          SECURITY_REVIEW_EVIDENCE_KEY: \${{ secrets.SECURITY_REVIEW_EVIDENCE_KEY }}
      - name: Upload encrypted security review evidence
        if: always()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: factory-security-review-encrypted-evidence-\${{ github.run_id }}
          path: \${{ runner.temp }}/factory-security-review-encrypted-evidence.tgz.gpg
          if-no-files-found: ignore
          retention-days: 30
`;

function buildTree(workflow) {
  const root = mkdtempSync(join(tmpdir(), "factory-security-review-boundary-"));
  roots.push(root);
  const workflowDir = join(root, ".github", "workflows");
  mkdirSync(workflowDir, { recursive: true });
  writeFileSync(join(workflowDir, "factory-security-review.yml"), workflow);
  return root;
}

function runGate(root) {
  try {
    execFileSync("node", [GATE], {
      env: { ...process.env, FACTORY_SECURITY_REVIEW_BOUNDARY_ROOT: root },
      stdio: "pipe",
    });
    return 0;
  } catch (error) {
    return error.status ?? 1;
  }
}

let passed = 0;
let failed = 0;
function expect(label, workflow, wantExit) {
  const got = runGate(buildTree(workflow));
  if (got === wantExit) {
    console.log(`  PASS ${label} (exit ${got})`);
    passed += 1;
  } else {
    console.error(`  FAIL ${label}: expected exit ${wantExit}, got ${got}`);
    failed += 1;
  }
}

console.log("Self-test: verify-factory-security-review-boundary.mjs\n");

expect("hardened workflow passes", GOOD_WORKFLOW, 0);

expect(
  "unredirected Droid mission fails",
  GOOD_WORKFLOW.replace('          } >"${review_output}" 2>&1; then\n', "          }; then\n"),
  1,
);

expect(
  "unsanitized Droid mission environment fails",
  GOOD_WORKFLOW.replace('sudo -H -u "${mission_user}" env -i \\', "\\"),
  1,
);

expect(
  "Droid mission env file path inheritance fails",
  GOOD_WORKFLOW.replace(
    '              RUNNER_TEMP="${mission_tmp}" \\',
    '              RUNNER_TEMP="${mission_tmp}" \\\n              GITHUB_ENV="${GITHUB_ENV}" \\',
  ),
  1,
);

expect(
  "Droid mission real runner temp inheritance fails",
  GOOD_WORKFLOW.replace(
    '              RUNNER_TEMP="${mission_tmp}" \\',
    '              RUNNER_TEMP="${RUNNER_TEMP}" \\',
  ),
  1,
);

expect(
  "Droid mission missing unprivileged user fails",
  GOOD_WORKFLOW.replace('          mission_user="factory-mission"\n', ""),
  1,
);

expect(
  "Droid mission missing npm install resolution fails",
  GOOD_WORKFLOW.replace('          npm_global_bin="$(npm prefix --global)/bin"\n          droid_bin="${npm_global_bin}/droid"\n', ""),
  1,
);

expect(
  "advisory body through argv fails",
  GOOD_WORKFLOW.replace(
    '--input "${payload_tmp}"',
    '-f description="${body}"',
  ).replace(
    'description_tmp="$(mktemp)"',
    'description_tmp="$(mktemp)"\n          body="$(head -c "${max_chars}" "${report_tmp}")',
  ),
  1,
);

expect(
  "CI-log report fallback fails",
  GOOD_WORKFLOW.replace(
    "workflow failed closed without printing the report",
    "review full report in CI logs",
  ),
  1,
);

expect(
  "Slack substituted for advisory fails",
  GOOD_WORKFLOW.replace(
    'if [[ "${advisory_created}" == "false" ]]; then',
    'if [[ "${advisory_created}" == "false" && "${slack_sent}" == "false" ]]; then',
  ),
  1,
);

expect(
  "raw artifact upload fails",
  GOOD_WORKFLOW.replace(
    'if [[ "${advisory_created}" == "true" ]]; then',
    'uses: actions/upload-artifact@v4\n          with:\n            path: ${HOME}/security-audits\n          if [[ "${advisory_created}" == "true" ]]; then',
  ),
  1,
);

expect(
  "optioned report print fails",
  GOOD_WORKFLOW.replace(
    'slack_text="Private advisory created."',
    'head -c 200 "${report_tmp}"\n            slack_text="Private advisory created."',
  ),
  1,
);

expect(
  "advisory response body print fails",
  GOOD_WORKFLOW.replace(
    '"${gh_bin}" api --silent --method POST',
    '"${gh_bin}" api --method POST',
  ),
  1,
);

expect(
  "routing step missing trusted PATH reset fails",
  GOOD_WORKFLOW.replace('          export PATH="/usr/bin:/bin:/usr/sbin:/sbin"\n', ""),
  1,
);

expect(
  "routing step missing shell hook cleanup fails",
  GOOD_WORKFLOW.replace("          unset BASH_ENV ENV CDPATH\n", ""),
  1,
);

expect(
  "routing step direct gh lookup bypass fails",
  GOOD_WORKFLOW.replace('"${gh_bin}" api --silent --method POST', "gh api --silent --method POST"),
  1,
);

expect(
  "routing step direct jq lookup bypass fails",
  GOOD_WORKFLOW.replace('"${jq_bin}" -n', "jq -n"),
  1,
);

expect(
  "routing step direct curl lookup bypass fails",
  GOOD_WORKFLOW.replace('"${curl_bin}" -fsS -X POST', "curl -fsS -X POST"),
  1,
);

expect(
  "routing step direct gpg lookup bypass fails",
  GOOD_WORKFLOW.replace('"${gpg_bin}" --batch --yes --pinentry-mode loopback', "gpg --batch --yes --pinentry-mode loopback"),
  1,
);

expect(
  "routing step direct tar lookup bypass fails",
  GOOD_WORKFLOW.replace('"${tar_bin}" -czf - report.txt metadata.json', "tar -czf - report.txt metadata.json"),
  1,
);

expect(
  "encrypted evidence upload missing fails",
  GOOD_WORKFLOW.replace(
    /      - name: Upload encrypted security review evidence[\s\S]*?          retention-days: 30\n/u,
    "",
  ),
  1,
);

expect(
  "encrypted evidence key secret missing fails",
  GOOD_WORKFLOW.replace(
    "          SECURITY_REVIEW_EVIDENCE_KEY: ${{ secrets.SECURITY_REVIEW_EVIDENCE_KEY }}\n",
    "",
  ),
  1,
);

expect(
  "default GitHub token fails",
  GOOD_WORKFLOW.replace(
    "GH_TOKEN: ${{ secrets.SECURITY_ADVISORY_TOKEN }}",
    "GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}",
  ),
  1,
);

expect(
  "uppercase advisory ecosystem fails",
  GOOD_WORKFLOW.replace('ecosystem: \\"other\\"', 'ecosystem: \\"OTHER\\"'),
  1,
);

if (failed > 0) {
  console.error(`\n${failed} factory security-review boundary self-test(s) failed`);
  process.exit(1);
}

console.log(`\n${passed} factory security-review boundary self-test(s) passed`);
