#!/usr/bin/env node
/**
 * Self-test for scripts/ci/verify-factory-security-review-boundary.mjs.
 */

import { execFileSync } from "node:child_process";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const GATE = join(SCRIPT_DIR, "verify-factory-security-review-boundary.mjs");
const roots = [];
process.on("exit", () =>
  roots.forEach((dir) => rmSync(dir, { recursive: true, force: true })),
);

const fixture = (strings, ...values) =>
  String.raw({ raw: strings.raw }, ...values).replaceAll("\\${", "${");

const GOOD_WORKFLOW = fixture`
name: Factory Security Review
permissions:
  contents: read
  security-events: write
on:
  workflow_dispatch:
jobs:
  deep-security-review:
    steps:
      - name: Run mission-based deep security review
        env:
          FACTORY_API_KEY: \${{ secrets.FACTORY_API_KEY }}
        run: |
          set -euo pipefail
          review_output="\${RUNNER_TEMP}/factory-security-review-output.log"
          if ! droid exec --mission --auto high \
            --model "\${FACTORY_SECURITY_MODEL}" \
            "/security-review across the entire repository" \
            >"\${review_output}" 2>&1; then
            echo "::error::Droid security review failed. Raw mission output was kept on the runner and was not printed to CI logs."
            rm -f "\${review_output}"
            exit 1
          fi
          rm -f "\${review_output}"
          echo "Droid security review completed; raw mission output was not printed to CI logs."
      - name: Route critical findings to private security advisory
        run: |
          set -euo pipefail
          tmp_files=()
          cleanup() {
            for f in "\${tmp_files[@]}"; do
              rm -f "\${f}"
            done
          }
          trap cleanup EXIT
          report_tmp="$(mktemp)"
          tmp_files+=("\${report_tmp}")
          description_tmp="$(mktemp)"
          payload_tmp="$(mktemp)"
          tmp_files+=("\${description_tmp}" "\${payload_tmp}")
          find "\${HOME}/security-audits" -type f -print0 | sort -z | while IFS= read -r -d '' f; do
            rel="\${f#"\${HOME}/security-audits"/}"
            {
              echo "===== \${rel} ====="
              cat "\${f}"
              echo ""
            } >> "\${report_tmp}"
          done
          max_chars=60000
          {
            printf 'Auto-generated by the Factory Security Review workflow.\\n\\n'
            head -c "\${max_chars}" "\${report_tmp}"
          } > "\${description_tmp}"
          jq -n \
            --arg summary "Weekly security review" \
            --rawfile description "\${description_tmp}" \
            '{summary: $summary, description: $description, severity: "critical", confidential: true}' > "\${payload_tmp}"
          advisory_created=false
          if gh api --method POST "/repos/\${GITHUB_REPOSITORY}/security-advisories" \
            --input "\${payload_tmp}" \
            2>/dev/null; then
            advisory_created=true
          fi
          if [[ "\${advisory_created}" == "true" ]]; then
            slack_text="Private advisory created."
          else
            slack_text="Advisory creation failed; workflow failed closed without printing the report."
          fi
          # Slack is only an alert, never a substitute for the confidential report body.
          if [[ "\${advisory_created}" == "false" ]]; then
            echo "::error::Critical findings detected but private advisory routing failed. Raw report intentionally not printed to CI logs."
            exit 1
          fi
`;

function buildTree(workflow) {
  const root = mkdtempSync(join(tmpdir(), "factory-security-review-boundary-"));
  roots.push(root);
  const workflowDir = join(root, ".github", "workflows");
  mkdirSync(workflowDir, { recursive: true });
  writeFileSync(join(workflowDir, "factory-security-review.yml"), workflow);
  return root;
}

function runGate(root) {
  try {
    execFileSync("node", [GATE], {
      env: { ...process.env, FACTORY_SECURITY_REVIEW_BOUNDARY_ROOT: root },
      stdio: "pipe",
    });
    return 0;
  } catch (error) {
    return error.status ?? 1;
  }
}

let passed = 0;
let failed = 0;
function expect(label, workflow, wantExit) {
  const got = runGate(buildTree(workflow));
  if (got === wantExit) {
    console.log(`  PASS ${label} (exit ${got})`);
    passed += 1;
  } else {
    console.error(`  FAIL ${label}: expected exit ${wantExit}, got ${got}`);
    failed += 1;
  }
}

console.log("Self-test: verify-factory-security-review-boundary.mjs\n");

expect("hardened workflow passes", GOOD_WORKFLOW, 0);

expect(
  "unredirected Droid mission fails",
  GOOD_WORKFLOW.replace('            >"${review_output}" 2>&1; then\n', "            ; then\n"),
  1,
);

expect(
  "advisory body through argv fails",
  GOOD_WORKFLOW.replace(
    '--input "${payload_tmp}"',
    '-f description="${body}"',
  ).replace(
    'description_tmp="$(mktemp)"',
    'description_tmp="$(mktemp)"\n          body="$(head -c "${max_chars}" "${report_tmp}")',
  ),
  1,
);

expect(
  "CI-log report fallback fails",
  GOOD_WORKFLOW.replace(
    "workflow failed closed without printing the report",
    "review full report in CI logs",
  ),
  1,
);

expect(
  "Slack substituted for advisory fails",
  GOOD_WORKFLOW.replace(
    'if [[ "${advisory_created}" == "false" ]]; then',
    'if [[ "${advisory_created}" == "false" && "${slack_sent}" == "false" ]]; then',
  ),
  1,
);

expect(
  "raw artifact upload fails",
  GOOD_WORKFLOW.replace(
    'if [[ "${advisory_created}" == "true" ]]; then',
    'uses: actions/upload-artifact@v4\n          with:\n            path: ${HOME}/security-audits\n          if [[ "${advisory_created}" == "true" ]]; then',
  ),
  1,
);

if (failed > 0) {
  console.error(`\n${failed} factory security-review boundary self-test(s) failed`);
  process.exit(1);
}

console.log(`\n${passed} factory security-review boundary self-test(s) passed`);
