#!/usr/bin/env node
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { splitDocStatements } from "./verify-sqlite-schema-doc.mjs";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");

test("splitDocStatements skips framing and splits plain DDL", () => {
  const statements = splitDocStatements(`-- GENERATED BY x.
-- migrationEndpoint: v2_b
-- migrationCount: 2
-- schemaHashSHA256: 0

-- ── index a_idx ── (introduced: v2_b)
CREATE INDEX a_idx ON t(a);

-- ── table t ── (introduced: v1_a)
CREATE TABLE "t" ("id" TEXT PRIMARY KEY, "n" INTEGER NOT NULL DEFAULT 0);
`);
  assert.deepEqual(statements, [
    "CREATE INDEX a_idx ON t(a)",
    'CREATE TABLE "t" ("id" TEXT PRIMARY KEY, "n" INTEGER NOT NULL DEFAULT 0)',
  ]);
});

test("splitDocStatements keeps trigger bodies whole across internal semicolons", () => {
  const statements = splitDocStatements(`-- ── trigger t_ad ── (introduced: v3_c)
CREATE TRIGGER t_ad AFTER DELETE ON t BEGIN
    DELETE FROM t_fts WHERE rowid = old.rowid;
    UPDATE t_stats SET n = n - 1 WHERE id = 'a;b';
END;

-- ── table t_stats ── (introduced: v3_c)
CREATE TABLE t_stats(id TEXT PRIMARY KEY, n INTEGER NOT NULL);
`);
  assert.equal(statements.length, 2);
  assert.ok(statements[0].startsWith("CREATE TRIGGER t_ad"));
  assert.ok(statements[0].endsWith("END"));
  assert.ok(statements[0].includes("old.rowid;\n    UPDATE"));
  assert.equal(statements[1], "CREATE TABLE t_stats(id TEXT PRIMARY KEY, n INTEGER NOT NULL)");
});

test("splitDocStatements balances CASE..END inside triggers", () => {
  const statements = splitDocStatements(`CREATE TRIGGER t_au AFTER UPDATE ON t BEGIN
    UPDATE t SET n = CASE WHEN old.n IS NULL THEN 0 ELSE old.n END WHERE id = new.id;
END;
CREATE TABLE after_case(id TEXT);
`);
  assert.equal(statements.length, 2);
  assert.ok(statements[0].endsWith("END"));
  assert.equal(statements[1], "CREATE TABLE after_case(id TEXT)");
});

test("splitDocStatements ignores semicolons and parens inside literals", () => {
  const statements = splitDocStatements(`CREATE TABLE t(id TEXT DEFAULT 'a;b(c)', j TEXT DEFAULT '{"k":1}');
CREATE INDEX [weird;idx] ON "t"("id");
`);
  assert.deepEqual(statements, [
    `CREATE TABLE t(id TEXT DEFAULT 'a;b(c)', j TEXT DEFAULT '{"k":1}')`,
    'CREATE INDEX [weird;idx] ON "t"("id")',
  ]);
});

test("splitDocStatements fails closed on unterminated input", () => {
  assert.throws(() => splitDocStatements("CREATE TABLE t(id TEXT"), /no terminating ;/u);
  assert.throws(
    () => splitDocStatements("CREATE TRIGGER t_ai AFTER INSERT ON t BEGIN\n    SELECT 1;\n"),
    /unbalanced BEGIN\/END/u
  );
  assert.throws(
    () => splitDocStatements("CREATE TABLE t(id TEXT DEFAULT 'oops);"),
    /unterminated literal/u
  );
});

test("live doc: split reproduces every framed object and the header hash", () => {
  const docText = readFileSync(path.join(repoRoot, "docs", "SCHEMA_SQLITE.sql"), "utf8");
  const statements = splitDocStatements(docText);
  const framed = docText.split("\n").filter((line) => line.startsWith("-- ── ")).length;
  assert.equal(statements.length, framed);
  assert.ok(statements.length > 200, `expected hundreds of statements, got ${statements.length}`);
  const headerHash = docText.match(/^-- schemaHashSHA256: ([0-9a-f]{64})/m)?.[1];
  assert.ok(headerHash, "doc header must carry schemaHashSHA256");
  const rejoined = createHash("sha256").update(statements.join("\n"), "utf8").digest("hex");
  assert.equal(rejoined, headerHash);
});
