#!/usr/bin/env node
/**
 * Codegen for the BurnBar data-domain registry.
 *
 * Reads registry.json and emits typed, identical domain definitions for all
 * three client platforms so the Data & Privacy Control Center renders the same
 * domains + encryption tiers everywhere, from one source of truth:
 *   gen/domains.ts     — web (TS)
 *   gen/DataDomains.swift — iOS / iPadOS / macOS
 *   gen/DataDomains.kt    — Android
 *
 * Pure Node, no dependencies. Run: node codegen.mjs
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const GEN = join(HERE, "gen");

export function loadRegistry() {
  return JSON.parse(readFileSync(join(HERE, "registry.json"), "utf8"));
}

const TIERS = ["server_readable", "zero_access", "end_to_end"];

/** Validate the registry shape; throw on any structural problem (also used by the test). */
export function validateRegistry(reg) {
  const errors = [];
  if (reg.schemaVersion !== 1) errors.push(`schemaVersion must be 1, got ${reg.schemaVersion}`);
  if (!Array.isArray(reg.domains) || reg.domains.length === 0) errors.push("domains must be a non-empty array");
  const ids = new Set();
  for (const d of reg.domains ?? []) {
    if (!d.id || ids.has(d.id)) errors.push(`duplicate or missing domain id: ${d.id}`);
    ids.add(d.id);
    if (!TIERS.includes(d.encryptionTier)) errors.push(`${d.id}: invalid encryptionTier ${d.encryptionTier}`);
    if (!d.title) errors.push(`${d.id}: missing title`);
    if (!Array.isArray(d.firestorePaths)) errors.push(`${d.id}: firestorePaths must be an array`);
    if (!Array.isArray(d.actions)) errors.push(`${d.id}: actions must be an array`);
  }
  if (errors.length) throw new Error(`registry.json invalid:\n  - ${errors.join("\n  - ")}`);
  return reg;
}

const HEADER = "// GENERATED by packages/data-domains/codegen.mjs — DO NOT EDIT. Source: registry.json";

function esc(s) {
  return String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function emitTs(reg) {
  const tierUnion = TIERS.map((t) => `"${t}"`).join(" | ");
  const lines = [
    HEADER,
    "",
    `export type EncryptionTier = ${tierUnion};`,
    "export type DomainAction = string;",
    "",
    "export interface DataDomain {",
    "  id: string;",
    "  title: string;",
    "  icon: string;",
    "  encryptionTier: EncryptionTier;",
    "  summary: string;",
    "  serverSees: string[];",
    "  deviceOnly: string[];",
    "  firestorePaths: string[];",
    "  storagePaths: string[];",
    "  countSource: string | null;",
    "  byteSource: string | null;",
    "  retention: string;",
    "  actions: DomainAction[];",
    "  callables: Record<string, string>;",
    "  entitlementGate: string | null;",
    "  suspensionSurface: string | null;",
    "  /** Optional reference to a tiered-limits table (e.g. PENSIEVE_LIMITS). */",
    "  tieredLimits?: string;",
    "}",
    "",
    `export const ENCRYPTION_TIERS = ${JSON.stringify(reg.encryptionTiers, null, 2)} as const;`,
    "",
    "export const DATA_DOMAINS: readonly DataDomain[] = " + JSON.stringify(reg.domains, null, 2) + " as const;",
    "",
    "export const DATA_DOMAIN_IDS = DATA_DOMAINS.map((d) => d.id);",
    "export function dataDomain(id: string): DataDomain | undefined { return DATA_DOMAINS.find((d) => d.id === id); }",
    "",
  ];
  return lines.join("\n");
}

function swiftStringArray(arr) {
  return "[" + arr.map((s) => `"${esc(s)}"`).join(", ") + "]";
}

function emitSwift(reg) {
  const cases = TIERS.map((t) => `    case ${camel(t)} = "${t}"`).join("\n");
  const out = [HEADER, "", "import Foundation", "", "public enum EncryptionTier: String, Codable, Sendable {", cases, "}", ""];
  out.push("public struct DataDomain: Identifiable, Codable, Sendable {");
  out.push("    public let id: String");
  out.push("    public let title: String");
  out.push("    public let icon: String");
  out.push("    public let encryptionTier: EncryptionTier");
  out.push("    public let summary: String");
  out.push("    public let serverSees: [String]");
  out.push("    public let deviceOnly: [String]");
  out.push("    public let firestorePaths: [String]");
  out.push("    public let storagePaths: [String]");
  out.push("    public let countSource: String?");
  out.push("    public let byteSource: String?");
  out.push("    public let retention: String");
  out.push("    public let actions: [String]");
  out.push("    public let entitlementGate: String?");
  out.push("    public let suspensionSurface: String?");
  out.push("}");
  out.push("");
  out.push("public enum DataDomains {");
  out.push("    public static let all: [DataDomain] = [");
  for (const d of reg.domains) {
    out.push("        DataDomain(");
    out.push(`            id: "${esc(d.id)}", title: "${esc(d.title)}", icon: "${esc(d.icon)}",`);
    out.push(`            encryptionTier: .${camel(d.encryptionTier)}, summary: "${esc(d.summary)}",`);
    out.push(`            serverSees: ${swiftStringArray(d.serverSees)}, deviceOnly: ${swiftStringArray(d.deviceOnly)},`);
    out.push(`            firestorePaths: ${swiftStringArray(d.firestorePaths)}, storagePaths: ${swiftStringArray(d.storagePaths)},`);
    out.push(`            countSource: ${d.countSource ? `"${esc(d.countSource)}"` : "nil"}, byteSource: ${d.byteSource ? `"${esc(d.byteSource)}"` : "nil"},`);
    out.push(`            retention: "${esc(d.retention)}", actions: ${swiftStringArray(d.actions)},`);
    out.push(`            entitlementGate: ${d.entitlementGate ? `"${esc(d.entitlementGate)}"` : "nil"}, suspensionSurface: ${d.suspensionSurface ? `"${esc(d.suspensionSurface)}"` : "nil"}`);
    out.push("        ),");
  }
  out.push("    ]");
  out.push("    public static func domain(_ id: String) -> DataDomain? { all.first { $0.id == id } }");
  out.push("}");
  out.push("");
  return out.join("\n");
}

function kotlinStringList(arr) {
  return "listOf(" + arr.map((s) => `"${esc(s)}"`).join(", ") + ")";
}

function emitKotlin(reg) {
  const out = [HEADER, "", "package com.openburnbar.data.domains", ""];
  out.push("enum class EncryptionTier(val raw: String) {");
  out.push("    " + TIERS.map((t) => `${t.toUpperCase()}("${t}")`).join(",\n    ") + ";");
  out.push("    companion object { fun from(raw: String) = entries.first { it.raw == raw } }");
  out.push("}");
  out.push("");
  out.push("data class DataDomain(");
  out.push("    val id: String,");
  out.push("    val title: String,");
  out.push("    val icon: String,");
  out.push("    val encryptionTier: EncryptionTier,");
  out.push("    val summary: String,");
  out.push("    val serverSees: List<String>,");
  out.push("    val deviceOnly: List<String>,");
  out.push("    val firestorePaths: List<String>,");
  out.push("    val storagePaths: List<String>,");
  out.push("    val countSource: String?,");
  out.push("    val byteSource: String?,");
  out.push("    val retention: String,");
  out.push("    val actions: List<String>,");
  out.push("    val entitlementGate: String?,");
  out.push("    val suspensionSurface: String?,");
  out.push(")");
  out.push("");
  out.push("object DataDomains {");
  out.push("    val all: List<DataDomain> = listOf(");
  for (const d of reg.domains) {
    out.push("        DataDomain(");
    out.push(`            id = "${esc(d.id)}", title = "${esc(d.title)}", icon = "${esc(d.icon)}",`);
    out.push(`            encryptionTier = EncryptionTier.${d.encryptionTier.toUpperCase()}, summary = "${esc(d.summary)}",`);
    out.push(`            serverSees = ${kotlinStringList(d.serverSees)}, deviceOnly = ${kotlinStringList(d.deviceOnly)},`);
    out.push(`            firestorePaths = ${kotlinStringList(d.firestorePaths)}, storagePaths = ${kotlinStringList(d.storagePaths)},`);
    out.push(`            countSource = ${d.countSource ? `"${esc(d.countSource)}"` : "null"}, byteSource = ${d.byteSource ? `"${esc(d.byteSource)}"` : "null"},`);
    out.push(`            retention = "${esc(d.retention)}", actions = ${kotlinStringList(d.actions)},`);
    out.push(`            entitlementGate = ${d.entitlementGate ? `"${esc(d.entitlementGate)}"` : "null"}, suspensionSurface = ${d.suspensionSurface ? `"${esc(d.suspensionSurface)}"` : "null"},`);
    out.push("        ),");
  }
  out.push("    )");
  out.push("    fun domain(id: String): DataDomain? = all.firstOrNull { it.id == id }");
  out.push("}");
  out.push("");
  return out.join("\n");
}

function camel(snake) {
  return snake.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

export function generateAll(reg) {
  return {
    "gen/domains.ts": emitTs(reg),
    "gen/DataDomains.swift": emitSwift(reg),
    "gen/DataDomains.kt": emitKotlin(reg),
  };
}

function main() {
  const reg = validateRegistry(loadRegistry());
  mkdirSync(GEN, { recursive: true });
  const files = generateAll(reg);
  for (const [rel, content] of Object.entries(files)) {
    writeFileSync(join(HERE, rel), content);
  }
  console.log(`[data-domains] generated ${Object.keys(files).length} files for ${reg.domains.length} domains.`);
}

if (import.meta.url === `file://${process.argv[1]}`) main();
