// Generated by scripts/generate-provider-ingestion-catalog.mjs.
// Source of truth: contracts/provider-ingestion-catalog.json. Do not edit manually.

import Foundation
import OpenBurnBarKernel

public enum AgentProviderIngestionCoverage: String, Codable, Sendable {
    case localParser = "local-parser"
    case apiBacked = "api-backed"
    case unavailable
}

public enum AgentProviderIngestionCatalog {
    public struct Entry: Equatable, Sendable {
        public let provider: AgentProvider
        public let agentProviderCase: String
        public let providerID: String
        public let displayLabel: String
        public let aliases: [String]
        public let linuxLogicalPath: String
        public let macOSLogicalPath: String
        public let filePattern: String
        public let ingestion: AgentProviderIngestionCoverage
        public let coverageNote: String
        public let quotaSignal: Bool
    }

    public static let entries: [Entry] = [
        Entry(
            provider: .factory,
            agentProviderCase: "factory",
            providerID: "droid",
            displayLabel: "Droid / Factory",
            aliases: ["factory", "factory-droid"],
            linuxLogicalPath: "~/.factory/sessions",
            macOSLogicalPath: "~/.factory/sessions",
            filePattern: "*.jsonl",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: true
        ),
        Entry(
            provider: .claudeCode,
            agentProviderCase: "claudeCode",
            providerID: "claude",
            displayLabel: "Claude Code",
            aliases: ["anthropic", "claude-code"],
            linuxLogicalPath: "~/.claude/projects",
            macOSLogicalPath: "~/.claude/projects",
            filePattern: "*.jsonl",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: true
        ),
        Entry(
            provider: .copilot,
            agentProviderCase: "copilot",
            providerID: "copilot",
            displayLabel: "Copilot",
            aliases: [],
            linuxLogicalPath: "~/.copilot/session-state",
            macOSLogicalPath: "~/.copilot/session-state",
            filePattern: "*.jsonl",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: true
        ),
        Entry(
            provider: .aider,
            agentProviderCase: "aider",
            providerID: "aider",
            displayLabel: "Aider",
            aliases: [],
            linuxLogicalPath: "~/.aider",
            macOSLogicalPath: "~/.aider",
            filePattern: "*.jsonl",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: false
        ),
        Entry(
            provider: .cursor,
            agentProviderCase: "cursor",
            providerID: "cursor",
            displayLabel: "Cursor",
            aliases: [],
            linuxLogicalPath: "~/.cursor/ai-tracking",
            macOSLogicalPath: "~/.cursor/ai-tracking",
            filePattern: "*.db",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: true
        ),
        Entry(
            provider: .openAI,
            agentProviderCase: "openAI",
            providerID: "openai",
            displayLabel: "OpenAI",
            aliases: [],
            linuxLogicalPath: "~/.codex",
            macOSLogicalPath: "~/.codex",
            filePattern: "openai-no-local-logs",
            ingestion: .apiBacked,
            coverageNote: "No local parser; usage is supplied by the official API path.",
            quotaSignal: true
        ),
        Entry(
            provider: .openBurnBar,
            agentProviderCase: "openBurnBar",
            providerID: "openburnbar",
            displayLabel: "OpenBurnBar",
            aliases: [],
            linuxLogicalPath: "~/.codex",
            macOSLogicalPath: "~/.codex",
            filePattern: "openburnbar-no-local-logs",
            ingestion: .apiBacked,
            coverageNote: "No local parser; usage is recorded by the native app/ledger path.",
            quotaSignal: true
        ),
        Entry(
            provider: .deepSeek,
            agentProviderCase: "deepSeek",
            providerID: "deepseek",
            displayLabel: "DeepSeek",
            aliases: [],
            linuxLogicalPath: "~/.codex",
            macOSLogicalPath: "~/.codex",
            filePattern: "deepseek-no-local-logs",
            ingestion: .apiBacked,
            coverageNote: "No local parser; quota and usage require the provider API path.",
            quotaSignal: true
        ),
        Entry(
            provider: .codex,
            agentProviderCase: "codex",
            providerID: "codex",
            displayLabel: "Codex",
            aliases: [],
            linuxLogicalPath: "~/.codex/sessions",
            macOSLogicalPath: "~/.codex/sessions",
            filePattern: "*.jsonl",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: true
        ),
        Entry(
            provider: .openCode,
            agentProviderCase: "openCode",
            providerID: "opencode",
            displayLabel: "OpenCode",
            aliases: ["opencode-go"],
            linuxLogicalPath: "~/.local/share/opencode",
            macOSLogicalPath: "~/.local/share/opencode",
            filePattern: "opencode.db",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: true
        ),
        Entry(
            provider: .zai,
            agentProviderCase: "zai",
            providerID: "zai",
            displayLabel: "Z.ai",
            aliases: [],
            linuxLogicalPath: "~/.factory/sessions",
            macOSLogicalPath: "~/.factory/sessions",
            filePattern: "*.jsonl",
            ingestion: .localParser,
            coverageNote: "Local model-filter parser registered in ParserRegistry.",
            quotaSignal: true
        ),
        Entry(
            provider: .minimax,
            agentProviderCase: "minimax",
            providerID: "minimax",
            displayLabel: "MiniMax",
            aliases: [],
            linuxLogicalPath: "~/.factory/sessions",
            macOSLogicalPath: "~/.factory/sessions",
            filePattern: "*.jsonl",
            ingestion: .localParser,
            coverageNote: "Local model-filter parser registered in ParserRegistry.",
            quotaSignal: true
        ),
        Entry(
            provider: .kimi,
            agentProviderCase: "kimi",
            providerID: "kimi",
            displayLabel: "Kimi",
            aliases: ["moonshot"],
            linuxLogicalPath: "~/.kimi/sessions",
            macOSLogicalPath: "~/.kimi/sessions",
            filePattern: "*.jsonl",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: true
        ),
        Entry(
            provider: .cline,
            agentProviderCase: "cline",
            providerID: "cline",
            displayLabel: "Cline",
            aliases: [],
            linuxLogicalPath: "~/.config/Code/User/globalStorage/saoudrizwan.claude-dev/tasks",
            macOSLogicalPath: "~/Library/Application Support/Code/User/globalStorage/saoudrizwan.claude-dev/tasks",
            filePattern: "*.json",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: false
        ),
        Entry(
            provider: .kiloCode,
            agentProviderCase: "kiloCode",
            providerID: "kilocode",
            displayLabel: "Kilo Code",
            aliases: ["kilo-code"],
            linuxLogicalPath: "~/.config/Code/User/globalStorage/kilocode.kilo-code/tasks",
            macOSLogicalPath: "~/Library/Application Support/Code/User/globalStorage/kilocode.kilo-code/tasks",
            filePattern: "*.json",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: false
        ),
        Entry(
            provider: .rooCode,
            agentProviderCase: "rooCode",
            providerID: "roocode",
            displayLabel: "Roo Code",
            aliases: ["roo-code"],
            linuxLogicalPath: "~/.config/Code/User/globalStorage/rooveterinaryinc.roo-cline/tasks",
            macOSLogicalPath: "~/Library/Application Support/Code/User/globalStorage/rooveterinaryinc.roo-cline/tasks",
            filePattern: "*.json",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: false
        ),
        Entry(
            provider: .forgeDev,
            agentProviderCase: "forgeDev",
            providerID: "forge",
            displayLabel: "Forge",
            aliases: ["forge-dev"],
            linuxLogicalPath: "~/.forge/sessions",
            macOSLogicalPath: "~/.forge/sessions",
            filePattern: "*.jsonl",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: false
        ),
        Entry(
            provider: .augment,
            agentProviderCase: "augment",
            providerID: "augment",
            displayLabel: "Augment",
            aliases: [],
            linuxLogicalPath: "~/.config/Code/User/globalStorage/augment.vscode-augment",
            macOSLogicalPath: "~/Library/Application Support/Code/User/globalStorage/augment.vscode-augment",
            filePattern: "*.jsonl",
            ingestion: .localParser,
            coverageNote: "Parser is registered, but macOS marks this source unsupported.",
            quotaSignal: false
        ),
        Entry(
            provider: .hermes,
            agentProviderCase: "hermes",
            providerID: "hermes",
            displayLabel: "Hermes",
            aliases: [],
            linuxLogicalPath: "~/.hermes/sessions",
            macOSLogicalPath: "~/.hermes/sessions",
            filePattern: "*.jsonl",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: false
        ),
        Entry(
            provider: .piAgent,
            agentProviderCase: "piAgent",
            providerID: "pi",
            displayLabel: "Pi Agent",
            aliases: ["pi-agent"],
            linuxLogicalPath: "~/.pi/sessions",
            macOSLogicalPath: "~/.pi/sessions",
            filePattern: "*.jsonl",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: false
        ),
        Entry(
            provider: .geminiCLI,
            agentProviderCase: "geminiCLI",
            providerID: "gemini",
            displayLabel: "Gemini CLI",
            aliases: ["google", "gemini-cli"],
            linuxLogicalPath: "~/.gemini/tmp",
            macOSLogicalPath: "~/.gemini/tmp",
            filePattern: "*.json",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: false
        ),
        Entry(
            provider: .antigravity,
            agentProviderCase: "antigravity",
            providerID: "antigravity",
            displayLabel: "Antigravity",
            aliases: ["antigravity-cli"],
            linuxLogicalPath: "~/.gemini/antigravity-cli",
            macOSLogicalPath: "~/.gemini/antigravity-cli",
            filePattern: "history.jsonl",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: true
        ),
        Entry(
            provider: .goose,
            agentProviderCase: "goose",
            providerID: "goose",
            displayLabel: "Goose",
            aliases: [],
            linuxLogicalPath: "~/.local/share/goose/sessions",
            macOSLogicalPath: "~/.local/share/goose/sessions",
            filePattern: "sessions.db",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: false
        ),
        Entry(
            provider: .openClaw,
            agentProviderCase: "openClaw",
            providerID: "openclaw",
            displayLabel: "OpenClaw",
            aliases: ["open-claw"],
            linuxLogicalPath: "~/.openclaw/sessions",
            macOSLogicalPath: "~/.openclaw/sessions",
            filePattern: "*.jsonl",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: false
        ),
        Entry(
            provider: .openClaude,
            agentProviderCase: "openClaude",
            providerID: "openclaude",
            displayLabel: "OpenClaude",
            aliases: ["open-claude"],
            linuxLogicalPath: "~/.openclaude/projects",
            macOSLogicalPath: "~/.openclaude/projects",
            filePattern: "*.jsonl",
            ingestion: .localParser,
            coverageNote: "Claude-compatible local transcript parser registered in ParserRegistry.",
            quotaSignal: false
        ),
        Entry(
            provider: .omp,
            agentProviderCase: "omp",
            providerID: "omp",
            displayLabel: "OMP",
            aliases: ["oh-my-pi"],
            linuxLogicalPath: "~/.omp/agent/sessions",
            macOSLogicalPath: "~/.omp/agent/sessions",
            filePattern: "*.jsonl",
            ingestion: .localParser,
            coverageNote: "Pi-compatible local parser registered in ParserRegistry.",
            quotaSignal: true
        ),
        Entry(
            provider: .ollama,
            agentProviderCase: "ollama",
            providerID: "ollama",
            displayLabel: "Ollama",
            aliases: [],
            linuxLogicalPath: "~/.ollama/logs",
            macOSLogicalPath: "~/.ollama/logs",
            filePattern: "server*.log",
            ingestion: .localParser,
            coverageNote: "Local model-filter parser registered in ParserRegistry.",
            quotaSignal: true
        ),
        Entry(
            provider: .windsurf,
            agentProviderCase: "windsurf",
            providerID: "windsurf",
            displayLabel: "Windsurf",
            aliases: [],
            linuxLogicalPath: "~/.config/Windsurf - Next/User/globalStorage",
            macOSLogicalPath: "~/Library/Application Support/Windsurf - Next/User/globalStorage",
            filePattern: "state.vscdb",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: false
        ),
        Entry(
            provider: .devin,
            agentProviderCase: "devin",
            providerID: "devin",
            displayLabel: "Devin",
            aliases: ["devin-desktop", "devin-cli"],
            linuxLogicalPath: "~/.config/Devin/sessions",
            macOSLogicalPath: "~/Library/Application Support/Devin/sessions",
            filePattern: "*.jsonl",
            ingestion: .unavailable,
            coverageNote: "Devin Desktop supersedes Windsurf branding, but no Devin session parser is registered yet. Keep the provider visible with unavailable local usage until a real parser ships.",
            quotaSignal: false
        ),
        Entry(
            provider: .warp,
            agentProviderCase: "warp",
            providerID: "warp",
            displayLabel: "Warp",
            aliases: [],
            linuxLogicalPath: "~/.config/Warp",
            macOSLogicalPath: "~/Library/Application Support/dev.warp.Warp-Stable",
            filePattern: "warp_network*.log",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: true
        ),
        Entry(
            provider: .xAI,
            agentProviderCase: "xAI",
            providerID: "grok",
            displayLabel: "Grok / xAI",
            aliases: ["xai", "x.ai"],
            linuxLogicalPath: "~/.grok/sessions",
            macOSLogicalPath: "~/.grok/sessions",
            filePattern: "summary.json",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: true
        ),
        Entry(
            provider: .mimo,
            agentProviderCase: "mimo",
            providerID: "mimo",
            displayLabel: "MiMo",
            aliases: ["xiaomi-mimo"],
            linuxLogicalPath: "~/.codex",
            macOSLogicalPath: "~/.codex",
            filePattern: "mimo-no-local-logs",
            ingestion: .apiBacked,
            coverageNote: "No local parser; usage requires the MiMo API/token-plan path.",
            quotaSignal: true
        ),
        Entry(
            provider: .cursorAgent,
            agentProviderCase: "cursorAgent",
            providerID: "cursor-agent",
            displayLabel: "Cursor Agent",
            aliases: ["cursoragent"],
            linuxLogicalPath: "~/.cursor-agent/sessions",
            macOSLogicalPath: "~/.cursor-agent/sessions",
            filePattern: "*.jsonl",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: true
        ),
        Entry(
            provider: .junie,
            agentProviderCase: "junie",
            providerID: "junie",
            displayLabel: "Junie",
            aliases: ["jetbrains-junie"],
            linuxLogicalPath: "~/.junie/sessions",
            macOSLogicalPath: "~/.junie/sessions",
            filePattern: "*.jsonl",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: false
        ),
        Entry(
            provider: .primeAgent,
            agentProviderCase: "primeAgent",
            providerID: "prime-agent",
            displayLabel: "Prime Agent",
            aliases: ["prime", "prime-agent"],
            linuxLogicalPath: "~/.prime/agent/sessions",
            macOSLogicalPath: "~/.prime/agent/sessions",
            filePattern: "*.jsonl",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: false
        ),
        Entry(
            provider: .muse,
            agentProviderCase: "muse",
            providerID: "muse",
            displayLabel: "Muse",
            aliases: ["muse-code", "meta-muse"],
            linuxLogicalPath: "~/.local/share/muse/sessions",
            macOSLogicalPath: "~/.local/share/muse/sessions",
            filePattern: "*.jsonl",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: false
        ),
        Entry(
            provider: .fx,
            agentProviderCase: "fx",
            providerID: "fx",
            displayLabel: "fx",
            aliases: ["vercel-fx"],
            linuxLogicalPath: "~/.fx/sessions",
            macOSLogicalPath: "~/.fx/sessions",
            filePattern: "*.json",
            ingestion: .localParser,
            coverageNote: "Local parser registered in ParserRegistry.",
            quotaSignal: false
        )
    ]

    private static let entriesByProvider = Dictionary(
        uniqueKeysWithValues: entries.map { ($0.provider, $0) }
    )

    public static func entry(for provider: AgentProvider) -> Entry {
        guard let entry = entriesByProvider[provider] else {
            preconditionFailure("Missing provider ingestion catalog entry for \(provider.rawValue)")
        }
        return entry
    }

    public static var localParserProviders: Set<AgentProvider> {
        Set(entries.lazy.filter { $0.ingestion == .localParser }.map(\.provider))
    }

    public static var quotaSignalProviders: Set<AgentProvider> {
        Set(entries.lazy.filter(\.quotaSignal).map(\.provider))
    }
}
