/**
 * @fileoverview Shared TypeScript types for OpenBurnBar Cloud Functions v2.
 *
 * Extracted from src/types/legacy.ts (the strangler "leftovers" bucket) and
 * grouped by domain. Re-exported verbatim from src/types/legacy.ts so every
 * existing `import ... from "../types/legacy"` keeps resolving unchanged.
 */

import type { CloudVaultSealedTextDoc } from "./quota-usage.js";

// ---------------------------------------------------------------------------
// Mercury media (file transfer, screen share, 1:1 video calling)
//
// Schema mirrors the iroh transport docs in `IrohTransportAuditEventDoc` /
// `IrohTransportDailyRollupDoc`. Source of truth and lifecycle live in
// `plans/2026-05-15-mercury-media-master-plan.md` § F + § H.
// ---------------------------------------------------------------------------

export type MediaFeature = "fileTransfer" | "screenShare" | "videoCall";

export type MediaStreamClass =
  | "media.blob"
  | "media.blob.advertise"
  | "media.blob.fetch"
  | "media.screen.video"
  | "media.audio.out"
  | "media.audio.in"
  | "media.video.out"
  | "media.video.in"
  | "media.control"
  | "media.classify";

export type MediaSessionEndReason =
  | "completedSuccess"
  | "completedUserCancel"
  | "completedPeerCancel"
  | "timeout"
  | "error"
  | "entitlementRevoked"
  | "budgetSoftCap"
  | "budgetHardCap"
  | "thermalCritical";

/**
 * Per-session telemetry record. Pure metadata — never carries payload bytes,
 * filenames, hashes, or peer NodeIds in plaintext. Bucketed enums only.
 *
 * Path: `users/{uid}/media_session_events/{eventId}`
 */
export interface MediaSessionEventDoc {
  id: string;
  sessionId: string;
  feature: MediaFeature;
  streamClass: MediaStreamClass;
  startedAt: string; // ISO 8601 UTC
  endedAt?: string;
  endReason?: MediaSessionEndReason;
  peerDeviceIdHash?: string; // SHA-256 of NodeId, never plaintext
  byteCountInbound: number;
  byteCountOutbound: number;
  freezeCount: number;
  p95RoundTripMillisBucket?: "lt_50ms" | "50_150ms" | "150_400ms" | "gte_400ms";
  p95BitsPerSecondBucket?:
    | "lt_300kbps"
    | "300_600kbps"
    | "600kbps_1mbps"
    | "1_2mbps"
    | "2_4mbps"
    | "4_8mbps"
    | "gte_8mbps";
  durationBucket?: "lt_30s" | "30s_2m" | "2m_10m" | "10m_30m" | "30m_60m" | "gte_60m";
  expireAt?: import("firebase-admin/firestore").Timestamp;
  schemaVersion: number;
}

/**
 * Daily quota usage counter per user. Written only by the hourly
 * `recomputeMediaQuotaUsage` Cloud Function from bounded media session
 * metadata. The Mac is the source of truth for live capability gating; this
 * server-owned doc is the persisted start-of-session reconcile target.
 *
 * Path: `users/{uid}/media_quota_usage/{YYYY-MM-DD}`
 */
export type MediaQuotaUsageDoc = import("../generated/media-analytics.js").MediaQuotaUsageDoc & {
  fileTransfersInitiated: number;
  fileTransfersFailed: number;
  screenShareSecondsUsed: number;
  screenShareSessions: number;
  videoCallSecondsUsed: number;
  videoCallSessions: number;
  updatedAt: import("firebase-admin/firestore").Timestamp;
  schemaVersion: number;
};

/**
 * Per-attachment manifest. Bytes themselves never live in Firestore — they
 * flow peer-to-peer over iroh-blobs. The manifest is a small audit record
 * so DSR exports and admin tooling can answer "what files have been sent
 * from this Mac to which paired iPhones."
 *
 * Path: `users/{uid}/media_attachment_manifests/{manifestId}`
 */
export interface MediaAttachmentManifestDoc {
  id: string; // manifestId
  blobHash: string; // BLAKE3 hex
  /**
   * @deprecated Legacy plaintext filename. New writers send `sealedFilename`
   * (vault-sealed AES-256-GCM). The Firestore rule rejects a plaintext `filename`
   * once a `sealedFilename` is present; this stays optional only for in-flight /
   * pre-migration docs (privacy-leak-remediation-2026-06-02 Fork F = SEAL).
   */
  filename?: string;
  /** Vault-sealed filename — the server never sees the cleartext name. */
  sealedFilename?: CloudVaultSealedTextDoc;
  mime: string;
  size: number; // bytes
  peerDeviceIdHash: string; // SHA-256 of NodeId, never plaintext
  direction: "macToIos" | "iosToMac";
  createdAt: import("firebase-admin/firestore").Timestamp;
  expireAt?: import("firebase-admin/firestore").Timestamp;
  schemaVersion: number;
}

/**
 * Daily rollup of `media_session_events` for the operator dashboard. Mirrors
 * `IrohTransportDailyRollupDoc` shape. Generated by the
 * `rollupMediaSessionDaily` Cloud Function.
 *
 * Path: `ops/media_session_daily_rollups/days/{YYYY-MM-DD}`
 */
export interface MediaSessionDailyRollupDoc {
  id: string;
  date: string;
  windowStart: string;
  windowEnd: string;
  generatedAt: string;
  totalEvents: number;
  uniqueUsers: number;
  perFeature: Record<
    MediaFeature,
    {
      sessionCount: number;
      successRate: number;
      fallbackRate: number;
      totalSeconds: number;
      totalBytes: number;
      rttMillis: { count: number; p50?: number; p95?: number; p99?: number; sketchBase64?: string };
      bitsPerSecond: { count: number; p50?: number; p95?: number; p99?: number; sketchBase64?: string };
      freezeCount: { count: number; p50?: number; p95?: number; p99?: number; sketchBase64?: string };
    }
  >;
  schemaVersion: number;
}

export type MediaBudgetLevel = "normal" | "soft_cap" | "hard_cap";

/**
 * Current state of the n0 hosted-relay budget guardrail. Single document
 * at `ops/media_budget_status/state/current`. Server-only writes; both apps cache
 * the value for 60 s and re-read on session start.
 *
 * Operator runbook: `docs/runbooks/media-budget.md`.
 * Decision: master plan Decision 4 ($600 soft / $1000 hard).
 */
export interface MediaBudgetStatusDoc {
  level: MediaBudgetLevel;
  projectedMonthEndUSD: number;
  monthToDateUSD: number;
  lastEvaluatedAt: import("firebase-admin/firestore").Timestamp;
  activeEnvelope: {
    screenShareDailyMinutes: number;
    screenSharePerSessionMinutes: number;
    videoCallDailyMinutes: number;
    videoCallPerCallMinutes: number;
    fileTransferDailyGBIn: number;
    fileTransferDailyGBOut: number;
  };
  schemaVersion: number;
}

// MARK: - Computer Use (master plan 2026-05-16)

export type ComputerUseMode = "agent_watch" | "browser" | "system";
export type ComputerUseTrustMode = "manual" | "step" | "trusted";
export type ComputerUseBudgetLevel = "normal" | "soft_cap" | "hard_cap";
export type ComputerUseEndReason =
  | "completed"
  | "user_halt"
  | "panic_hotkey"
  | "panic_phone_gesture"
  | "panic_mac_lock"
  | "panic_remote_config"
  | "panic_accessibility_revoked"
  | "timeout"
  | "entitlement_lost"
  | "budget_soft_cap"
  | "budget_hard_cap"
  | "error";
export type ComputerUseActionStatus = "executed" | "denied" | "rejected" | "awaiting_approval" | "error";
export type ComputerUseApprovedBy = "mac" | "phone" | "trusted_scope" | "step" | "denied" | "panic";

/**
 * Session record. Persisted server-side at session end with metadata
 * only — never carries the action descriptors, screenshots, or scope
 * rule contents. The full chain lives on the user's Mac under
 * `~/Library/Application Support/...`.
 *
 * Path: `users/{uid}/computer_use_sessions/{sessionId}`
 */
export interface ComputerUseSessionDoc {
  id: string;
  sessionId: string;
  userId: string;
  mode: ComputerUseMode;
  trustMode: ComputerUseTrustMode;
  startedAt: import("firebase-admin/firestore").Timestamp;
  endedAt?: import("firebase-admin/firestore").Timestamp;
  endReason?: ComputerUseEndReason;
  actionCount: number;
  approvalCount: number;
  rejectionCount: number;
  panicHaltCount: number;
  visionSpendUSD: number;
  manifestHashHex: string;
  auditHeadHashHex?: string;
  macAppVersion: string;
  schemaVersion: number;
  quotaStartMeteredEventId?: string;
  quotaStartMeteredDayKey?: string;
  quotaStartMeteredAt?: import("firebase-admin/firestore").Timestamp;
  quotaCompletionMeteredEventId?: string;
  quotaCompletionMeteredDayKey?: string;
  quotaCompletionMeteredAt?: import("firebase-admin/firestore").Timestamp;
}

/**
 * Per-action audit *header* mirrored from the Mac's on-disk JSONL
 * chain. The on-disk chain carries the full descriptor + screenshot
 * hashes; this server doc holds only the chain links + status so the
 * phone can render the live timeline without reading the local
 * filesystem.
 *
 * Path: `users/{uid}/computer_use_actions/{actionId}`
 */
export interface ComputerUseActionDoc {
  id: string;
  sessionId: string;
  entryIndex: number;
  toolKind: string;
  actionKind: string;
  status: ComputerUseActionStatus;
  approvedBy: ComputerUseApprovedBy;
  scopeRuleId?: string;
  denyReason?: string;
  parentEntryHashHex: string;
  approvalLatencyMillis?: number;
  visionTokensCostUSD?: number;
  recordedAt: import("firebase-admin/firestore").Timestamp;
  schemaVersion: number;
  quotaMeteredEventId?: string;
  quotaMeteredDayKey?: string;
  quotaMeteredAt?: import("firebase-admin/firestore").Timestamp;
}

/**
 * Daily counters mirrored from the Mac. Source-of-truth correction
 * runs hourly via `recomputeComputerUseQuotaUsage`.
 *
 * Path: `users/{uid}/computer_use_quota_usage/{YYYY-MM-DD}`
 */
export interface ComputerUseQuotaUsageDoc {
  dayKey: string;
  browserActionsExecuted: number;
  browserActionsRejected: number;
  systemActionsExecuted: number;
  systemActionsRejected: number;
  phoneControlIntentsExecuted: number;
  phoneControlIntentsRejected: number;
  sessionsStarted: number;
  sessionsCompleted: number;
  totalSessionSeconds: number;
  visionModelSpendUSD: number;
  updatedAt: import("firebase-admin/firestore").Timestamp;
}

/**
 * Operator-side daily rollup. One per UTC day.
 *
 * Path: `ops/computer_use_session_daily_rollups/days/{YYYY-MM-DD}`
 */
export interface ComputerUseSessionDailyRollupDoc {
  dayKey: string;
  sessionsStarted: number;
  sessionsCompleted: number;
  browserActionsExecuted: number;
  browserActionsRejected: number;
  systemActionsExecuted: number;
  systemActionsRejected: number;
  phoneControlIntents: number;
  scopeViolations: number;
  panicHaltCount: number;
  approvalLatencyP50Millis: number;
  approvalLatencyP95Millis: number;
  approvalLatencyP99Millis: number;
  cappedVisionModelSpendUSD?: number;
  visionModelSpendUSD: number;
  updatedAt: import("firebase-admin/firestore").Timestamp;
}

/**
 * Current envelope. Single doc at `ops/computer_use_budget_status/state/current`.
 */
export interface ComputerUseBudgetStatusDoc {
  level: ComputerUseBudgetLevel;
  projectedMonthEndUSD: number;
  monthToDateUSD: number;
  activeActionsPerRun: number;
  activeActionsPerDay: number;
  activeSessionsPerDay: number;
  perUserDailySpendCeilingUSD: number;
  updatedAt: import("firebase-admin/firestore").Timestamp;
}

/**
 * Entitlement claim. Mirror of the StoreKit entitlement.
 *
 * Path: `users/{uid}/entitlements/hosted_computer_use_sync`
 */
export interface ComputerUseEntitlementDoc {
  active: boolean;
  productID: string;
  expireAt?: import("firebase-admin/firestore").Timestamp;
  features: {
    browserComputerUse: boolean;
    systemComputerUse: boolean;
    phoneControl: boolean;
    auditExport: boolean;
    trustedScopes: boolean;
  };
}

export interface ComputerUseOpenTimestampsValidationRequest {
  uid: string;
  sessionId: string;
  auditHeadHashHex: string;
  proofBase64: string;
  /**
   * Optional original chain file bytes. The official `ots verify` CLI can use
   * the file beside `chain.jsonl.ots` for detached timestamp validation.
   */
  chainFileBase64?: string;
}

export type ComputerUseOpenTimestampsValidationStatus =
  | "verified"
  | "ots_verifier_unavailable"
  | "ots_verify_failed"
  | "session_not_found"
  | "server_head_missing"
  | "head_mismatch";

export interface ComputerUseOpenTimestampsValidationResponse {
  status: ComputerUseOpenTimestampsValidationStatus;
  verified: boolean;
  sessionId: string;
  auditHeadHashHex: string;
  serverAuditHeadHashHex?: string;
  proofSizeBytes: number;
  checkedAt: string;
  otsVerifierOutput?: string;
}

// ---------------------------------------------------------------------------
// Hermes Skill Runs / mobile mission dispatch
// ---------------------------------------------------------------------------

export type HermesSkillRunIDDoc =
  | "what_happened"
  | "burn_forensics"
  | "pattern_miner"
  | "compare_agents"
  | "next_action_coach"
  | "handoff_builder"
  | "regression_watch"
  | "run_pulse";

export type SkillRunDeliveryModeDoc = "action_only" | "full_stream" | "muted";

export type SkillRunEventImportanceDoc = "quiet" | "normal" | "action_required" | "terminal";

export interface CLIAgentMissionEventDoc {
  sequence: number;
  timestamp: string;
  kind:
    | "status"
    | "llm_response"
    | "assistant_message"
    | "tool_call"
    | "tool_result"
    | "error"
    | "approval_request"
    | "artifact"
    | "changed_file"
    | "final_answer";
  phase: string;
  title: string;
  message: string;
  fullMessage?: string;
  messageLength?: number;
  messageTruncated?: boolean;
  runtime?: string;
  source: "ios" | "android" | "ios-chat" | "android-chat" | "mac";
  sourceSkillID?: HermesSkillRunIDDoc;
  deliveryMode?: SkillRunDeliveryModeDoc;
  eventImportance?: SkillRunEventImportanceDoc;
  skillStepID?: string;
  toolName?: string;
  artifactPath?: string;
  changedFilePath?: string;
  isError: boolean;
}

export interface CLIAgentMissionRequestDoc {
  id: string;
  title: string;
  prompt: string;
  missionKind: string;
  requestedRuntime: string;
  requestedModelID?: string;
  targetProject?: string;
  depth?: "light" | "standard" | "deep" | "max";
  approvalMode?: "existing_policy" | "manual_all" | "risky_only" | "read_only";
  commandsAllowed?: boolean;
  fileEditsAllowed?: boolean;
  source: "ios-insights" | "android-insights" | "mac-insights" | "ios-chat" | "android-chat";
  sourceSkillID?: HermesSkillRunIDDoc;
  sourceSurface?: string;
  deliveryMode?: SkillRunDeliveryModeDoc;
  parentHermesThreadID?: string;
  status: string;
  createdAt: string;
  updatedAt: unknown;
  startedAt?: string;
  completedAt?: string;
  claimedBy?: string;
  selectedRuntime?: string;
  selectedRuntimeName?: string;
  selectedModelID?: string;
  sessionId?: string;
  approvalRequestId?: string;
  approvalStatus?: "pending" | "approved" | "rejected" | "canceled" | "cancelled";
  approvalRequestedAt?: string;
  approvalRespondedAt?: string;
  approvalTitle?: string;
  approvalMessage?: string;
  liveSummary?: string;
  events?: CLIAgentMissionEventDoc[];
  resultPreview?: string;
  errorMessage?: string;
  lastEventSequence?: number;
  schemaVersion: number;
  groupID?: string;
  siblingIndex?: number;
  siblingCount?: number;
  isGroupChild?: boolean;
  personaScopeJSON?: string;
  personaID?: string;
  clientThreadID?: string;
  parentSessionID?: string;
  resumeAction?: "new" | "resume" | "fork" | "forward";
}

export interface SubscriptionTopicDoc {
  agentURI: string;
  topicID: string;
  /**
   * Legacy plaintext topic display text. Optional now that the private display
   * strings are vault-sealed into `sealedDisplayName`/`sealedDescription`;
   * readers keep these as a legacy fallback when the sealed copy is absent.
   */
  displayName?: string;
  description?: string;
  /** Vault-sealed topic display text (CloudVaultSealedText envelope). */
  sealedDisplayName?: CloudVaultSealedTextDoc;
  sealedDescription?: CloudVaultSealedTextDoc;
  cadence: "on_demand" | "daily" | "weekly" | "monthly";
  consentGivenAt?: import("firebase-admin/firestore").Timestamp | string | number;
  isMuted: boolean;
  deliveryMode: SkillRunDeliveryModeDoc;
  minimumEventImportance: SkillRunEventImportanceDoc;
  deliveryCountThisMonth: number;
  lastDeliveredAt?: import("firebase-admin/firestore").Timestamp | string | number;
  updatedAt?: import("firebase-admin/firestore").Timestamp;
}
