import Foundation
import OpenBurnBarCore
@testable import OpenBurnBar

// MARK: - Live stream-parse contract format (VAL-P0-STREAM-028)
//
// A portable, deterministic projection of the LIVE CLIBridge stream parser's
// output. Where VAL-P0-HARNESS-024 (`ParserOutputContract`) freezes the on-disk
// *log* parser's `TokenUsage` accounting, this contract freezes the *live*
// `claude --output-format stream-json` → `ClaudeCodeStreamJSONParser` path: the
// ordered `CLIChatStreamEvent`s the shipped parser emits for a real captured
// stream.
//
// The golden pairs two committed artifacts:
//   • `claude-stream-mac-golden.jsonl`        — the RAW stream captured from a
//     real macOS `claude --output-format stream-json` run (never hand-edited).
//   • `claude-stream-mac-golden-events.json`  — the N parsed events (this
//     contract shape) + scenario metadata, regenerated by re-parsing the RAW
//     stream through the shipped parser.
//
// The parse-diff test (`ClaudeStreamGoldenParseDiffTests`) re-parses the RAW
// golden through `ClaudeCodeStreamJSONParser` and asserts the N events equal the
// committed events golden — proving the live CLIBridge→stream→parser path, not a
// static reimplementation. The RAW stream is committed so Windows (STREAM-029)
// can replay it deterministically and diff the identical parsed events.
//
// Design rules that make the projection byte-stable across languages/platforms
// (mirroring the HARNESS-024 philosophy):
//   • Project only the parser's deterministic output — the event kind, text,
//     tool name, and tool detail. Never the raw stream's non-reproducible fields
//     (`session_id`, `uuid`, `duration_ms`, `total_cost_usd`, timestamps): those
//     stay in the RAW `.jsonl` and are ignored by the parser (they project to
//     zero events), which is exactly why the parsed golden is environment-stable
//     while the raw capture is a machine-specific snapshot.
//   • Serialize with sorted keys + stable pretty-printing + a trailing newline so
//     the committed golden is a clean, byte-stable text diff.
//
// The spec lives at `docs/windows-port/STREAM_JSON_MAC_GOLDEN.md`.

/// The token projection for a `.usage` stream event. Claude's stream parser never
/// emits `.usage` (usage arrives on the raw `result` line, which the parser does
/// not project — faithful production behavior), but the contract is total over
/// every `CLIChatStreamEvent` case so a future provider golden (Codex, generic)
/// can reuse the same shape.
struct StreamUsageContractRecord: Codable, Equatable, Hashable {
    let inputTokens: Int
    let outputTokens: Int
    let cacheCreationTokens: Int
    let cacheReadTokens: Int
    let reasoningTokens: Int
    let totalTokens: Int

    init(_ usage: CLIUsageSnapshot) {
        inputTokens = usage.inputTokens
        outputTokens = usage.outputTokens
        cacheCreationTokens = usage.cacheCreationTokens
        cacheReadTokens = usage.cacheReadTokens
        reasoningTokens = usage.reasoningTokens
        totalTokens = usage.totalTokens
    }
}

/// One parsed `CLIChatStreamEvent` projected to the portable, byte-stable
/// contract, tied back to the RAW stream line that produced it.
struct StreamEventContractRecord: Codable, Equatable, Hashable {
    /// Position in the ordered parsed-event sequence (0-based).
    let index: Int
    /// 0-based physical line of the RAW stream (`split("\n")`) this event was
    /// parsed from — the precise raw→parsed map that STREAM-029 replays.
    let sourceLineIndex: Int
    /// `"text"` / `"reasoning"` / `"refusal"` / `"toolUse"` / `"toolResult"` /
    /// `"usage"`.
    let kind: String
    /// Payload for `.text` / `.reasoning` / `.refusal`.
    let text: String?
    /// Tool name for `.toolUse` / `.toolResult`.
    let toolName: String?
    /// Tool detail for `.toolUse` / `.toolResult`.
    let detail: String?
    /// Token projection for `.usage`.
    let usage: StreamUsageContractRecord?

    init(_ event: CLIChatStreamEvent, index: Int, sourceLineIndex: Int) {
        self.index = index
        self.sourceLineIndex = sourceLineIndex
        switch event {
        case .text(let value):
            kind = "text"; text = value; toolName = nil; detail = nil; usage = nil
        case .reasoning(let value):
            kind = "reasoning"; text = value; toolName = nil; detail = nil; usage = nil
        case .refusal(let value):
            kind = "refusal"; text = value; toolName = nil; detail = nil; usage = nil
        case .toolUse(let name, let toolDetail):
            kind = "toolUse"; text = nil; toolName = name; detail = toolDetail; usage = nil
        case .toolResult(let name, let toolDetail):
            kind = "toolResult"; text = nil; toolName = name; detail = toolDetail; usage = nil
        case .usage(let snapshot):
            kind = "usage"; text = nil; toolName = nil; detail = nil
            usage = StreamUsageContractRecord(snapshot)
        case .sessionID(let sessionID):
            kind = "sessionID"; text = sessionID; toolName = nil; detail = nil; usage = nil
        }
    }
}

/// A count of one raw stream event `(type, subtype)` — a self-documenting index
/// of the raw stream's event variety, computed from the committed RAW `.jsonl`.
/// Recomputing it from the committed raw and requiring a match is what keeps the
/// two committed files (raw + events) from silently drifting apart.
struct StreamRawEventKind: Codable, Equatable, Hashable {
    let type: String
    let subtype: String
    let count: Int
}

/// The fixed prompt/scenario the golden was captured from — the reproduction
/// recipe for a fresh Windows capture (STREAM-029 replays the raw bytes; this is
/// for regenerating the raw bytes should that ever be needed).
struct StreamParseScenario: Codable, Equatable {
    let prompt: String
    let marker: String
    let captureCommand: String
    let description: String
}

/// The committed Mac live-stream golden: the parsed events + the scenario +
/// raw-stream consistency metadata.
struct StreamParseGolden: Codable, Equatable {
    /// Bumped when the contract *shape* changes (not when parser output drifts).
    let formatVersion: Int
    /// `AgentProvider.claudeCode.rawValue` — `"Claude Code"`.
    let provider: String
    /// The shipped parser under test — `"ClaudeCodeStreamJSONParser"`.
    let parser: String
    /// The model the scenario pins for reproduction.
    let model: String
    let scenario: StreamParseScenario
    /// Number of non-empty JSON lines in the RAW stream.
    let rawLineCount: Int
    /// Raw event-type histogram (sorted) — documents representative variety.
    let rawEventKinds: [StreamRawEventKind]
    /// N — the number of parsed events (== `events.count`).
    let eventCount: Int
    /// The N parsed events, in stream order.
    let events: [StreamEventContractRecord]
}

// MARK: - Projection + serialization

enum StreamParseContract {
    /// Current on-disk contract shape.
    static let formatVersion = 1

    /// Bundle resource base names for the committed golden pair.
    static let rawResourceName = "claude-stream-mac-golden"
    static let eventsResourceName = "claude-stream-mac-golden-events"

    /// Re-parse the RAW stream through the SHIPPED live parser, projecting each
    /// emitted `CLIChatStreamEvent` (with its source raw-line index) to the
    /// contract. Lines are split on `"\n"` (empties preserved so `sourceLineIndex`
    /// is the physical raw line number) and fed one at a time, exactly as
    /// `CLIProcessStreamRunner` feeds `stdout` lines to `runClaude`'s parse
    /// closure `ClaudeCodeStreamJSONParser.events(fromLine:)`.
    static func parseEvents(fromRaw raw: String) -> [StreamEventContractRecord] {
        var records: [StreamEventContractRecord] = []
        var lineIndex = 0
        for line in raw.split(separator: "\n", omittingEmptySubsequences: false) {
            for event in ClaudeCodeStreamJSONParser.events(fromLine: String(line)) {
                records.append(StreamEventContractRecord(event, index: records.count, sourceLineIndex: lineIndex))
            }
            lineIndex += 1
        }
        return records
    }

    /// The raw event-type histogram (sorted), computed from the RAW stream — a
    /// self-documenting variety index and a raw↔events consistency cross-check.
    static func rawEventKinds(fromRaw raw: String) -> [StreamRawEventKind] {
        var counts: [String: Int] = [:]
        for line in raw.split(separator: "\n", omittingEmptySubsequences: true) {
            guard let data = line.data(using: .utf8),
                  let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else { // try?-ok(non-JSON raw line skipped)
                continue
            }
            let type = (obj["type"] as? String) ?? ""
            let subtype = (obj["subtype"] as? String) ?? ""
            counts["\(type)\u{1F}\(subtype)", default: 0] += 1
        }
        return counts.map { key, count in
            let parts = key.components(separatedBy: "\u{1F}")
            return StreamRawEventKind(type: parts[0], subtype: parts.count > 1 ? parts[1] : "", count: count)
        }
        .sorted { ($0.type, $0.subtype) < ($1.type, $1.subtype) }
    }

    /// Number of non-empty JSON lines in the RAW stream.
    static func nonEmptyLineCount(_ raw: String) -> Int {
        raw.split(separator: "\n", omittingEmptySubsequences: true).count
    }

    /// Build the golden by re-parsing the RAW stream through the shipped parser.
    static func golden(fromRaw raw: String, scenario: StreamParseScenario,
                       provider: String, parser: String, model: String) -> StreamParseGolden {
        let events = parseEvents(fromRaw: raw)
        return StreamParseGolden(
            formatVersion: formatVersion,
            provider: provider,
            parser: parser,
            model: model,
            scenario: scenario,
            rawLineCount: nonEmptyLineCount(raw),
            rawEventKinds: rawEventKinds(fromRaw: raw),
            eventCount: events.count,
            events: events
        )
    }

    /// Canonical text encoding (sorted keys + stable pretty-print), terminated by
    /// a trailing newline so the committed file is a clean diff.
    static func encode(_ golden: StreamParseGolden) throws -> Data {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        var data = try encoder.encode(golden)
        data.append(0x0A)
        return data
    }

    static func decode(_ data: Data) throws -> StreamParseGolden {
        try JSONDecoder().decode(StreamParseGolden.self, from: data)
    }

    /// Locate a committed golden-pair resource in the flattened test bundle.
    static func bundledURL(resource: String, ext: String, bundle: Bundle) -> URL? {
        bundle.url(forResource: resource, withExtension: ext)
            ?? bundle.url(forResource: resource, withExtension: ext, subdirectory: "StreamGolden")
            ?? bundle.url(forResource: resource, withExtension: ext, subdirectory: "Fixtures/StreamGolden")
    }
}
