import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import zlib from "node:zlib";
import { captureP15AccountBillingProof } from "./capture-p15-account-billing-proof.mjs";
import { pngCrc32 } from "./lib/installed-ui-proof.mjs";
import { canonicalJsonBytes, createInstalledManifest, signInstalledManifest } from "./lib/linux-installed-manifest.mjs";
import { validateP15InstalledSession, validateP15Proof } from "./lib/p15-account-billing-proof.mjs";
import { materializeP15AccountBillingSession } from "./materialize-p15-account-billing-session.mjs";
import { runP15AccountBillingWorkflow } from "./run-p15-native-account-billing-probes.mjs";

const HEAD = "1".repeat(40); const RUN = "151515"; const DIGEST = `sha256:${"2".repeat(64)}`; const ENVIRONMENT = "ubuntu-24.04-gnome-x11-x86_64"; const VERSION = "1.2.3";
function hash(bytes) { return crypto.createHash("sha256").update(bytes).digest("hex"); }
function write(file, bytes, mode = 0o600) { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, bytes); fs.chmodSync(file, mode); return file; }
function json(file, value) { return write(file, `${JSON.stringify(value, null, 2)}\n`); }
function record(root, file) { const bytes = fs.readFileSync(file); return { path: path.relative(root, file).split(path.sep).join("/"), sha256: hash(bytes), size: bytes.length }; }
function chunk(type, data) { const name = Buffer.from(type); const output = Buffer.alloc(data.length + 12); output.writeUInt32BE(data.length); name.copy(output, 4); data.copy(output, 8); output.writeUInt32BE(pngCrc32(Buffer.concat([name, data])), data.length + 8); return output; }
function png(seed) { const width = 320; const height = 220; const header = Buffer.alloc(13); header.writeUInt32BE(width); header.writeUInt32BE(height, 4); header[8] = 8; header[9] = 2; const raw = Buffer.alloc((width * 3 + 1) * height); for (let y = 0; y < height; y += 1) for (let x = 0; x < width; x += 1) { const at = y * (width * 3 + 1) + 1 + x * 3; raw[at] = (x + seed * 17) % 256; raw[at + 1] = (y + seed * 29) % 256; raw[at + 2] = (x + y + seed * 41) % 256; } return Buffer.concat([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), chunk("IHDR", header), chunk("IDAT", zlib.deflateSync(raw, { level: 0 })), chunk("IEND", Buffer.alloc(0))]); }
function attestation(root, directory) { const { privateKey, publicKey } = crypto.generateKeyPairSync("ed25519"); const privatePem = privateKey.export({ type: "pkcs8", format: "pem" }); const publicPem = publicKey.export({ type: "spki", format: "pem" }); write(path.join(root, "packaging/linux/openburnbar-linux-ed25519.pub.pem"), publicPem); const item = (installedPath, bytes, mode) => ({ path: installedPath, type: "file", sha256: hash(bytes), size: bytes.length, mode, uid: 0, gid: 0 }); const manifest = canonicalJsonBytes(createInstalledManifest({ files: [item("/usr/bin/openburnbar-daemon", Buffer.from("daemon"), "0755"), item("/usr/bin/openburnbar-linux-desktop", Buffer.from("desktop"), "0755"), item("/usr/share/openburnbar/attestation/release-ed25519.pub.pem", publicPem, "0644")], packageVersion: VERSION, gitCommit: HEAD, packageArchitecture: "x86_64", packageFormat: "deb", firebaseAppId: "1:2:web:3" })); const signature = signInstalledManifest(manifest, privatePem, publicPem); return { manifestPath: write(path.join(directory, "installed-manifest.json"), manifest), signaturePath: write(path.join(directory, "installed-manifest.json.sig"), signature), manifestSha256: hash(manifest), manifestSignatureSha256: hash(signature) }; }
function options(root) { return { rawOutputDir: path.join(root, "live/raw"), stateHome: path.join(root, "live/home"), environmentId: ENVIRONMENT, targetHead: HEAD, candidateRunId: RUN, candidateArtifactDigest: DIGEST, packageVersion: VERSION, manifestSha256: "0".repeat(64), manifestSignatureSha256: "0".repeat(64), architecture: "x86_64", packageFormat: "deb", compositor: "Mutter", desktop: "GNOME", displayServer: "X11" }; }
function fakeDependencies(overrides = {}) { let daemon = false; let launched = false; let restored = 0; const account = { state: "signed-out", signedIn: false, trustClass: "linux-lower-trust", syncState: "local-only", deviceApprovalRequired: false }; const expected = { initial: "Identity and sync", action: "Membership", degraded: "Account and sync status need", recovered: "Local-first" }; return { platform: "linux", desktopSession: true, installedVerifier() {}, marker: "p15-0123456789abcdef", nonce: "3".repeat(32), identity: () => ({ packageManager: "dpkg", packageName: "open-burn-bar", packageOwned: true }), desktopPids: () => [], daemonActive: () => daemon, async setDaemonActive(value) { daemon = value; }, async launch() { launched = true; }, accountStatus: async () => account, membershipStatus: async () => ({ tier: "free", entitlements: [], restoreAvailable: true }), checkout: async () => ({ outcome: "fail-closed", host: null, paymentCredentialsCollected: false }), authCycle: async () => ({ attempted: true, allowlistedAuthorization: true, loopbackRedirect: true, stateLength: 43, cancelObserved: true, browserCredentialsCollected: false }), invalidCloudDelete: async () => true, async reload() {}, refresh: async (healthy) => ({ healthy, visible: true, attemptCount: 1 }), async capture(state, name, accessibility, image) { assert.equal(launched, true); assert.equal(name, expected[state]); write(image, png({ initial: 1, action: 2, degraded: 3, recovered: 4 }[state])); json(accessibility, { schemaVersion: 1, capturedAt: new Date().toISOString(), application: "OpenBurnBar", route: "account", expectedName: name, expectedNamePresent: true, nodeCount: 30, namedNodeCount: 15, actionableNodeCount: 5, focusableNodeCount: 5, focusedNodes: [], roleCounts: { button: 5 }, namedSamples: [], actionableSamples: [], truncated: false, minimums: { nodes: 12, named: 6, actionable: 1 }, pass: true, failures: [], readinessAttempts: 1 }); }, async terminate() {}, async restoreState() { restored += 1; }, restored: () => restored, ...overrides }; }
async function fixture() { const base = path.join(process.cwd(), ".tmp/p15-proof-tests"); fs.mkdirSync(base, { recursive: true }); const root = fs.mkdtempSync(path.join(base, "case-")); const opts = options(root); const identity = attestation(root, path.join(root, "attestation")); Object.assign(opts, identity); const deps = fakeDependencies(); const result = await runP15AccountBillingWorkflow(opts, deps); const input = path.join(root, "docs/linux-port/evidence/product-parity-inputs/P-15", ENVIRONMENT); fs.mkdirSync(input, { recursive: true }); const materialized = materializeP15AccountBillingSession({ ...opts, repoRoot: root, outputRoot: input, rawEvidenceDir: result.rawOutputDir }, { installedVerifier() {}, manifestPath: identity.manifestPath, signaturePath: identity.signaturePath }); return { root, opts, deps, input, session: materialized.document, sessionFile: materialized.output }; }
function binding(value) { return { ...value.opts, repoRoot: value.root, candidateRunId: RUN }; }
function refresh(value, field, file) { value.session.evidence[field] = record(value.root, file); }

test("P-15 production contract proves account, external billing, degraded recovery, and restoration", async () => { const value = await fixture(); try { assert.equal(value.deps.restored(), 1); assert.equal(validateP15InstalledSession(value.session, binding(value)).document.requirementId, "P-15"); const captured = captureP15AccountBillingProof({ ...binding(value), inputRoot: value.input, sessionReport: value.sessionFile }, { resolveHead: () => HEAD, now: () => new Date() }); assert.equal(captured.document.claim.safeExternalBilling, true); validateP15Proof({ ...binding(value), snapshot: { bytes: fs.readFileSync(captured.output) } }); assert.throws(() => validateP15Proof({ ...binding(value), manifestSha256: "f".repeat(64), snapshot: { bytes: fs.readFileSync(captured.output) } }), /P-15/u); } finally { fs.rmSync(value.root, { recursive: true, force: true }); } });

test("P-15 rejects secret leakage, stale/replayed receipts, unsafe checkout, optimistic recovery, forged provenance, and failed restoration", async () => { const mutations = [(value, native) => { native.account.initial.detail = "access_token=leaked"; }, (_value, native) => { native.startedAt = "2020-01-01T00:00:00.000Z"; }, (value, native) => { value.session.marker.challenge = "f".repeat(64); native.challenge = value.session.marker.challenge; }, (_value, native) => { native.billing.checkout = { outcome: "allowlisted-url", host: "evil.example", paymentCredentialsCollected: false }; }, (_value, native) => { native.degradation.optimisticSuccess = true; }, (value) => { value.session.marker.package.format = "rpm"; }, (_value, native) => { native.auth.browserCredentialsCollected = true; }, (_value, native) => { native.restoration.isolatedStateRestored = false; }]; for (const mutate of mutations) { const value = await fixture(); try { const nativeFile = path.join(value.root, value.session.evidence.nativeTranscript.path); const native = JSON.parse(fs.readFileSync(nativeFile)); mutate(value, native); json(nativeFile, native); refresh(value, "nativeTranscript", nativeFile); assert.throws(() => validateP15InstalledSession(value.session, binding(value)), /P-15/u); } finally { fs.rmSync(value.root, { recursive: true, force: true }); } } });

test("P-15 workflow fails closed and aggregates restoration failure", async () => { const root = fs.mkdtempSync(path.join(process.cwd(), ".tmp/p15-workflow-")); const opts = options(root); try { const deps = fakeDependencies({ checkout: async () => ({ outcome: "allowlisted-url", host: "evil.example", paymentCredentialsCollected: true }), async restoreState() { throw new Error("forced restoration failure"); } }); await assert.rejects(() => runP15AccountBillingWorkflow(opts, deps), (error) => error instanceof AggregateError && error.errors.length === 2); } finally { fs.rmSync(root, { recursive: true, force: true }); } });
