#!/usr/bin/env node
/**
 * P3-G9 one-time generator: turns the proven schema + extracted behavior into the
 * real source files that replace the hand-written HermesRealtimeRelayTypes.swift:
 *
 *   SharedModels/Generated/HermesRealtimeRelay<Domain>.swift   (generated data+Codable)
 *   SharedModels/HermesRealtimeRelayTypes+Behavior.swift       (hand-written henceforth:
 *       the HermesRealtimeRelayProtocol namespace, the shared DateCodec helper widened
 *       to module-internal, and every behavior member as an extension)
 *
 * The generated files are byte-equivalent (data+Codable) to the original, proven by
 * roundtrip.mjs. This script writes them; codegen.mjs owns regeneration thereafter.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildModel } from "./roundtrip.mjs";
import { emitSwiftType } from "./emit-swift-types.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const SHARED = join(HERE, "..", "..", "..", "OpenBurnBarCore", "Sources", "OpenBurnBarCore", "SharedModels");
const GENDIR = join(SHARED, "Generated");

const GEN_HEADER = (domain) =>
  `// GENERATED by packages/hermes-wire-protocol/codegen.mjs — DO NOT EDIT.\n` +
  `// Source of truth: packages/hermes-wire-protocol/relay-message-types.json. Run \`node codegen.mjs\`.\n` +
  `//\n// Hermes realtime-relay payload types — ${domain} domain. The wire contract is\n` +
  `// schema-locked across Swift / Kotlin so iOS·macOS ↔ Android can never drift.\n` +
  `// Behavior (computed members, factories) lives in HermesRealtimeRelayTypes+Behavior.swift.\n\n` +
  `import Foundation\n`;

function domainOf(name) {
  if (/RemoteUnlock|MacLockState/.test(name)) return "RemoteUnlock";
  if (/SystemPermission/.test(name)) return "SystemPermission";
  if (/Payload$|ErrorCode$|AgentContextTarget$/.test(name)) return "Envelope";
  if (/Media|Focus|Normalized|Mirror|Call|LongTermReference|PresenceHeartbeat|VideoCodec|Datagram|Streaming|AttachmentManifest|AgentTerminal/.test(name)) return "Media";
  return "Control";
}

function docLines(trivia) {
  return (trivia || []).filter((l) => { const t = l.trim(); return t.startsWith("///") || (t.startsWith("//") && !t.startsWith("// MARK")); });
}

function main() {
  const { types } = buildModel();
  mkdirSync(GENDIR, { recursive: true });

  // ── 1. generated data+Codable, domain-split ──
  const dataTypes = types.filter((t) => !t.priv && !(t.kind === "enum" && t.namespace));
  const byDomain = {};
  for (const t of dataTypes) {
    const dom = domainOf(t.name);
    (byDomain[dom] ??= []).push(t);
  }
  let genCount = 0;
  for (const [dom, ts] of Object.entries(byDomain)) {
    const body = ts.map((t) => {
      const doc = docLines(t.trivia);
      return (doc.length ? doc.join("\n") + "\n" : "") + emitSwiftType(t);
    }).join("\n\n");
    writeFileSync(join(GENDIR, `HermesRealtimeRelay${dom}.swift`), GEN_HEADER(dom) + "\n" + body + "\n");
    genCount += ts.length;
  }

  // ── 2. hand-written behavior + helpers ──
  const namespaceEnum = types.find((t) => t.kind === "enum" && t.namespace);
  const dateCodec = types.find((t) => t.priv);
  const behaviorParts = [];
  for (const t of dataTypes) {
    if (!t.behavior || !t.behavior.length) continue;
    const ext = [`extension ${t.name} {`];
    t.behavior.forEach((b, i) => {
      if (i > 0) ext.push("");
      for (const tl of docLines(b.trivia)) ext.push(tl);
      for (const l of b.lines) ext.push(l);
    });
    ext.push("}");
    behaviorParts.push(ext.join("\n"));
  }

  const behaviorFile = [
    "// Hand-written companion to the generated Hermes relay payload types.",
    "//",
    "// Holds the pieces a schema does not own: the protocol-constants namespace, the",
    "// shared ISO-8601 date codec (used by the generated Codable conformances), and",
    "// every behavior member (computed properties, factories) as an extension on its",
    "// generated type. The data shapes themselves are generated from",
    "// packages/hermes-wire-protocol/relay-message-types.json.",
    "",
    "import Foundation",
    "",
    namespaceEnum.raw.join("\n"),
    "",
    "// Widened from `private` to module-`internal` during the schema migration so the",
    "// generated payload types (in Generated/) can share one date (de)serializer.",
    dateCodec.raw.join("\n").replace(/^private enum /m, "enum "),
    "",
    ...behaviorParts,
    "",
  ].join("\n");
  writeFileSync(join(SHARED, "HermesRealtimeRelayTypes+Behavior.swift"), behaviorFile);

  console.log(`generated ${genCount} payload types across ${Object.keys(byDomain).length} domain files: ${Object.keys(byDomain).join(", ")}`);
  console.log(`behavior extensions: ${behaviorParts.length} types; namespace + DateCodec carried into +Behavior.swift`);
}

main();
