package com.openburnbar.data.cloud.signalsession

import java.util.Base64
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Test
import org.signal.libsignal.protocol.IdentityKeyPair
import org.signal.libsignal.protocol.SessionCipher
import org.signal.libsignal.protocol.SignalProtocolAddress
import org.signal.libsignal.protocol.message.CiphertextMessage
import org.signal.libsignal.protocol.message.PreKeySignalMessage
import org.signal.libsignal.protocol.state.KyberPreKeyRecord
import org.signal.libsignal.protocol.state.PreKeyRecord
import org.signal.libsignal.protocol.state.SignedPreKeyRecord

/**
 * Phase 2.5 G1 — Android self-consistency guard on the reverse interop fixture
 * (`/signal-interop/android-alice-to-swift-bob.json`, generated by [AndroidSignalInteropFixtureGen]).
 * Reconstructs Bob from the committed key material and decrypts BOTH committed PreKey messages,
 * proving the committed Android-Alice bytes are valid before the Swift `OBBSignalInteropKatTests`
 * opens the same fixture cross-language. A regression that re-emits a broken fixture fails here on
 * the Android side before it can break the Swift lane.
 */
class AndroidSignalReverseInteropKatTest {

    private fun b64(s: String): ByteArray = Base64.getDecoder().decode(s)

    @Test
    fun bobDecryptsAndroidAlicePreKeyAndChainAdvancedMessage() {
        val raw = javaClass.getResourceAsStream("/signal-interop/android-alice-to-swift-bob.json")
            ?.readBytes()?.toString(Charsets.UTF_8)
            ?: error("reverse interop fixture not found on the test classpath")
        val fx = JSONObject(raw)

        assertEquals("android-alice-to-swift-bob", fx.getString("direction"))
        assertEquals(CiphertextMessage.PREKEY_TYPE, fx.getInt("ciphertextType"))

        // Reconstruct Bob's store from the committed key material.
        val bobIdentity = IdentityKeyPair(b64(fx.getString("bobIdentityKeyPairB64")))
        val bob = AndroidSignalProtocolStore.testingTOFU(
            bobIdentity,
            fx.getInt("bobRegistrationId"),
            InMemorySignalRecordVault(),
        )
        bob.storePreKey(fx.getInt("bobPreKeyId"), PreKeyRecord(b64(fx.getString("bobPreKeyRecordB64"))))
        bob.storeSignedPreKey(fx.getInt("bobSignedPreKeyId"), SignedPreKeyRecord(b64(fx.getString("bobSignedPreKeyRecordB64"))))
        bob.storeKyberPreKey(fx.getInt("bobKyberPreKeyId"), KyberPreKeyRecord(b64(fx.getString("bobKyberPreKeyRecordB64"))))

        val deviceId = fx.getInt("deviceId")
        val aliceAddress = SignalProtocolAddress(fx.getString("aliceAddressName"), deviceId)
        val bobAddress = SignalProtocolAddress(fx.getString("bobAddressName"), deviceId)

        // Bob (local) decrypts Alice's (remote) PreKey messages — SessionCipher(store, LOCAL, REMOTE).
        val cipher = SessionCipher(bob, bobAddress, aliceAddress)
        val first = cipher.decrypt(PreKeySignalMessage(b64(fx.getString("ciphertextB64"))))
        assertEquals(fx.getString("expectedPlaintext"), String(first, Charsets.UTF_8))

        assertEquals(CiphertextMessage.PREKEY_TYPE, fx.getInt("secondCiphertextType"))
        val second = cipher.decrypt(PreKeySignalMessage(b64(fx.getString("secondCiphertextB64"))))
        assertEquals(fx.getString("secondExpectedPlaintext"), String(second, Charsets.UTF_8))
    }
}
