#!/usr/bin/env node
/**
 * Codegen for the Hermes/iroh realtime wire protocol.
 *
 * Reads protocol.json (the single source of truth) and emits typed, identical
 * frame-type + wire-constant definitions for every platform that speaks the
 * protocol, so a frame type or wire constant is defined ONCE and can never
 * drift across languages:
 *
 *   services/hermes-realtime-relay/src/generated/wireProtocol.ts  — CONSUMED by
 *       the Cloud Run relay's protocol.ts (relay-accepted subset + constants).
 *   gen/HermesWireProtocol.swift  — reference for OpenBurnBarCore's hand-written
 *       HermesRealtimeRelayFrameType (locked to it by the parity gate).
 *   gen/HermesWireProtocol.kt     — reference for android/openburnbar-iroh-relay.
 *   gen/wire_protocol.rs          — reference for crates/openburnbar-iroh constants.
 *
 * Enforcement (see parity.mjs + protocol.test.mjs, wired into fast-feedback's
 * schema-drift gate):
 *   1. DRIFT GATE — regenerate and assert the on-disk generated files are current.
 *   2. PARITY GATE — parse every hand-written surface (Swift/Kotlin enums, the TS
 *      relay set, the Rust constants) and assert its frame set + wire strings +
 *      constants equal this file. Drift in any language fails CI.
 *
 * The 9-vs-41 split is intentional, not drift: only the `relayAccepted` frames
 * are validated/multiplexed by the legacy Cloud Run WebSocket relay; the other
 * 32 are peer-to-peer over iroh and never reach the relay. This file records
 * which is which so the relay's accepted set is DERIVED, never hand-maintained.
 *
 * Pure Node, no dependencies. Run: node codegen.mjs
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadRelayTypes, validateRelayTypes, emitSwiftRelayTypes, emitKotlinRelayTypes, loadKotlinOverrides } from "./relay-types.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const GEN = join(HERE, "gen");
const RELAY_TS_PATH = join(
  HERE,
  "..",
  "..",
  "services",
  "hermes-realtime-relay",
  "src",
  "generated",
  "wireProtocol.ts",
);

export function loadProtocol() {
  return JSON.parse(readFileSync(join(HERE, "protocol.json"), "utf8"));
}

/** Validate the protocol shape; throw on any structural problem (also used by the test). */
export function validateProtocol(proto) {
  const errors = [];
  if (proto.schemaVersion !== 1) errors.push(`schemaVersion must be 1, got ${proto.schemaVersion}`);
  const p = proto.protocol ?? {};
  for (const key of [
    "version",
    "realtimeCapability",
    "irohCapability",
    "alpn",
    "maxFrameBytes",
    "lengthPrefixBytes",
    "roleHeaderName",
    "hostRoleHeaderValue",
    "clientRoleHeaderValue",
  ]) {
    if (p[key] === undefined || p[key] === null) errors.push(`protocol.${key} is required`);
  }
  if (p.lengthPrefixEndian !== "big") errors.push(`protocol.lengthPrefixEndian must be "big", got ${p.lengthPrefixEndian}`);
  const groupIds = new Set((proto.groups ?? []).map((g) => g.id));
  if (!Array.isArray(proto.frames) || proto.frames.length === 0) errors.push("frames must be a non-empty array");
  const ids = new Set();
  const wires = new Set();
  for (const f of proto.frames ?? []) {
    if (!f.id || ids.has(f.id)) errors.push(`duplicate or missing frame id: ${f.id}`);
    ids.add(f.id);
    if (!f.wire || wires.has(f.wire)) errors.push(`duplicate or missing frame wire: ${f.wire}`);
    wires.add(f.wire);
    if (!/^[a-z][A-Za-z0-9]*$/.test(f.id ?? "")) errors.push(`frame id must be lowerCamelCase: ${f.id}`);
    if (typeof f.relayAccepted !== "boolean") errors.push(`${f.id}: relayAccepted must be a boolean`);
    if (!groupIds.has(f.group)) errors.push(`${f.id}: unknown group ${f.group}`);
    if (f.implicitSwiftRawValue && f.wire !== f.id) {
      errors.push(`${f.id}: implicitSwiftRawValue requires wire === id (got ${f.wire})`);
    }
  }
  if (errors.length) throw new Error(`protocol.json invalid:\n  - ${errors.join("\n  - ")}`);
  return proto;
}

// ── helpers ──────────────────────────────────────────────────────────────────

function esc(s) {
  return String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/** lowerCamelCase frame id -> SCREAMING_SNAKE_CASE Kotlin enum constant. */
export function screamingSnake(id) {
  return id.replace(/([A-Z])/g, "_$1").toUpperCase();
}

const RELAY_TS_HEADER =
  "// GENERATED by packages/hermes-wire-protocol/codegen.mjs — DO NOT EDIT.\n" +
  "// Source: packages/hermes-wire-protocol/protocol.json. Run `node codegen.mjs`.";

const REF_HEADER =
  "// GENERATED by packages/hermes-wire-protocol/codegen.mjs — DO NOT EDIT. Source: protocol.json.";

function relayFrames(proto) {
  return proto.frames.filter((f) => f.relayAccepted);
}

// ── TypeScript (consumed by the relay) ───────────────────────────────────────

function emitTs(proto) {
  const p = proto.protocol;
  const all = proto.frames;
  const relay = relayFrames(proto);
  const union = (frames) => frames.map((f) => `  | "${esc(f.wire)}"`).join("\n");
  const arr = (frames) => frames.map((f) => `  "${esc(f.wire)}",`).join("\n");

  return [
    RELAY_TS_HEADER,
    "//",
    "// The Hermes/iroh realtime wire protocol, generated for the Cloud Run relay.",
    "// HERMES_* = the FULL peer-to-peer protocol (Swift + Kotlin enums mirror it).",
    "// RELAY_ACCEPTED_* = the subset this relay validates and multiplexes; the rest",
    "// are iroh-only (peer-to-peer) and never reach the relay.",
    "",
    `export const HERMES_PROTOCOL_VERSION = ${p.version} as const;`,
    `export const HERMES_REALTIME_CAPABILITY = "${esc(p.realtimeCapability)}" as const;`,
    `export const HERMES_IROH_CAPABILITY = "${esc(p.irohCapability)}" as const;`,
    `export const HERMES_ALPN = "${esc(p.alpn)}" as const;`,
    `export const HERMES_MAX_FRAME_BYTES = ${p.maxFrameBytes} as const;`,
    `export const HERMES_LENGTH_PREFIX_BYTES = ${p.lengthPrefixBytes} as const;`,
    `export const HERMES_ROLE_HEADER_NAME = "${esc(p.roleHeaderName)}" as const;`,
    `export const HERMES_HOST_ROLE_HEADER_VALUE = "${esc(p.hostRoleHeaderValue)}" as const;`,
    `export const HERMES_CLIENT_ROLE_HEADER_VALUE = "${esc(p.clientRoleHeaderValue)}" as const;`,
    "",
    `/** Every frame type in the protocol (${all.length} total). */`,
    "export type HermesFrameType =",
    `${union(all)};`,
    "",
    "export const HERMES_FRAME_TYPES: readonly HermesFrameType[] = [",
    `${arr(all)}`,
    "];",
    "",
    `/** The ${relay.length} frame types the Cloud Run WebSocket relay validates and multiplexes. */`,
    "export type RelayAcceptedFrameType =",
    `${union(relay)};`,
    "",
    "export const RELAY_ACCEPTED_FRAME_TYPES: readonly RelayAcceptedFrameType[] = [",
    `${arr(relay)}`,
    "];",
    "",
  ].join("\n");
}

// ── Swift (reference for OpenBurnBarCore) ────────────────────────────────────

function emitSwift(proto) {
  const p = proto.protocol;
  const out = [REF_HEADER, "", "import Foundation", ""];
  out.push("public enum HermesRealtimeRelayProtocol {");
  out.push(`    public static let version = ${p.version}`);
  out.push(`    public static let capability = "${esc(p.realtimeCapability)}"`);
  out.push(`    public static let defaultHostedRelayURLString = "${esc(p.defaultHostedRelayURLString ?? "")}"`);
  out.push(`    public static let roleHeaderName = "${esc(p.roleHeaderName)}"`);
  out.push(`    public static let hostRoleHeaderValue = "${esc(p.hostRoleHeaderValue)}"`);
  out.push(`    public static let clientRoleHeaderValue = "${esc(p.clientRoleHeaderValue)}"`);
  out.push("}");
  out.push("");
  out.push("public enum HermesRealtimeRelayFrameType: String, Codable, Sendable, Equatable {");
  let lastGroup = null;
  for (const f of proto.frames) {
    if (f.group !== lastGroup) {
      const g = proto.groups.find((x) => x.id === f.group);
      out.push(`    // ${g ? g.title : f.group}`);
      lastGroup = f.group;
    }
    if (f.doc) out.push(`    /// ${f.doc}`);
    if (f.implicitSwiftRawValue) {
      out.push(`    case ${f.id}`);
    } else {
      out.push(`    case ${f.id} = "${esc(f.wire)}"`);
    }
  }
  out.push("}");
  out.push("");
  return out.join("\n");
}

// ── Kotlin (reference for android/openburnbar-iroh-relay) ────────────────────

function emitKotlin(proto) {
  const p = proto.protocol;
  const out = [REF_HEADER, "", "package com.openburnbar.irohrelay", "", "import kotlinx.serialization.SerialName", "import kotlinx.serialization.Serializable", ""];
  out.push("object HermesRealtimeRelayProtocol {");
  out.push(`    const val VERSION: Int = ${p.version}`);
  out.push(`    const val CAPABILITY: String = "${esc(p.realtimeCapability)}"`);
  out.push(`    const val ROLE_HEADER_NAME: String = "${esc(p.roleHeaderName)}"`);
  out.push(`    const val HOST_ROLE_HEADER_VALUE: String = "${esc(p.hostRoleHeaderValue)}"`);
  out.push(`    const val CLIENT_ROLE_HEADER_VALUE: String = "${esc(p.clientRoleHeaderValue)}"`);
  out.push("}");
  out.push("");
  out.push("@Serializable");
  out.push("enum class HermesRealtimeRelayFrameType {");
  let lastGroup = null;
  const lines = [];
  for (const f of proto.frames) {
    if (f.group !== lastGroup) {
      const g = proto.groups.find((x) => x.id === f.group);
      lines.push(`    // ${g ? g.title : f.group}`);
      lastGroup = f.group;
    }
    if (f.doc) lines.push(`    /** ${f.doc} */`);
    lines.push(`    @SerialName("${esc(f.wire)}")`);
    lines.push(`    ${screamingSnake(f.id)},`);
  }
  out.push(lines.join("\n"));
  out.push("}");
  out.push("");
  return out.join("\n");
}

// ── Rust (reference for crates/openburnbar-iroh) ─────────────────────────────

function emitRust(proto) {
  const p = proto.protocol;
  const out = [REF_HEADER.replace("//", "//!"), "//!", "//! iroh transport wire constants, generated from the canonical protocol.", ""];
  out.push(`/// QUIC ALPN shared by Mac + iOS + Android.`);
  out.push(`pub const OPENBURNBAR_ALPN: &[u8] = b"${esc(p.alpn)}";`);
  out.push("");
  out.push(`/// Maximum length-prefix value accepted on inbound frames (${p.maxFrameBytes} bytes).`);
  out.push(`pub const OPENBURNBAR_MAX_FRAME_BYTES: usize = ${p.maxFrameBytes};`);
  out.push("");
  out.push(`/// Big-endian u32 length prefix width, in bytes.`);
  out.push(`pub const OPENBURNBAR_LENGTH_PREFIX_BYTES: usize = ${p.lengthPrefixBytes};`);
  out.push("");
  out.push(`/// Frame schema version carried in every HermesRealtimeRelayFrame.`);
  out.push(`pub const OPENBURNBAR_IROH_PROTOCOL_VERSION: u32 = ${p.version};`);
  out.push("");
  return out.join("\n");
}

export function generateAll(proto, relayTypes) {
  return {
    [RELAY_TS_PATH]: emitTs(proto),
    [join(GEN, "HermesWireProtocol.swift")]: emitSwift(proto),
    [join(GEN, "HermesWireProtocol.kt")]: emitKotlin(proto),
    [join(GEN, "wire_protocol.rs")]: emitRust(proto),
    // Rich relay PAYLOAD types — the second source-of-truth file, generated and
    // CONSUMED by OpenBurnBarCore (the hand-written monolith was retired). Rust
    // is intentionally absent: it carries frames as opaque bytes, no payload types.
    ...emitSwiftRelayTypes(relayTypes),
    // Kotlin (android/openburnbar-iroh-relay) — same schema, kotlinx.serialization.
    // Byte-faithful generate-and-consume of the types whose schema field-set matches
    // Kotlin's; drift types (date-regime, additive, dual-key) stay hand-written.
    ...emitKotlinRelayTypes(relayTypes, loadKotlinOverrides()),
  };
}

function main() {
  const proto = validateProtocol(loadProtocol());
  const relayTypes = validateRelayTypes(loadRelayTypes());
  mkdirSync(GEN, { recursive: true });
  mkdirSync(dirname(RELAY_TS_PATH), { recursive: true });
  const files = generateAll(proto, relayTypes);
  for (const [abs, content] of Object.entries(files)) {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content);
  }
  console.log(
    `[hermes-wire-protocol] generated ${Object.keys(files).length} files: ${proto.frames.length} frame types ` +
      `(${relayFrames(proto).length} relay-accepted) + ${relayTypes.types.length} relay payload types across 5 Swift domain files.`,
  );
}

if (import.meta.url === `file://${process.argv[1]}`) main();
