#!/usr/bin/env bash
set -euo pipefail

PROJECT_ID="${PROJECT_ID:?Set PROJECT_ID to the BurnBar Firebase/GCP project id}"
REGION="${REGION:-us-central1}"
SERVICE_NAME="${SERVICE_NAME:-hermes-realtime-relay}"
REDIS_URL="${REDIS_URL:?Set REDIS_URL, for example redis://10.0.0.3:6379}"
DEPLOY_PROFILE="${DEPLOY_PROFILE:-prod-safe}"
REQUEST_TIMEOUT_SECONDS="${REQUEST_TIMEOUT_SECONDS:-3600}"
SESSION_AFFINITY="${SESSION_AFFINITY:-true}"
SERVICE_ACCOUNT="${SERVICE_ACCOUNT:-}"
VPC_CONNECTOR="${VPC_CONNECTOR:-}"
DIRECT_VPC_NETWORK="${DIRECT_VPC_NETWORK:-}"
DIRECT_VPC_SUBNET="${DIRECT_VPC_SUBNET:-}"
DIRECT_VPC_TAGS="${DIRECT_VPC_TAGS:-}"
VPC_EGRESS="${VPC_EGRESS:-private-ranges-only}"
HOSTED_RELAY_PRODUCT_IDS="${HOSTED_RELAY_PRODUCT_IDS:-${HOSTED_QUOTA_PRODUCT_ID:-com.openburnbar.hostedQuotaSync.monthly}}"
ENFORCE_APP_CHECK="${ENFORCE_APP_CHECK:-true}"
VERIFY_REVOKED_ID_TOKENS="${VERIFY_REVOKED_ID_TOKENS:-false}"
APP_CHECK_ALLOWED_APP_IDS="${APP_CHECK_ALLOWED_APP_IDS:-}"

case "${DEPLOY_PROFILE}" in
  staging-cheap)
    MIN_INSTANCES="${MIN_INSTANCES:-0}"
    MAX_INSTANCES="${MAX_INSTANCES:-2}"
    CONCURRENCY="${CONCURRENCY:-300}"
    CPU="${CPU:-1}"
    MEMORY="${MEMORY:-256Mi}"
    ;;
  prod-safe)
    MIN_INSTANCES="${MIN_INSTANCES:-1}"
    MAX_INSTANCES="${MAX_INSTANCES:-10}"
    CONCURRENCY="${CONCURRENCY:-500}"
    CPU="${CPU:-1}"
    MEMORY="${MEMORY:-512Mi}"
    ;;
  prod-scale)
    MIN_INSTANCES="${MIN_INSTANCES:-2}"
    MAX_INSTANCES="${MAX_INSTANCES:-50}"
    CONCURRENCY="${CONCURRENCY:-800}"
    CPU="${CPU:-1}"
    MEMORY="${MEMORY:-768Mi}"
    ;;
  *)
    echo "Unknown DEPLOY_PROFILE '${DEPLOY_PROFILE}'. Use staging-cheap, prod-safe, or prod-scale." >&2
    exit 64
    ;;
esac

MAX_FRAME_BYTES="${MAX_FRAME_BYTES:-524288}"
MAX_HOST_SOCKETS_PER_USER="${MAX_HOST_SOCKETS_PER_USER:-2}"
MAX_CLIENT_SOCKETS_PER_USER="${MAX_CLIENT_SOCKETS_PER_USER:-4}"
MAX_REQUEST_STARTS_PER_MINUTE="${MAX_REQUEST_STARTS_PER_MINUTE:-60}"
MAX_BYTES_PER_MINUTE="${MAX_BYTES_PER_MINUTE:-26214400}"
MAX_IN_FLIGHT_REQUESTS_PER_USER="${MAX_IN_FLIGHT_REQUESTS_PER_USER:-6}"
ENTITLEMENT_CACHE_TTL_SECONDS="${ENTITLEMENT_CACHE_TTL_SECONDS:-60}"
ENTITLEMENT_NEGATIVE_CACHE_TTL_SECONDS="${ENTITLEMENT_NEGATIVE_CACHE_TTL_SECONDS:-15}"
SOCKET_LEASE_SECONDS="${SOCKET_LEASE_SECONDS:-120}"
IN_FLIGHT_LEASE_SECONDS="${IN_FLIGHT_LEASE_SECONDS:-600}"

if [[ -n "${VPC_CONNECTOR}" && ( -n "${DIRECT_VPC_NETWORK}" || -n "${DIRECT_VPC_SUBNET}" ) ]]; then
  echo "Set either VPC_CONNECTOR or DIRECT_VPC_NETWORK/DIRECT_VPC_SUBNET, not both." >&2
  exit 64
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVICE_DIR="${ROOT_DIR}/services/hermes-realtime-relay"

cd "${SERVICE_DIR}"
npm ci
npm run build

IMAGE="gcr.io/${PROJECT_ID}/${SERVICE_NAME}:$(date +%Y%m%d%H%M%S)"
gcloud builds submit --project "${PROJECT_ID}" --tag "${IMAGE}" .

ARGS=(
  run deploy "${SERVICE_NAME}"
  --project "${PROJECT_ID}"
  --region "${REGION}"
  --image "${IMAGE}"
  --platform managed
  --allow-unauthenticated
  --min-instances "${MIN_INSTANCES}"
  --max-instances "${MAX_INSTANCES}"
  --timeout "${REQUEST_TIMEOUT_SECONDS}"
  --concurrency "${CONCURRENCY}"
  --cpu "${CPU}"
  --memory "${MEMORY}"
  --cpu-throttling
  --set-env-vars "^|^REDIS_URL=${REDIS_URL}|ENFORCE_APP_CHECK=${ENFORCE_APP_CHECK}|VERIFY_REVOKED_ID_TOKENS=${VERIFY_REVOKED_ID_TOKENS}|HOSTED_RELAY_PRODUCT_IDS=${HOSTED_RELAY_PRODUCT_IDS}|APP_CHECK_ALLOWED_APP_IDS=${APP_CHECK_ALLOWED_APP_IDS}|MAX_FRAME_BYTES=${MAX_FRAME_BYTES}|MAX_HOST_SOCKETS_PER_USER=${MAX_HOST_SOCKETS_PER_USER}|MAX_CLIENT_SOCKETS_PER_USER=${MAX_CLIENT_SOCKETS_PER_USER}|MAX_REQUEST_STARTS_PER_MINUTE=${MAX_REQUEST_STARTS_PER_MINUTE}|MAX_BYTES_PER_MINUTE=${MAX_BYTES_PER_MINUTE}|MAX_IN_FLIGHT_REQUESTS_PER_USER=${MAX_IN_FLIGHT_REQUESTS_PER_USER}|ENTITLEMENT_CACHE_TTL_SECONDS=${ENTITLEMENT_CACHE_TTL_SECONDS}|ENTITLEMENT_NEGATIVE_CACHE_TTL_SECONDS=${ENTITLEMENT_NEGATIVE_CACHE_TTL_SECONDS}|SOCKET_LEASE_SECONDS=${SOCKET_LEASE_SECONDS}|IN_FLIGHT_LEASE_SECONDS=${IN_FLIGHT_LEASE_SECONDS}"
)

if [[ -n "${SERVICE_ACCOUNT}" ]]; then
  ARGS+=(--service-account "${SERVICE_ACCOUNT}")
fi

if [[ "${SESSION_AFFINITY}" == "true" ]]; then
  ARGS+=(--session-affinity)
else
  ARGS+=(--no-session-affinity)
fi

if [[ -n "${VPC_CONNECTOR}" ]]; then
  ARGS+=(--vpc-connector "${VPC_CONNECTOR}" --vpc-egress "${VPC_EGRESS}")
elif [[ -n "${DIRECT_VPC_NETWORK}" || -n "${DIRECT_VPC_SUBNET}" ]]; then
  [[ -n "${DIRECT_VPC_NETWORK}" ]] && ARGS+=(--network "${DIRECT_VPC_NETWORK}")
  [[ -n "${DIRECT_VPC_SUBNET}" ]] && ARGS+=(--subnet "${DIRECT_VPC_SUBNET}")
  [[ -n "${DIRECT_VPC_TAGS}" ]] && ARGS+=(--network-tags "${DIRECT_VPC_TAGS}")
  ARGS+=(--vpc-egress "${VPC_EGRESS}")
fi

gcloud "${ARGS[@]}"
gcloud run services describe "${SERVICE_NAME}" \
  --project "${PROJECT_ID}" \
  --region "${REGION}" \
  --format 'value(status.url)'
