import Foundation
import Observation

// MARK: - Inbox shelf
//
// Local, app-owned management state for AI Inbox items: pin, colour tag,
// category, manual order, saved, deleted.
//
// **Why this is not a database column.** The AI Inbox splits table ownership
// between two processes — the daemon writes `ai_inbox_items` / `ai_inbox_runs` /
// `ai_inbox_state`, the app writes `ai_inbox_item_state`, and neither side ever
// writes the other's tables (see `ControlPlaneStore+AIInbox`). Adding a column
// to `ai_inbox_item_state` means a new schema version, which in this repo also
// means the Core mirror, the daemon DDL, the Windows C# schema + migration
// count pins, the Linux pins, a regenerated byte-compat `.sqlcipher` fixture,
// the `SCHEMA_SQLITE.sql` hash, and the rollback catalog — ~41 files of blast
// radius for state the daemon never reads.
//
// Everything here is *presentation* state: it changes what the list looks like
// and nothing else. No detector consumes it, no sync ships it, and losing it
// costs a user their arrangement, not their data. That is exactly the bar
// `ControlDeckLayout` clears by persisting its arrangement as JSON under a
// storage key, so this follows the same idiom.
//
// **UserDefaults, not a file in Application Support.** Three reasons:
//   1. It is the precedent already set by `ControlDeckLayout` for arrangement
//      state, and one idiom beats two.
//   2. The inbox's whole design promise is that it renders instantly — reads go
//      straight to SQLite rather than through the daemon for that reason. A
//      file introduces an I/O failure mode (missing directory, sandbox denial,
//      partial write) on the render path; `UserDefaults` does not.
//   3. The payload is bounded on purpose: entries exist only for items a user
//      has explicitly acted on, empty entries are dropped, absent ids are
//      pruned, and `maxEntries` is a hard ceiling. At ~120 bytes an entry the
//      worst case is tens of kilobytes.

/// A named colour tag.
///
/// Every tag carries a **name and a glyph** as well as a colour. Colour is never
/// the only carrier of meaning here: the row shows the name, VoiceOver reads the
/// name, and the menu is a list of names. The colour is the fast visual index,
/// not the message.
///
/// The names are intents rather than hues ("Follow up", not "Orange") so the tag
/// still means something when it is read aloud.
enum InboxColorTag: String, Codable, CaseIterable, Sendable, Identifiable, Hashable {
    case urgent
    case followUp = "follow_up"
    case watching
    case idea
    case done
    case onIce = "on_ice"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .urgent: return "Urgent"
        case .followUp: return "Follow up"
        case .watching: return "Watching"
        case .idea: return "Idea"
        case .done: return "Done"
        case .onIce: return "On ice"
        }
    }

    /// Shape redundancy for the colour. Used everywhere the tag is shown so the
    /// chip is legible without colour vision and over the live backdrop.
    var symbolName: String {
        switch self {
        case .urgent: return "exclamationmark.circle.fill"
        case .followUp: return "arrow.turn.down.right"
        case .watching: return "eye.fill"
        case .idea: return "lightbulb.fill"
        case .done: return "checkmark.circle.fill"
        case .onIce: return "snowflake"
        }
    }
}

/// Starter categories.
///
/// Offered alongside whatever the user has already used so the first "file
/// this somewhere" click does not begin with an empty text field. Nothing here
/// is privileged — a preset is just a string until somebody picks it.
enum InboxCategoryPresets {
    static let all = ["Triage", "Costs", "Reliability", "Reading", "Someday"]
}

/// One item's shelf record. Every field is optional-by-default so a record
/// written by an older (or newer) build decodes rather than throws.
struct InboxShelfEntry: Codable, Equatable, Sendable {
    var pinned: Bool
    var colorTag: InboxColorTag?
    var category: String?
    var sortIndex: Double?
    var savedAt: Date?
    var deletedAt: Date?
    /// Last time any field moved. Only used to pick eviction victims when the
    /// store hits `InboxShelfStore.maxEntries`.
    var updatedAt: Date

    init(
        pinned: Bool = false,
        colorTag: InboxColorTag? = nil,
        category: String? = nil,
        sortIndex: Double? = nil,
        savedAt: Date? = nil,
        deletedAt: Date? = nil,
        updatedAt: Date = .distantPast
    ) {
        self.pinned = pinned
        self.colorTag = colorTag
        self.category = category
        self.sortIndex = sortIndex
        self.savedAt = savedAt
        self.deletedAt = deletedAt
        self.updatedAt = updatedAt
    }

    var isSaved: Bool { savedAt != nil }
    var isDeleted: Bool { deletedAt != nil }

    /// True when the record carries no user intent at all. Empty records are
    /// dropped rather than stored, which is half of what keeps the store small.
    var isEmpty: Bool {
        pinned == false
            && colorTag == nil
            && category == nil
            && sortIndex == nil
            && savedAt == nil
            && deletedAt == nil
    }

    // MARK: Codable

    private enum CodingKeys: String, CodingKey {
        case pinned, colorTag, category, sortIndex, savedAt, deletedAt, updatedAt
    }

    /// Field-by-field lenient decode.
    ///
    /// The synthesized decoder would throw on a record written before a field
    /// existed (`pinned` is not optional) and on a `colorTag` this build does
    /// not ship (a tag added by a newer version). Both are ordinary situations
    /// for state that survives app updates, so each field falls back to its
    /// default independently instead of failing the whole record.
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        pinned = Self.lenient(Bool.self, container, .pinned) ?? false
        colorTag = Self.lenient(InboxColorTag.self, container, .colorTag)
        category = Self.lenient(String.self, container, .category)
        sortIndex = Self.lenient(Double.self, container, .sortIndex)
        savedAt = Self.lenient(Date.self, container, .savedAt)
        deletedAt = Self.lenient(Date.self, container, .deletedAt)
        updatedAt = Self.lenient(Date.self, container, .updatedAt) ?? .distantPast
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pinned, forKey: .pinned)
        try container.encodeIfPresent(colorTag, forKey: .colorTag)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(sortIndex, forKey: .sortIndex)
        try container.encodeIfPresent(savedAt, forKey: .savedAt)
        try container.encodeIfPresent(deletedAt, forKey: .deletedAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }

    private static func lenient<T: Decodable>(
        _ type: T.Type,
        _ container: KeyedDecodingContainer<CodingKeys>,
        _ key: CodingKeys
    ) -> T? {
        // try?-ok(a field this build cannot read falls back to its default)
        guard let value = try? container.decodeIfPresent(type, forKey: key) else { return nil }
        return value
    }
}

// MARK: - Store

/// The shelf itself: one record per item id, loaded once and written back on a
/// coalescing timer.
///
/// `@Observable` so the list re-renders when a tag or pin changes; `@MainActor`
/// because every mutation originates in a click and the store is read straight
/// from a SwiftUI body.
@Observable
@MainActor
final class InboxShelfStore {
    static let storageKey = "inbox.shelf.v1"

    /// Hard ceiling on stored records. Reached only if a profile accumulates
    /// more acted-on items than the inbox ever retains; eviction is oldest
    /// first, and untouched-intent records go before pinned/saved/deleted ones.
    static let maxEntries = 500

    /// Long enough to swallow a drag's worth of index churn, short enough that
    /// a pin survives an immediate quit.
    static let defaultPersistDebounce: TimeInterval = 0.25

    /// Categories are labels on a chip, not prose.
    static let maxCategoryLength = 48

    private(set) var entries: [String: InboxShelfEntry] = [:]

    /// Number of times the store has actually written to `UserDefaults`.
    /// Exposed so a test can prove a drag coalesces into one write. Not
    /// observed: a view redrawing because a write happened would be noise.
    @ObservationIgnored private(set) var writeCount = 0

    private let defaults: UserDefaults
    private let persistDebounce: TimeInterval
    @ObservationIgnored private var persistTask: Task<Void, Never>?

    init(
        defaults: UserDefaults = .standard,
        persistDebounce: TimeInterval = InboxShelfStore.defaultPersistDebounce
    ) {
        self.defaults = defaults
        self.persistDebounce = persistDebounce
        entries = Self.decode(defaults.data(forKey: Self.storageKey))
    }

    // MARK: Reads

    func entry(_ id: String) -> InboxShelfEntry? { entries[id] }

    func isPinned(_ id: String) -> Bool { entries[id]?.pinned == true }
    func isSaved(_ id: String) -> Bool { entries[id]?.isSaved == true }
    func isDeleted(_ id: String) -> Bool { entries[id]?.isDeleted == true }
    func colorTag(_ id: String) -> InboxColorTag? { entries[id]?.colorTag }
    func category(_ id: String) -> String? { entries[id]?.category }
    func sortIndex(_ id: String) -> Double? { entries[id]?.sortIndex }

    /// Every category currently in use, case-insensitively sorted, with deleted
    /// items excluded so a category does not survive in the picker purely
    /// because a trashed item still carries it.
    var categoriesInUse: [String] {
        var seen: [String: String] = [:]
        for entry in entries.values where entry.isDeleted == false {
            guard let category = entry.category, category.isEmpty == false else { continue }
            seen[category.lowercased()] = category
        }
        return seen.values.sorted { $0.localizedCaseInsensitiveCompare($1) == .orderedAscending }
    }

    var deletedIDs: Set<String> {
        Set(entries.filter { $0.value.isDeleted }.keys)
    }

    // MARK: Mutations

    func setPinned(_ pinned: Bool, ids: some Sequence<String>, at now: Date = Date()) {
        mutate(ids: ids, at: now) { $0.pinned = pinned }
    }

    func setColorTag(_ tag: InboxColorTag?, ids: some Sequence<String>, at now: Date = Date()) {
        mutate(ids: ids, at: now) { $0.colorTag = tag }
    }

    /// Moving an item between categories. `nil` (or whitespace) clears it —
    /// there are no folders here, so "move" is exactly "set the category".
    func setCategory(_ category: String?, ids: some Sequence<String>, at now: Date = Date()) {
        let normalized = Self.normalizeCategory(category)
        mutate(ids: ids, at: now) { $0.category = normalized }
    }

    func setSaved(_ saved: Bool, ids: some Sequence<String>, at now: Date = Date()) {
        mutate(ids: ids, at: now) { $0.savedAt = saved ? ($0.savedAt ?? now) : nil }
    }

    func markDeleted(ids: some Sequence<String>, at now: Date = Date()) {
        mutate(ids: ids, at: now) { $0.deletedAt = $0.deletedAt ?? now }
    }

    func clearDeleted(ids: some Sequence<String>, at now: Date = Date()) {
        mutate(ids: ids, at: now) { $0.deletedAt = nil }
    }

    /// Writes a manual arrangement as contiguous indices.
    ///
    /// Rewriting the whole run each time (rather than nudging one float) keeps
    /// the order stable across reloads and immune to precision drift, and the
    /// write is debounced so a drag does not hit `UserDefaults` per frame.
    func applyManualOrder(_ orderedIDs: [String], at now: Date = Date()) {
        guard orderedIDs.isEmpty == false else { return }
        for (index, id) in orderedIDs.enumerated() {
            var entry = entries[id] ?? InboxShelfEntry()
            entry.sortIndex = Double(index)
            entry.updatedAt = now
            entries[id] = entry
        }
        enforceCapacity()
        schedulePersist(debounced: true)
    }

    /// Drops records for ids the inbox no longer has.
    ///
    /// The caller must only pass an **authoritative** id set — pruning against a
    /// filtered page would wipe the arrangement of everything off that page.
    /// `InboxModel` guards that; see `pruneShelfIfNeeded`.
    func prune(keeping knownIDs: Set<String>) {
        let stale = entries.keys.filter { knownIDs.contains($0) == false }
        guard stale.isEmpty == false else { return }
        for id in stale { entries.removeValue(forKey: id) }
        schedulePersist(debounced: false)
    }

    func removeAll() {
        guard entries.isEmpty == false else { return }
        entries.removeAll()
        schedulePersist(debounced: false)
    }

    // MARK: Persistence

    /// Writes any pending debounced change immediately.
    func flush() {
        persistTask?.cancel()
        persistTask = nil
        persistNow()
    }

    private func mutate(
        ids: some Sequence<String>,
        at now: Date,
        _ transform: (inout InboxShelfEntry) -> Void
    ) {
        var changed = false
        for id in ids where id.isEmpty == false {
            let before = entries[id]
            var entry = before ?? InboxShelfEntry()
            transform(&entry)
            entry.updatedAt = now
            if entry.isEmpty {
                if before != nil {
                    entries.removeValue(forKey: id)
                    changed = true
                }
                continue
            }
            // Compare on intent, not on the timestamp we just stamped.
            if before.map({ Self.sameIntent($0, entry) }) != true {
                entries[id] = entry
                changed = true
            }
        }
        guard changed else { return }
        enforceCapacity()
        schedulePersist(debounced: false)
    }

    private static func sameIntent(_ lhs: InboxShelfEntry, _ rhs: InboxShelfEntry) -> Bool {
        lhs.pinned == rhs.pinned
            && lhs.colorTag == rhs.colorTag
            && lhs.category == rhs.category
            && lhs.sortIndex == rhs.sortIndex
            && lhs.savedAt == rhs.savedAt
            && lhs.deletedAt == rhs.deletedAt
    }

    static func normalizeCategory(_ raw: String?) -> String? {
        guard let raw else { return nil }
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.isEmpty == false else { return nil }
        return String(trimmed.prefix(maxCategoryLength))
    }

    /// Bounded growth even when no authoritative id set is ever available:
    /// evict the least recently touched records, and prefer records that only
    /// carry an arrangement over records that carry an explicit keep-or-kill
    /// decision (pinned, saved, deleted).
    private func enforceCapacity() {
        guard entries.count > Self.maxEntries else { return }
        let victims = entries
            .sorted { lhs, rhs in
                let lhsSticky = Self.isSticky(lhs.value)
                let rhsSticky = Self.isSticky(rhs.value)
                if lhsSticky != rhsSticky { return rhsSticky }
                if lhs.value.updatedAt != rhs.value.updatedAt {
                    return lhs.value.updatedAt < rhs.value.updatedAt
                }
                return lhs.key < rhs.key
            }
            .prefix(entries.count - Self.maxEntries)
            .map { $0.key }
        for id in victims { entries.removeValue(forKey: id) }
    }

    private static func isSticky(_ entry: InboxShelfEntry) -> Bool {
        entry.pinned || entry.isSaved || entry.isDeleted
    }

    private func schedulePersist(debounced: Bool) {
        guard debounced, persistDebounce > 0 else {
            persistTask?.cancel()
            persistTask = nil
            persistNow()
            return
        }
        persistTask?.cancel()
        let interval = persistDebounce
        persistTask = Task { [weak self] in
            do {
                try await Task.sleep(nanoseconds: UInt64(interval * 1_000_000_000))
            } catch {
                // Cancelled by a newer edit, which now owns the write. This is
                // the coalescing path, not a failure.
                return
            }
            guard Task.isCancelled == false else { return }
            self?.persistNow()
        }
    }

    private func persistNow() {
        writeCount += 1
        guard entries.isEmpty == false else {
            defaults.removeObject(forKey: Self.storageKey)
            return
        }
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        guard let data = try? encoder.encode(entries) else { return } // try?-ok(unencodable shelf is dropped, never crashes a click)
        defaults.set(data, forKey: Self.storageKey)
    }

    /// A payload this build cannot read at all resets to an empty shelf rather
    /// than trapping. Individual records already survive shape drift on their
    /// own (see `InboxShelfEntry.init(from:)`); this is the outer envelope.
    static func decode(_ data: Data?) -> [String: InboxShelfEntry] {
        guard let data, data.isEmpty == false else { return [:] }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        // try?-ok(unreadable shelf degrades to no arrangement, never a crash)
        guard let decoded = try? decoder.decode([String: InboxShelfEntry].self, from: data) else {
            return [:]
        }
        return decoded
    }

    static func encode(_ entries: [String: InboxShelfEntry]) -> Data? {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        return try? encoder.encode(entries) // try?-ok(mirror of decode; callers treat nil as "nothing to write")
    }
}
