using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using OpenBurnBar.CloudSync.Json;
using OpenBurnBar.CloudSync.Models;
using Xunit;

namespace OpenBurnBar.CloudSync.Tests;

/// <summary>
/// The parity keystone: every ported Firestore model type round-trips
/// BYTE-FOR-BYTE against a committed vector that was generated by encoding the
/// REAL macOS <c>OpenBurnBarFirestoreModels</c> Swift structs with
/// <c>JSONEncoder([.sortedKeys, .withoutEscapingSlashes])</c>. Deserializing the
/// vector into the C# model and re-serializing with <see cref="CanonicalJson"/>
/// must reproduce the exact Swift bytes — proving the C# record's field names,
/// types, optionality (nil-omission), and number formatting match Swift's Codable
/// output across the two languages.
/// </summary>
public sealed class ModelParityTests
{
    private static readonly System.Reflection.Assembly ModelsAssembly = typeof(FirestoreProviderAccountDoc).Assembly;

    private static readonly JsonSerializerOptions ReadOptions = new()
    {
        PropertyNameCaseInsensitive = false,
    };

    public static IEnumerable<object[]> Vectors() =>
        Fixtures.ModelVectorFiles().Select(f => new object[] { Path.GetFileName(f) });

    [Theory]
    [MemberData(nameof(Vectors))]
    public void Model_round_trips_byte_for_byte_against_swift_vector(string fileName)
    {
        byte[] expected = Fixtures.ReadBytes("models", fileName);

        Type modelType = ResolveModelType(fileName);
        object model = JsonSerializer.Deserialize(expected, modelType, ReadOptions)
            ?? throw new InvalidOperationException($"Vector {fileName} decoded to null.");

        byte[] actual = CanonicalJson.SerializeToUtf8Bytes(model, modelType);

        Assert.Equal(
            Encoding.UTF8.GetString(expected),
            Encoding.UTF8.GetString(actual));
    }

    [Fact]
    public void All_fourteen_model_domains_are_represented_by_vectors()
    {
        // Sanity: the vector corpus covers every one of the 14 Firestore model
        // FILES (36 struct types) so no domain silently loses coverage.
        // The 36th type, FirestoreCapabilityToken, is a non-Firestore model
        // (it lives in OpenBurnBarComputerUseCore, not OpenBurnBarFirestoreModels)
        // but is mirrored in the CloudSync C# models for PDP capability-token
        // wire parity, so its byte-for-byte round-trip is exercised here.
        var covered = Fixtures.ModelVectorFiles()
            .Select(f => StripMinSuffix(Path.GetFileNameWithoutExtension(f)))
            .Distinct(StringComparer.Ordinal)
            .ToList();

        Assert.Equal(36, covered.Count);
        foreach (string typeName in covered)
        {
            Assert.NotNull(ModelsAssembly.GetType($"OpenBurnBar.CloudSync.Models.{typeName}"));
        }
    }

    private static Type ResolveModelType(string fileName)
    {
        string typeName = StripMinSuffix(Path.GetFileNameWithoutExtension(fileName));
        return ModelsAssembly.GetType($"OpenBurnBar.CloudSync.Models.{typeName}")
            ?? throw new InvalidOperationException($"No C# model named {typeName} for vector {fileName}.");
    }

    private static string StripMinSuffix(string baseName) =>
        baseName.EndsWith(".min", StringComparison.Ordinal) ? baseName[..^4] : baseName;
}
