import Foundation
import OpenBurnBarCore
import OpenBurnBarComputerUseCore

/// JSON-RPC framing for the Computer Use Playwright driver. Phase 9.
///
/// The driver spawns one long-lived `node` subprocess that hosts a tiny
/// Playwright bridge script. The script reads newline-terminated JSON
/// requests on stdin and writes newline-terminated JSON responses on
/// stdout. Stderr is line-buffered into the daemon log for diagnosis.
///
/// One subprocess per Computer Use session. A fresh
/// `chromium.launch(headless: false)` instance is opened per session so
/// the agent's pages cannot inherit cookies / storage from a prior
/// session that ran under a different scope rule.
public actor OpenBurnBarPlaywrightDriver {
    public enum DriverError: Error, Sendable, Equatable {
        case binaryNotFound
        case bridgeScriptMissing
        case subprocessFailedToStart(String)
        case subprocessExited(Int32)
        case rpcTimeout
        case rpcDecodeFailure(String)
        case rpcRemoteError(String)
        case driverStopped
    }

    /// Request envelope. Mirrors the on-wire JSON the bridge script
    /// reads from stdin. `id` is a monotonic counter generated by the
    /// driver; the bridge echoes it on the response so we can
    /// associate.
    public struct Request: Codable, Sendable {
        public var id: Int
        public var method: String
        public var params: [String: BurnBarJSONValue]

        public init(id: Int, method: String, params: [String: BurnBarJSONValue] = [:]) {
            self.id = id
            self.method = method
            self.params = params
        }
    }

    public struct Response: Codable, Sendable {
        public var id: Int
        public var ok: Bool
        public var result: BurnBarJSONValue?
        public var error: String?
        public var elapsedMillis: Int?
    }

    public struct Configuration: Sendable {
        public let nodeExecutablePath: String
        public let bridgeScriptPath: URL
        public let browserChannel: String?
        public let userDataDirectory: URL?
        public let headless: Bool
        public let perActionTimeoutMillis: Int

        public init(
            nodeExecutablePath: String,
            bridgeScriptPath: URL,
            browserChannel: String? = nil,
            userDataDirectory: URL? = nil,
            headless: Bool = false,
            perActionTimeoutMillis: Int = 10_000
        ) {
            self.nodeExecutablePath = nodeExecutablePath
            self.bridgeScriptPath = bridgeScriptPath
            self.browserChannel = browserChannel
            self.userDataDirectory = userDataDirectory
            self.headless = headless
            self.perActionTimeoutMillis = perActionTimeoutMillis
        }
    }

    public let configuration: Configuration
    public let sessionId: ComputerUseSessionID
    private let logger: BurnBarDaemonLogger

    private var process: Process?
    private var stdinPipe: Pipe?
    private var stdoutPipe: Pipe?
    private var stderrPipe: Pipe?
    private var nextRequestId: Int = 1
    private var pendingContinuations: [Int: CheckedContinuation<Response, Error>] = [:]
    private var stdoutTask: Task<Void, Never>?
    private var stderrTask: Task<Void, Never>?
    private var stoppedExplicitly: Bool = false

    public init(
        configuration: Configuration,
        sessionId: ComputerUseSessionID,
        logger: BurnBarDaemonLogger = BurnBarDaemonLogger(category: "playwright-driver")
    ) {
        self.configuration = configuration
        self.sessionId = sessionId
        self.logger = logger
    }

    deinit {
        // Best-effort cleanup if the caller forgot to call stop().
        process?.terminate()
        stdoutTask?.cancel()
        stderrTask?.cancel()
    }

    // MARK: Lifecycle

    public func start() async throws {
        guard process == nil else { return }
        stoppedExplicitly = false

        guard FileManager.default.isExecutableFile(atPath: configuration.nodeExecutablePath) else {
            throw DriverError.binaryNotFound
        }
        guard FileManager.default.fileExists(atPath: configuration.bridgeScriptPath.path) else {
            throw DriverError.bridgeScriptMissing
        }

        let process = Process()
        let stdin = Pipe()
        let stdout = Pipe()
        let stderr = Pipe()
        process.executableURL = URL(fileURLWithPath: configuration.nodeExecutablePath)

        var args = [configuration.bridgeScriptPath.path]
        if configuration.headless { args.append("--headless") }
        if let channel = configuration.browserChannel { args += ["--channel", channel] }
        if let userData = configuration.userDataDirectory { args += ["--user-data-dir", userData.path] }
        args += ["--session-id", sessionId.rawValue]
        args += ["--per-action-timeout-ms", "\(configuration.perActionTimeoutMillis)"]
        process.arguments = args
        process.standardInput = stdin
        process.standardOutput = stdout
        process.standardError = stderr

        do {
            try process.run()
        } catch {
            throw DriverError.subprocessFailedToStart(error.localizedDescription)
        }

        self.process = process
        self.stdinPipe = stdin
        self.stdoutPipe = stdout
        self.stderrPipe = stderr

        let sessionId = self.sessionId.rawValue
        let logger = self.logger
        stderrTask = Task.detached { [weak self] in
            guard self != nil else { return }
            let handle = stderr.fileHandleForReading
            while !Task.isCancelled {
                let data = handle.availableData
                if data.isEmpty { break }
                if let line = String(data: data, encoding: .utf8) {
                    logger.notice("playwright_stderr", metadata: [
                        "session": sessionId,
                        "line": line.trimmingCharacters(in: .whitespacesAndNewlines)
                    ])
                }
            }
        }

        // Read newline-delimited responses from stdout.
        stdoutTask = Task.detached { [weak self] in
            guard let self else { return }
            await self.runStdoutLoop()
        }
    }

    public func stop() async {
        stoppedExplicitly = true
        process?.terminate()
        stdoutTask?.cancel()
        stderrTask?.cancel()
        process = nil
        stdinPipe = nil
        stdoutPipe = nil
        stderrPipe = nil
        let pending = pendingContinuations
        pendingContinuations.removeAll()
        for (_, cont) in pending { cont.resume(throwing: DriverError.driverStopped) }
    }

    // MARK: RPC actions

    public func click(
        selector: String?,
        positionX: Int? = nil,
        positionY: Int? = nil,
        timeoutMillis: Int? = nil
    ) async throws -> Response {
        try await call(method: "click", params: [
            "selector": selector.map { .string($0) } ?? .null,
            "positionX": positionX.map { .number(Double($0)) } ?? .null,
            "positionY": positionY.map { .number(Double($0)) } ?? .null,
            "timeoutMs": .number(Double(timeoutMillis ?? configuration.perActionTimeoutMillis))
        ])
    }

    public func fill(selector: String, text: String, timeoutMillis: Int? = nil) async throws -> Response {
        try await call(method: "fill", params: [
            "selector": .string(selector),
            "text": .string(text),
            "timeoutMs": .number(Double(timeoutMillis ?? configuration.perActionTimeoutMillis))
        ])
    }

    public func goto(url: String, timeoutMillis: Int? = nil) async throws -> Response {
        try await call(method: "goto", params: [
            "url": .string(url),
            "timeoutMs": .number(Double(timeoutMillis ?? configuration.perActionTimeoutMillis))
        ])
    }

    public func key(_ key: String, modifiers: [String] = []) async throws -> Response {
        try await call(method: "key", params: [
            "key": .string(key),
            "modifiers": .array(modifiers.map { .string($0) })
        ])
    }

    public func select(selector: String, value: String) async throws -> Response {
        try await call(method: "select", params: [
            "selector": .string(selector),
            "value": .string(value)
        ])
    }

    public func screenshot(fullPage: Bool = false) async throws -> Response {
        try await call(method: "screenshot", params: [
            "fullPage": .bool(fullPage)
        ])
    }

    public func extract(selector: String?) async throws -> Response {
        try await call(method: "extract", params: [
            "selector": selector.map { .string($0) } ?? .null
        ])
    }

    public func currentURL() async throws -> Response {
        try await call(method: "current_url", params: [:])
    }

    public func currentTitle() async throws -> Response {
        try await call(method: "current_title", params: [:])
    }

    // MARK: Wire

    private func call(method: String, params: [String: BurnBarJSONValue]) async throws -> Response {
        let id = nextRequestId
        nextRequestId += 1
        let request = Request(id: id, method: method, params: params)
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        var line = try encoder.encode(request)
        line.append(0x0A)
        guard let stdin = stdinPipe else { throw DriverError.driverStopped }
        try stdin.fileHandleForWriting.write(contentsOf: line)

        let timeoutMs = (params["timeoutMs"].flatMap { value -> Double? in
            if case let .number(n) = value { return n }
            return nil
        }) ?? Double(configuration.perActionTimeoutMillis)
        let timeoutNs = UInt64(max(timeoutMs + 2000, 5_000)) * 1_000_000

        return try await withThrowingTaskGroup(of: Response.self) { group in
            group.addTask { [weak self] in
                try await withCheckedThrowingContinuation { cont in
                    Task { [weak self] in
                        guard let self else {
                            cont.resume(throwing: DriverError.driverStopped)
                            return
                        }
                        await self.registerContinuation(id: id, continuation: cont)
                    }
                }
            }
            group.addTask {
                try await Task.sleep(nanoseconds: timeoutNs)
                throw DriverError.rpcTimeout
            }
            defer { group.cancelAll() }
            return try await group.next() ?? Response(id: id, ok: false, result: nil, error: "no response")
        }
    }

    private func registerContinuation(
        id: Int,
        continuation: CheckedContinuation<Response, Error>
    ) {
        pendingContinuations[id] = continuation
    }

    private func resolve(_ response: Response) {
        if let cont = pendingContinuations.removeValue(forKey: response.id) {
            cont.resume(returning: response)
        } else {
            logger.warning("orphan_playwright_response", metadata: [
                "session": sessionId.rawValue,
                "id": "\(response.id)"
            ])
        }
    }

    private func failPending(with error: DriverError) {
        let pending = pendingContinuations
        pendingContinuations.removeAll()
        for (_, cont) in pending { cont.resume(throwing: error) }
    }

    private func runStdoutLoop() async {
        guard let handle = stdoutPipe?.fileHandleForReading else { return }
        let decoder = JSONDecoder()
        var buffer = Data()
        while !Task.isCancelled {
            let chunk = handle.availableData
            if chunk.isEmpty {
                if stoppedExplicitly { return }
                await Task.yield()
                // Brief sleep so a quiet stdout doesn't hot-spin.
                try? await Task.sleep(nanoseconds: 5_000_000)
                continue
            }
            buffer.append(chunk)
            while let newlineIndex = buffer.firstIndex(of: 0x0A) {
                let lineData = buffer[buffer.startIndex..<newlineIndex]
                buffer.removeSubrange(buffer.startIndex...newlineIndex)
                guard !lineData.isEmpty else { continue }
                do {
                    let response = try decoder.decode(Response.self, from: lineData)
                    resolve(response)
                } catch {
                    logger.warning("playwright_decode_failure", metadata: [
                        "session": sessionId.rawValue,
                        "error": String(describing: error)
                    ])
                }
            }
        }
    }
}
