// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!


package uniffi.openburnbar_domain_ffi

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_openburnbar_domain_ffi_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_openburnbar_domain_ffi_rustbuffer_free(buf, status)
        }
    }

    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "openburnbar_domain_ffi"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}


































































































// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            loadIndirect<UniffiLib>(componentName = "openburnbar_domain_ffi")
            .also { lib: UniffiLib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                }
        }

    }

    fun uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_aad_v1(`uid`: RustBuffer.ByValue,`collection`: RustBuffer.ByValue,`docId`: RustBuffer.ByValue,`field`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_aad_v2(`uid`: RustBuffer.ByValue,`collection`: RustBuffer.ByValue,`docId`: RustBuffer.ByValue,`field`: RustBuffer.ByValue,`schemaVersion`: Int,`purpose`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_aes_gcm_open_combined(`combined`: RustBuffer.ByValue,`key`: RustBuffer.ByValue,`aad`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_aes_gcm_open_detached(`nonce`: RustBuffer.ByValue,`ciphertext`: RustBuffer.ByValue,`tag`: RustBuffer.ByValue,`key`: RustBuffer.ByValue,`aad`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_aes_gcm_open_text_detached(`nonce`: RustBuffer.ByValue,`ciphertext`: RustBuffer.ByValue,`tag`: RustBuffer.ByValue,`key`: RustBuffer.ByValue,`aad`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_aes_gcm_seal_combined(`plaintext`: RustBuffer.ByValue,`key`: RustBuffer.ByValue,`nonce`: RustBuffer.ByValue,`aad`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_aes_gcm_seal_detached(`plaintext`: RustBuffer.ByValue,`key`: RustBuffer.ByValue,`nonce`: RustBuffer.ByValue,`aad`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_base64_decode_strict(`value`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_base64_encode(`data`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_expected_session_body_hash(`data`: RustBuffer.ByValue,`key`: RustBuffer.ByValue,`bodyHashVersion`: Int,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_key_id(`key`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_keyed_hash_hex(`data`: RustBuffer.ByValue,`key`: RustBuffer.ByValue,`purpose`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_resolve_aad(`envelopeAad`: RustBuffer.ByValue,`context`: RustBuffer.ByValue,`rejectLegacy`: Byte,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_sha256_hex(`data`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun uniffi_openburnbar_domain_ffi_fn_func_domain_core_abi_version(uniffi_out_err: UniffiRustCallStatus,
    ): Int
    fun uniffi_openburnbar_domain_ffi_fn_func_domain_core_version(uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun uniffi_openburnbar_domain_ffi_fn_func_parse_anthropic_rate_limit_headers(`payload`: RustBuffer.ByValue,`nowUnix`: Long,`shape`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun uniffi_openburnbar_domain_ffi_fn_func_parse_claude_statusline_quota(`payload`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun uniffi_openburnbar_domain_ffi_fn_func_parse_codex_usage_quota(`payload`: RustBuffer.ByValue,`nowUnix`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun uniffi_openburnbar_domain_ffi_fn_func_parse_cursor_usage_quota(`payload`: RustBuffer.ByValue,`userEmail`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun ffi_openburnbar_domain_ffi_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun ffi_openburnbar_domain_ffi_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun ffi_openburnbar_domain_ffi_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun ffi_openburnbar_domain_ffi_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_free_u8(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Byte
    fun ffi_openburnbar_domain_ffi_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_free_i8(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Byte
    fun ffi_openburnbar_domain_ffi_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_free_u16(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Short
    fun ffi_openburnbar_domain_ffi_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_free_i16(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Short
    fun ffi_openburnbar_domain_ffi_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_free_u32(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Int
    fun ffi_openburnbar_domain_ffi_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_free_i32(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Int
    fun ffi_openburnbar_domain_ffi_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_free_u64(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Long
    fun ffi_openburnbar_domain_ffi_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_free_i64(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Long
    fun ffi_openburnbar_domain_ffi_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_free_f32(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Float
    fun ffi_openburnbar_domain_ffi_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_free_f64(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Double
    fun ffi_openburnbar_domain_ffi_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_cancel_pointer(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_free_pointer(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Pointer
    fun ffi_openburnbar_domain_ffi_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    fun ffi_openburnbar_domain_ffi_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_cancel_void(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_free_void(`handle`: Long,
    ): Unit
    fun ffi_openburnbar_domain_ffi_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Unit
    fun uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_aad_v1(
    ): Short
    fun uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_aad_v2(
    ): Short
    fun uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_aes_gcm_open_combined(
    ): Short
    fun uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_aes_gcm_open_detached(
    ): Short
    fun uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_aes_gcm_open_text_detached(
    ): Short
    fun uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_aes_gcm_seal_combined(
    ): Short
    fun uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_aes_gcm_seal_detached(
    ): Short
    fun uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_base64_decode_strict(
    ): Short
    fun uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_base64_encode(
    ): Short
    fun uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_expected_session_body_hash(
    ): Short
    fun uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_key_id(
    ): Short
    fun uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_keyed_hash_hex(
    ): Short
    fun uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_resolve_aad(
    ): Short
    fun uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_sha256_hex(
    ): Short
    fun uniffi_openburnbar_domain_ffi_checksum_func_domain_core_abi_version(
    ): Short
    fun uniffi_openburnbar_domain_ffi_checksum_func_domain_core_version(
    ): Short
    fun uniffi_openburnbar_domain_ffi_checksum_func_parse_anthropic_rate_limit_headers(
    ): Short
    fun uniffi_openburnbar_domain_ffi_checksum_func_parse_claude_statusline_quota(
    ): Short
    fun uniffi_openburnbar_domain_ffi_checksum_func_parse_codex_usage_quota(
    ): Short
    fun uniffi_openburnbar_domain_ffi_checksum_func_parse_cursor_usage_quota(
    ): Short
    fun ffi_openburnbar_domain_ffi_uniffi_contract_version(
    ): Int

}

private fun uniffiCheckContractApiVersion(lib: UniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_openburnbar_domain_ffi_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

private fun uniffiCheckApiChecksums(lib: UniffiLib) {
    if (lib.uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_aad_v1() != 43983.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_aad_v2() != 35572.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_aes_gcm_open_combined() != 9151.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_aes_gcm_open_detached() != 45041.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_aes_gcm_open_text_detached() != 33389.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_aes_gcm_seal_combined() != 15475.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_aes_gcm_seal_detached() != 43222.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_base64_decode_strict() != 52306.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_base64_encode() != 55479.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_expected_session_body_hash() != 32041.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_key_id() != 19743.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_keyed_hash_hex() != 27492.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_resolve_aad() != 62830.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openburnbar_domain_ffi_checksum_func_cloud_vault_sha256_hex() != 55638.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openburnbar_domain_ffi_checksum_func_domain_core_abi_version() != 60924.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openburnbar_domain_ffi_checksum_func_domain_core_version() != 28819.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openburnbar_domain_ffi_checksum_func_parse_anthropic_rate_limit_headers() != 49269.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openburnbar_domain_ffi_checksum_func_parse_claude_statusline_quota() != 44207.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openburnbar_domain_ffi_checksum_func_parse_codex_usage_quota() != 48415.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_openburnbar_domain_ffi_checksum_func_parse_cursor_usage_quota() != 39634.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/**
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterLong: FfiConverter<Long, Long> {
    override fun lift(value: Long): Long {
        return value
    }

    override fun read(buf: ByteBuffer): Long {
        return buf.getLong()
    }

    override fun lower(value: Long): Long {
        return value
    }

    override fun allocationSize(value: Long) = 8UL

    override fun write(value: Long, buf: ByteBuffer) {
        buf.putLong(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterDouble: FfiConverter<Double, Double> {
    override fun lift(value: Double): Double {
        return value
    }

    override fun read(buf: ByteBuffer): Double {
        return buf.getDouble()
    }

    override fun lower(value: Double): Double {
        return value
    }

    override fun allocationSize(value: Double) = 8UL

    override fun write(value: Double, buf: ByteBuffer) {
        buf.putDouble(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}



data class CloudVaultAadContextInput (
    var `uid`: kotlin.String,
    var `collection`: kotlin.String,
    var `docId`: kotlin.String,
    var `field`: kotlin.String,
    var `schemaVersion`: kotlin.UInt,
    var `purpose`: kotlin.String?
) {

    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeCloudVaultAadContextInput: FfiConverterRustBuffer<CloudVaultAadContextInput> {
    override fun read(buf: ByteBuffer): CloudVaultAadContextInput {
        return CloudVaultAadContextInput(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: CloudVaultAadContextInput) = (
            FfiConverterString.allocationSize(value.`uid`) +
            FfiConverterString.allocationSize(value.`collection`) +
            FfiConverterString.allocationSize(value.`docId`) +
            FfiConverterString.allocationSize(value.`field`) +
            FfiConverterUInt.allocationSize(value.`schemaVersion`) +
            FfiConverterOptionalString.allocationSize(value.`purpose`)
    )

    override fun write(value: CloudVaultAadContextInput, buf: ByteBuffer) {
            FfiConverterString.write(value.`uid`, buf)
            FfiConverterString.write(value.`collection`, buf)
            FfiConverterString.write(value.`docId`, buf)
            FfiConverterString.write(value.`field`, buf)
            FfiConverterUInt.write(value.`schemaVersion`, buf)
            FfiConverterOptionalString.write(value.`purpose`, buf)
    }
}



data class CloudVaultAesGcmDetachedBox (
    var `nonce`: kotlin.ByteArray,
    var `ciphertext`: kotlin.ByteArray,
    var `tag`: kotlin.ByteArray
) {

    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeCloudVaultAesGcmDetachedBox: FfiConverterRustBuffer<CloudVaultAesGcmDetachedBox> {
    override fun read(buf: ByteBuffer): CloudVaultAesGcmDetachedBox {
        return CloudVaultAesGcmDetachedBox(
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
        )
    }

    override fun allocationSize(value: CloudVaultAesGcmDetachedBox) = (
            FfiConverterByteArray.allocationSize(value.`nonce`) +
            FfiConverterByteArray.allocationSize(value.`ciphertext`) +
            FfiConverterByteArray.allocationSize(value.`tag`)
    )

    override fun write(value: CloudVaultAesGcmDetachedBox, buf: ByteBuffer) {
            FfiConverterByteArray.write(value.`nonce`, buf)
            FfiConverterByteArray.write(value.`ciphertext`, buf)
            FfiConverterByteArray.write(value.`tag`, buf)
    }
}



data class QuotaBucket (
    var `key`: kotlin.String,
    var `label`: kotlin.String,
    var `windowKind`: QuotaWindowKind,
    var `usedValue`: kotlin.Double?,
    var `limitValue`: kotlin.Double?,
    var `remainingValue`: kotlin.Double?,
    var `usedPercent`: kotlin.Double?,
    var `resetsAtUnix`: kotlin.Double?,
    var `unit`: QuotaUnit,
    var `isEstimated`: kotlin.Boolean
) {

    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeQuotaBucket: FfiConverterRustBuffer<QuotaBucket> {
    override fun read(buf: ByteBuffer): QuotaBucket {
        return QuotaBucket(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterTypeQuotaWindowKind.read(buf),
            FfiConverterOptionalDouble.read(buf),
            FfiConverterOptionalDouble.read(buf),
            FfiConverterOptionalDouble.read(buf),
            FfiConverterOptionalDouble.read(buf),
            FfiConverterOptionalDouble.read(buf),
            FfiConverterTypeQuotaUnit.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: QuotaBucket) = (
            FfiConverterString.allocationSize(value.`key`) +
            FfiConverterString.allocationSize(value.`label`) +
            FfiConverterTypeQuotaWindowKind.allocationSize(value.`windowKind`) +
            FfiConverterOptionalDouble.allocationSize(value.`usedValue`) +
            FfiConverterOptionalDouble.allocationSize(value.`limitValue`) +
            FfiConverterOptionalDouble.allocationSize(value.`remainingValue`) +
            FfiConverterOptionalDouble.allocationSize(value.`usedPercent`) +
            FfiConverterOptionalDouble.allocationSize(value.`resetsAtUnix`) +
            FfiConverterTypeQuotaUnit.allocationSize(value.`unit`) +
            FfiConverterBoolean.allocationSize(value.`isEstimated`)
    )

    override fun write(value: QuotaBucket, buf: ByteBuffer) {
            FfiConverterString.write(value.`key`, buf)
            FfiConverterString.write(value.`label`, buf)
            FfiConverterTypeQuotaWindowKind.write(value.`windowKind`, buf)
            FfiConverterOptionalDouble.write(value.`usedValue`, buf)
            FfiConverterOptionalDouble.write(value.`limitValue`, buf)
            FfiConverterOptionalDouble.write(value.`remainingValue`, buf)
            FfiConverterOptionalDouble.write(value.`usedPercent`, buf)
            FfiConverterOptionalDouble.write(value.`resetsAtUnix`, buf)
            FfiConverterTypeQuotaUnit.write(value.`unit`, buf)
            FfiConverterBoolean.write(value.`isEstimated`, buf)
    }
}



data class QuotaParseResult (
    var `status`: QuotaParseStatus,
    var `snapshot`: QuotaSnapshot
) {

    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeQuotaParseResult: FfiConverterRustBuffer<QuotaParseResult> {
    override fun read(buf: ByteBuffer): QuotaParseResult {
        return QuotaParseResult(
            FfiConverterTypeQuotaParseStatus.read(buf),
            FfiConverterTypeQuotaSnapshot.read(buf),
        )
    }

    override fun allocationSize(value: QuotaParseResult) = (
            FfiConverterTypeQuotaParseStatus.allocationSize(value.`status`) +
            FfiConverterTypeQuotaSnapshot.allocationSize(value.`snapshot`)
    )

    override fun write(value: QuotaParseResult, buf: ByteBuffer) {
            FfiConverterTypeQuotaParseStatus.write(value.`status`, buf)
            FfiConverterTypeQuotaSnapshot.write(value.`snapshot`, buf)
    }
}



data class QuotaSnapshot (
    var `provider`: kotlin.String,
    var `source`: QuotaSourceKind,
    var `confidence`: QuotaConfidence,
    var `statusMessage`: kotlin.String,
    var `nowUnix`: kotlin.Long?,
    var `buckets`: List<QuotaBucket>
) {

    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeQuotaSnapshot: FfiConverterRustBuffer<QuotaSnapshot> {
    override fun read(buf: ByteBuffer): QuotaSnapshot {
        return QuotaSnapshot(
            FfiConverterString.read(buf),
            FfiConverterTypeQuotaSourceKind.read(buf),
            FfiConverterTypeQuotaConfidence.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalLong.read(buf),
            FfiConverterSequenceTypeQuotaBucket.read(buf),
        )
    }

    override fun allocationSize(value: QuotaSnapshot) = (
            FfiConverterString.allocationSize(value.`provider`) +
            FfiConverterTypeQuotaSourceKind.allocationSize(value.`source`) +
            FfiConverterTypeQuotaConfidence.allocationSize(value.`confidence`) +
            FfiConverterString.allocationSize(value.`statusMessage`) +
            FfiConverterOptionalLong.allocationSize(value.`nowUnix`) +
            FfiConverterSequenceTypeQuotaBucket.allocationSize(value.`buckets`)
    )

    override fun write(value: QuotaSnapshot, buf: ByteBuffer) {
            FfiConverterString.write(value.`provider`, buf)
            FfiConverterTypeQuotaSourceKind.write(value.`source`, buf)
            FfiConverterTypeQuotaConfidence.write(value.`confidence`, buf)
            FfiConverterString.write(value.`statusMessage`, buf)
            FfiConverterOptionalLong.write(value.`nowUnix`, buf)
            FfiConverterSequenceTypeQuotaBucket.write(value.`buckets`, buf)
    }
}




enum class AnthropicCredentialShape {

    OAUTH_BEARER,
    CONSOLE_API_KEY;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeAnthropicCredentialShape: FfiConverterRustBuffer<AnthropicCredentialShape> {
    override fun read(buf: ByteBuffer) = try {
        AnthropicCredentialShape.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: AnthropicCredentialShape) = 4UL

    override fun write(value: AnthropicCredentialShape, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}







sealed class CloudVaultFfiException: kotlin.Exception() {

    class InvalidKeyLength(
        ) : CloudVaultFfiException() {
        override val message
            get() = ""
    }

    class InvalidAadPart(
        ) : CloudVaultFfiException() {
        override val message
            get() = ""
    }

    class InvalidSchemaVersion(
        ) : CloudVaultFfiException() {
        override val message
            get() = ""
    }

    class AadMismatch(
        ) : CloudVaultFfiException() {
        override val message
            get() = ""
    }

    class LegacyAadRejected(
        ) : CloudVaultFfiException() {
        override val message
            get() = ""
    }

    class UnsupportedHashVersion(
        ) : CloudVaultFfiException() {
        override val message
            get() = ""
    }

    class DerivationFailure(
        ) : CloudVaultFfiException() {
        override val message
            get() = ""
    }

    class InvalidNonceLength(
        ) : CloudVaultFfiException() {
        override val message
            get() = ""
    }

    class InvalidCombinedLength(
        ) : CloudVaultFfiException() {
        override val message
            get() = ""
    }

    class AuthenticationFailed(
        ) : CloudVaultFfiException() {
        override val message
            get() = ""
    }

    class InvalidUtf8(
        ) : CloudVaultFfiException() {
        override val message
            get() = ""
    }

    class InvalidBase64(
        ) : CloudVaultFfiException() {
        override val message
            get() = ""
    }


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<CloudVaultFfiException> {
        override fun lift(error_buf: RustBuffer.ByValue): CloudVaultFfiException = FfiConverterTypeCloudVaultFfiError.lift(error_buf)
    }


}

/**
 * @suppress
 */
public object FfiConverterTypeCloudVaultFfiError : FfiConverterRustBuffer<CloudVaultFfiException> {
    override fun read(buf: ByteBuffer): CloudVaultFfiException {


        return when(buf.getInt()) {
            1 -> CloudVaultFfiException.InvalidKeyLength()
            2 -> CloudVaultFfiException.InvalidAadPart()
            3 -> CloudVaultFfiException.InvalidSchemaVersion()
            4 -> CloudVaultFfiException.AadMismatch()
            5 -> CloudVaultFfiException.LegacyAadRejected()
            6 -> CloudVaultFfiException.UnsupportedHashVersion()
            7 -> CloudVaultFfiException.DerivationFailure()
            8 -> CloudVaultFfiException.InvalidNonceLength()
            9 -> CloudVaultFfiException.InvalidCombinedLength()
            10 -> CloudVaultFfiException.AuthenticationFailed()
            11 -> CloudVaultFfiException.InvalidUtf8()
            12 -> CloudVaultFfiException.InvalidBase64()
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: CloudVaultFfiException): ULong {
        return when(value) {
            is CloudVaultFfiException.InvalidKeyLength -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is CloudVaultFfiException.InvalidAadPart -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is CloudVaultFfiException.InvalidSchemaVersion -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is CloudVaultFfiException.AadMismatch -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is CloudVaultFfiException.LegacyAadRejected -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is CloudVaultFfiException.UnsupportedHashVersion -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is CloudVaultFfiException.DerivationFailure -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is CloudVaultFfiException.InvalidNonceLength -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is CloudVaultFfiException.InvalidCombinedLength -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is CloudVaultFfiException.AuthenticationFailed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is CloudVaultFfiException.InvalidUtf8 -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is CloudVaultFfiException.InvalidBase64 -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
        }
    }

    override fun write(value: CloudVaultFfiException, buf: ByteBuffer) {
        when(value) {
            is CloudVaultFfiException.InvalidKeyLength -> {
                buf.putInt(1)
                Unit
            }
            is CloudVaultFfiException.InvalidAadPart -> {
                buf.putInt(2)
                Unit
            }
            is CloudVaultFfiException.InvalidSchemaVersion -> {
                buf.putInt(3)
                Unit
            }
            is CloudVaultFfiException.AadMismatch -> {
                buf.putInt(4)
                Unit
            }
            is CloudVaultFfiException.LegacyAadRejected -> {
                buf.putInt(5)
                Unit
            }
            is CloudVaultFfiException.UnsupportedHashVersion -> {
                buf.putInt(6)
                Unit
            }
            is CloudVaultFfiException.DerivationFailure -> {
                buf.putInt(7)
                Unit
            }
            is CloudVaultFfiException.InvalidNonceLength -> {
                buf.putInt(8)
                Unit
            }
            is CloudVaultFfiException.InvalidCombinedLength -> {
                buf.putInt(9)
                Unit
            }
            is CloudVaultFfiException.AuthenticationFailed -> {
                buf.putInt(10)
                Unit
            }
            is CloudVaultFfiException.InvalidUtf8 -> {
                buf.putInt(11)
                Unit
            }
            is CloudVaultFfiException.InvalidBase64 -> {
                buf.putInt(12)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




enum class CloudVaultHashPurpose {

    BLOB_INTEGRITY,
    SESSION_BODY,
    SESSION_CHUNK,
    PROJECT_MEMORY_CONTENT;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeCloudVaultHashPurpose: FfiConverterRustBuffer<CloudVaultHashPurpose> {
    override fun read(buf: ByteBuffer) = try {
        CloudVaultHashPurpose.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: CloudVaultHashPurpose) = 4UL

    override fun write(value: CloudVaultHashPurpose, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class QuotaConfidence {

    EXACT,
    ESTIMATED,
    UNAVAILABLE;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeQuotaConfidence: FfiConverterRustBuffer<QuotaConfidence> {
    override fun read(buf: ByteBuffer) = try {
        QuotaConfidence.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: QuotaConfidence) = 4UL

    override fun write(value: QuotaConfidence, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class QuotaParseStatus {

    PARSED,
    EMPTY,
    MALFORMED;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeQuotaParseStatus: FfiConverterRustBuffer<QuotaParseStatus> {
    override fun read(buf: ByteBuffer) = try {
        QuotaParseStatus.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: QuotaParseStatus) = 4UL

    override fun write(value: QuotaParseStatus, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class QuotaSourceKind {

    OFFICIAL_API,
    LOCAL_CLI,
    LOCAL_SESSION,
    MANUAL_ESTIMATE,
    UNAVAILABLE;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeQuotaSourceKind: FfiConverterRustBuffer<QuotaSourceKind> {
    override fun read(buf: ByteBuffer) = try {
        QuotaSourceKind.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: QuotaSourceKind) = 4UL

    override fun write(value: QuotaSourceKind, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class QuotaUnit {

    PERCENT,
    REQUESTS,
    TOKENS,
    SESSIONS,
    LINES,
    FILES,
    COUNT,
    CURRENCY;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeQuotaUnit: FfiConverterRustBuffer<QuotaUnit> {
    override fun read(buf: ByteBuffer) = try {
        QuotaUnit.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: QuotaUnit) = 4UL

    override fun write(value: QuotaUnit, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class QuotaWindowKind {

    ROLLING_HOURS,
    ROLLING_DAYS,
    DAILY,
    WEEKLY,
    MONTHLY,
    LIFETIME,
    CUSTOM;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeQuotaWindowKind: FfiConverterRustBuffer<QuotaWindowKind> {
    override fun read(buf: ByteBuffer) = try {
        QuotaWindowKind.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: QuotaWindowKind) = 4UL

    override fun write(value: QuotaWindowKind, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






/**
 * @suppress
 */
public object FfiConverterOptionalLong: FfiConverterRustBuffer<kotlin.Long?> {
    override fun read(buf: ByteBuffer): kotlin.Long? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterLong.read(buf)
    }

    override fun allocationSize(value: kotlin.Long?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterLong.allocationSize(value)
        }
    }

    override fun write(value: kotlin.Long?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterLong.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalDouble: FfiConverterRustBuffer<kotlin.Double?> {
    override fun read(buf: ByteBuffer): kotlin.Double? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterDouble.read(buf)
    }

    override fun allocationSize(value: kotlin.Double?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterDouble.allocationSize(value)
        }
    }

    override fun write(value: kotlin.Double?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterDouble.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeQuotaBucket: FfiConverterRustBuffer<List<QuotaBucket>> {
    override fun read(buf: ByteBuffer): List<QuotaBucket> {
        val len = buf.getInt()
        return List<QuotaBucket>(len) {
            FfiConverterTypeQuotaBucket.read(buf)
        }
    }

    override fun allocationSize(value: List<QuotaBucket>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeQuotaBucket.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<QuotaBucket>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeQuotaBucket.write(it, buf)
        }
    }
}
    @Throws(CloudVaultFfiException::class) fun `cloudVaultAadV1`(`uid`: kotlin.String, `collection`: kotlin.String, `docId`: kotlin.String, `field`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(CloudVaultFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_aad_v1(
        FfiConverterString.lower(`uid`),FfiConverterString.lower(`collection`),FfiConverterString.lower(`docId`),FfiConverterString.lower(`field`),_status)
}
    )
    }


    @Throws(CloudVaultFfiException::class) fun `cloudVaultAadV2`(`uid`: kotlin.String, `collection`: kotlin.String, `docId`: kotlin.String, `field`: kotlin.String, `schemaVersion`: kotlin.UInt, `purpose`: kotlin.String?): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(CloudVaultFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_aad_v2(
        FfiConverterString.lower(`uid`),FfiConverterString.lower(`collection`),FfiConverterString.lower(`docId`),FfiConverterString.lower(`field`),FfiConverterUInt.lower(`schemaVersion`),FfiConverterOptionalString.lower(`purpose`),_status)
}
    )
    }


    @Throws(CloudVaultFfiException::class) fun `cloudVaultAesGcmOpenCombined`(`combined`: kotlin.ByteArray, `key`: kotlin.ByteArray, `aad`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CloudVaultFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_aes_gcm_open_combined(
        FfiConverterByteArray.lower(`combined`),FfiConverterByteArray.lower(`key`),FfiConverterByteArray.lower(`aad`),_status)
}
    )
    }


    @Throws(CloudVaultFfiException::class) fun `cloudVaultAesGcmOpenDetached`(`nonce`: kotlin.ByteArray, `ciphertext`: kotlin.ByteArray, `tag`: kotlin.ByteArray, `key`: kotlin.ByteArray, `aad`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CloudVaultFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_aes_gcm_open_detached(
        FfiConverterByteArray.lower(`nonce`),FfiConverterByteArray.lower(`ciphertext`),FfiConverterByteArray.lower(`tag`),FfiConverterByteArray.lower(`key`),FfiConverterByteArray.lower(`aad`),_status)
}
    )
    }


    @Throws(CloudVaultFfiException::class) fun `cloudVaultAesGcmOpenTextDetached`(`nonce`: kotlin.ByteArray, `ciphertext`: kotlin.ByteArray, `tag`: kotlin.ByteArray, `key`: kotlin.ByteArray, `aad`: kotlin.ByteArray): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(CloudVaultFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_aes_gcm_open_text_detached(
        FfiConverterByteArray.lower(`nonce`),FfiConverterByteArray.lower(`ciphertext`),FfiConverterByteArray.lower(`tag`),FfiConverterByteArray.lower(`key`),FfiConverterByteArray.lower(`aad`),_status)
}
    )
    }


    @Throws(CloudVaultFfiException::class) fun `cloudVaultAesGcmSealCombined`(`plaintext`: kotlin.ByteArray, `key`: kotlin.ByteArray, `nonce`: kotlin.ByteArray, `aad`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CloudVaultFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_aes_gcm_seal_combined(
        FfiConverterByteArray.lower(`plaintext`),FfiConverterByteArray.lower(`key`),FfiConverterByteArray.lower(`nonce`),FfiConverterByteArray.lower(`aad`),_status)
}
    )
    }


    @Throws(CloudVaultFfiException::class) fun `cloudVaultAesGcmSealDetached`(`plaintext`: kotlin.ByteArray, `key`: kotlin.ByteArray, `nonce`: kotlin.ByteArray, `aad`: kotlin.ByteArray): CloudVaultAesGcmDetachedBox {
            return FfiConverterTypeCloudVaultAesGcmDetachedBox.lift(
    uniffiRustCallWithError(CloudVaultFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_aes_gcm_seal_detached(
        FfiConverterByteArray.lower(`plaintext`),FfiConverterByteArray.lower(`key`),FfiConverterByteArray.lower(`nonce`),FfiConverterByteArray.lower(`aad`),_status)
}
    )
    }


    @Throws(CloudVaultFfiException::class) fun `cloudVaultBase64DecodeStrict`(`value`: kotlin.String): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CloudVaultFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_base64_decode_strict(
        FfiConverterString.lower(`value`),_status)
}
    )
    }

 fun `cloudVaultBase64Encode`(`data`: kotlin.ByteArray): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_base64_encode(
        FfiConverterByteArray.lower(`data`),_status)
}
    )
    }


    @Throws(CloudVaultFfiException::class) fun `cloudVaultExpectedSessionBodyHash`(`data`: kotlin.ByteArray, `key`: kotlin.ByteArray, `bodyHashVersion`: kotlin.UInt): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(CloudVaultFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_expected_session_body_hash(
        FfiConverterByteArray.lower(`data`),FfiConverterByteArray.lower(`key`),FfiConverterUInt.lower(`bodyHashVersion`),_status)
}
    )
    }


    @Throws(CloudVaultFfiException::class) fun `cloudVaultKeyId`(`key`: kotlin.ByteArray): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(CloudVaultFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_key_id(
        FfiConverterByteArray.lower(`key`),_status)
}
    )
    }


    @Throws(CloudVaultFfiException::class) fun `cloudVaultKeyedHashHex`(`data`: kotlin.ByteArray, `key`: kotlin.ByteArray, `purpose`: CloudVaultHashPurpose): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(CloudVaultFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_keyed_hash_hex(
        FfiConverterByteArray.lower(`data`),FfiConverterByteArray.lower(`key`),FfiConverterTypeCloudVaultHashPurpose.lower(`purpose`),_status)
}
    )
    }


    @Throws(CloudVaultFfiException::class) fun `cloudVaultResolveAad`(`envelopeAad`: kotlin.String, `context`: CloudVaultAadContextInput, `rejectLegacy`: kotlin.Boolean): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(CloudVaultFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_resolve_aad(
        FfiConverterString.lower(`envelopeAad`),FfiConverterTypeCloudVaultAadContextInput.lower(`context`),FfiConverterBoolean.lower(`rejectLegacy`),_status)
}
    )
    }

 fun `cloudVaultSha256Hex`(`data`: kotlin.ByteArray): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_openburnbar_domain_ffi_fn_func_cloud_vault_sha256_hex(
        FfiConverterByteArray.lower(`data`),_status)
}
    )
    }

 fun `domainCoreAbiVersion`(): kotlin.UInt {
            return FfiConverterUInt.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_openburnbar_domain_ffi_fn_func_domain_core_abi_version(
        _status)
}
    )
    }

 fun `domainCoreVersion`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_openburnbar_domain_ffi_fn_func_domain_core_version(
        _status)
}
    )
    }

 fun `parseAnthropicRateLimitHeaders`(`payload`: kotlin.ByteArray, `nowUnix`: kotlin.Long, `shape`: AnthropicCredentialShape): QuotaParseResult {
            return FfiConverterTypeQuotaParseResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_openburnbar_domain_ffi_fn_func_parse_anthropic_rate_limit_headers(
        FfiConverterByteArray.lower(`payload`),FfiConverterLong.lower(`nowUnix`),FfiConverterTypeAnthropicCredentialShape.lower(`shape`),_status)
}
    )
    }

 fun `parseClaudeStatuslineQuota`(`payload`: kotlin.ByteArray): QuotaParseResult {
            return FfiConverterTypeQuotaParseResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_openburnbar_domain_ffi_fn_func_parse_claude_statusline_quota(
        FfiConverterByteArray.lower(`payload`),_status)
}
    )
    }

 fun `parseCodexUsageQuota`(`payload`: kotlin.ByteArray, `nowUnix`: kotlin.Long): QuotaParseResult {
            return FfiConverterTypeQuotaParseResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_openburnbar_domain_ffi_fn_func_parse_codex_usage_quota(
        FfiConverterByteArray.lower(`payload`),FfiConverterLong.lower(`nowUnix`),_status)
}
    )
    }

 fun `parseCursorUsageQuota`(`payload`: kotlin.ByteArray, `userEmail`: kotlin.String?): QuotaParseResult {
            return FfiConverterTypeQuotaParseResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_openburnbar_domain_ffi_fn_func_parse_cursor_usage_quota(
        FfiConverterByteArray.lower(`payload`),FfiConverterOptionalString.lower(`userEmail`),_status)
}
    )
    }
