#!/usr/bin/env bash
# Install repo git hooks into this clone's .git/hooks. Idempotent; run once per
# clone. Coexists with the wiki post-commit hook (scripts/wiki/install-hooks.sh)
# by installing a distinct pre-push hook rather than taking over core.hooksPath.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
hook_dir="$(git -C "${repo_root}" rev-parse --git-path hooks)"
mkdir -p "${hook_dir}"

src="${repo_root}/scripts/hooks/pre-push"
dest="${hook_dir}/pre-push"

write_chained_wrapper() {
  local original_description="$1"
  local tmp
  tmp="$(mktemp)"
  {
    echo "#!/usr/bin/env bash"
    echo "# Wrapper generated by install-git-hooks.sh."
    echo "# Chains the preserve-tag guard with the pre-existing pre-push hook."
    echo "# Original hook: ${original_description}"
    echo 'set -euo pipefail'
    echo ''
    echo '# Tee stdin to a temp file so both the guard and the original hook see it.'
    echo 'stdin_cache="$(mktemp)"'
    echo 'trap '\''rm -f "${stdin_cache}"'\'' EXIT'
    echo 'cat > "${stdin_cache}"'
    echo ''
    echo '# Preserve the remote name and URL arguments supplied by Git.'
    echo 'bash "${0}.guard" "$@" < "${stdin_cache}"'
    echo 'bash "${0}.original" "$@" < "${stdin_cache}"'
  } > "${tmp}"
  cp "${tmp}" "${dest}"
  rm -f "${tmp}"
  chmod +x "${dest}"
}

if [[ -f "${dest}.guard" && -f "${dest}.original" ]]; then
  cp "${src}" "${dest}.guard"
  chmod +x "${dest}.guard" "${dest}.original"
  write_chained_wrapper "${dest}.original"
  echo "Refreshed chained preserve-tag guard -> ${dest}"
  exit 0
fi

if [[ -f "${dest}" ]] && ! grep -q "preserve/\* tags" "${dest}" 2>/dev/null && [[ ! -f "${dest}.guard" ]]; then
  # An unrelated pre-push hook already exists. Chain the guard so successful
  # installation means the guard is actually present. We create a wrapper that
  # tees stdin to both the guard and the existing hook: the guard runs first
  # and exits non-zero if a preserve/* tag is detected, and the existing hook
  # logic also receives the full stdin.
  existing_backup="${dest}.pre-existing.$(date +%s)"
  cp "${dest}" "${existing_backup}"
  # Save the guard and the original hook alongside the wrapper before replacing
  # the entry point. Git LFS and other pre-existing hooks depend on Git's remote
  # name and URL arguments, so the generated wrapper forwards "$@" unchanged.
  cp "${src}" "${dest}.guard"
  chmod +x "${dest}.guard"
  cp "${existing_backup}" "${dest}.original"
  chmod +x "${dest}.original"
  write_chained_wrapper "${existing_backup}"
  echo "Chained preserve-tag guard into existing pre-push hook -> ${dest}"
  echo "  Guard:   ${dest}.guard"
  echo "  Original: ${dest}.original"
  echo "  Backup:   ${existing_backup}"
  exit 0
fi

cp "${src}" "${dest}"
chmod +x "${dest}"
echo "Installed pre-push guard -> ${dest}"
